### ISSUE TITLE
renameColumn drops "NOT NULL" attribute

### ISSUE THREAD

**Issue by gabe-alex** [tgriesser/knex#1324] opened 2016-04-01 20:24 UTC
Happens with MySQL, don't know about other DBs.
I checked for other attributes as well: UNSIGNED and ZEROFILL remain. DEFAULT gets changed to NULL. Checked using INT and VARCHAR columns.

**Comment by wubzz** [comment] 2016-04-01 20:49
Closing as duplicate of referenced issue, let's continue there.

**Closed by wubzz** 2016-04-01 20:49 UTC
Labels: duplicate
