### ISSUE TITLE
Insert shows all empty values.

### ISSUE THREAD

**Issue by ktstowell** [tgriesser/knex#1407] opened 2016-05-14 18:23 UTC
Hi all,

I am rather new to this library and have run across a problem I have not been able to find a solution for   on the interwebs.

Here is my Knex connection:

`Knex({client: 'pg', connection: config.DB, searchPath:'syp,public', debug: true})`

Here is my insert:

```
Knex('users')
    .returning('id')
    .insert(data)
    .then(function(user) {
      console.log(user);
    }, function(err) {
      console.log(err)
    });
```

This is my `data` from the above query:

```
{   
    "first_name": "Kenneth",
    "last_name": "Stowell",
    "email": "ken@bakuahtsu.codes" }
```

The resulting error is:

```
code:"42703"
file:"parse_target.c"
length:119
line:"943"
name:"error"
position:"230"
routine:"checkInsertTargets"
severity:"ERROR"
```

Which would make sense as the debugger is showing the following as the sql:

```
sql:"insert into "users" ("first_name", "last_name", "email") values (?, ?, ?) returning "id""
```

I hope I am just making a newbie mistake but I cannot for the life of me figure out why. It appears to be making the bindings correctly but never applying them.

Any help appreciated!

**Comment by jurko-gospodnetic** [comment] 2016-05-15 05:16
Could you give some more information on the problem needed to reproduce it?

For example:
- exact `knex` version used
- exact `Postgres` version used
- exact `user` database table schema
- complete output of `.toSQL()` on your `knex` SQL command object, including its `binding` property
- a complete but minimal javascript module that you actually used to reproduce the issue, e.g. usin g `node.js`

**Comment by rhys-vdw** [comment] 2016-05-16 11:10
@jurko-gospodnetic That's a good list for an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates), which we really need. I do happen to know that this issue is true for all versions of Knex.

@ktstowell Actually this is how `debug: true` works (and also `DEBUG=knex:query`). It logs the raw string as provided to the client, but not the bindings (for some reason). I'm not sure why this decision was made, but it is irritating.

Perhaps we can change this to print the bindings as well?

**Comment by rhys-vdw** [comment] 2016-05-16 11:11
@elhigu, @wubzz any reason you can think of why we might not be logging bindings in debug mode?

**Comment by elhigu** [comment] 2016-05-16 12:36
I have no idea.

**Comment by wubzz** [comment] 2016-05-16 16:29
@rhys-vdw As far as I know it also logs the bindings, at least when applied via knex config object.

```javascript
knex = knex({
connection: {...},
debug: true
});

knex('TestTable').where('TestColumn', 'TestValue').select()
.then(_.noop)
//
{ method: 'select',
  options: {},
  timeout: false,
  bindings: [ 'TestValue' ],
  sql: 'select * from "TestTable" where "TestColumn" = ?'
 }
```

**Comment by ktstowell** [comment] 2016-05-19 17:49
Hi all,

Thanks for the replies. There was another error not piped to stdio from within the pqsql docker container. It took for ever to find but has been remedied.

Feel free to close this on my account. The debug bindings thing would be a nice change, however.

**Comment by wubzz** [comment] 2018-02-22 12:48
Bindings are logged by DEBUG flag since 2016, closing.

**Closed by wubzz** 2018-02-22 12:48 UTC
Labels: feature request
