### ISSUE TITLE
Update not actually updating data

### ISSUE THREAD

**Issue by mschoendorf** [tgriesser/knex#1522] opened 2016-06-20 23:22 UTC
Hi,

I'm executing an update on a row in my 'field' table where the type was previously '2':

```
    return this.knex.table('field')
        .where({id : 1 })
        .update({type : 3})
        .returning('*')
```

This call does not fail, but the return shows that the type is STILL 2 and querying postgres shows that is in in fact still 2. Other calls, such as insert, are working fine.

Furthermore, I added a .toQuery() and copied and pasted the query directly to my database, and that worked (type was updated to 3).

**Comment by tgriesser** [comment] 2016-06-20 23:41
So this is something that will probably be addressed before 1.0 (at least with a warning), but queries aren't actually executed until something triggers the promise (calling `.then`, `.catch`, etc. or [another associated method](http://knexjs.org/#Interfaces)).

If you put a `.then()` at the end of the `.returning('*')` does the query run? If that's not the issue is there any chance you're in a transaction that isn't being committed?

**Comment by mschoendorf** [comment] 2016-06-21 20:19
I think I might have debugged it. I had a ".first()" on the end of the
update call, which I added when I realized that the return gives a list of
rows when I just wanted the first one. Interestingly, this made the update
return the first row as expected, but prevented the update from actually
going through. Happy to close.

Megan Schoendorf
Check us out! www.stridespark.com

**Closed** 2018-02-26 08:08 UTC
Labels: More information requested

**Comment by codingbeans** [comment] 2019-07-07 03:01
This line still doesn't work even now...

`knex('table').where(A).update(B);`

and need to be replaced with

`knex('table').where(A).update(B).then();`

Very frustrating misbehavior...

**Comment by ricardograca** [comment] 2019-07-07 12:02
This is the intended behavior, as it allows chaining actions together without having them execute unexpectedly. For example, you can do this:

```
const update = knex('table').update(B).where(A)

if (something) update.whereIn(C)

update.then(results => {
  // your results are now limited bu .where() and .whereIn() if "something" is "true".
})
```

Also, Knex query methods return Promises, so you would always have to attach a `.then()` or `.catch()` to see if the query actually succeeded or not.

I agree that the documentation could have the complete call, including `.then()` since currently it looks like the queries exemplified would just be executed without it.

**Comment by elhigu** [comment] 2019-07-08 11:45
Yep, documentation page doesn't execute queries, but only prints out SQL that is generated by the query.

Anyhow nowadays preferred method to trigger query builder is to do 

```
const res = await knex('table').where(A).update(B);
```

**Comment by codingbeans** [comment] 2019-07-08 12:07
I see. Thanks for the detailed explanation! I've had the misunderstanding for quite a while.
