### ISSUE TITLE
Reconnect to mysql on disconnect or error

### ISSUE THREAD

**Issue by ammar08429** [tgriesser/knex#2323] opened 2017-11-13 13:06 UTC
If the MySQL server goes down, or it down scales or something
the previous connection of the application server with MySQL get corrupted and the server starts throwing this issue
`PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR Cannot enqueue Query after fatal error`
We face multiple errors in such scenarios, In the docs, I couldn't find anything regarding reconnecting the only solution that we have is restarting the service?

I would like to know that, do you have anything
like `reconnectTries`, `reconnectInterval`
like other libraries like [this mongo library](http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html) has

**Comment by elhigu** [comment] 2017-11-13 13:40
Which knex version are you using? Pool reconnecting after connection failure was improved in 0.14.

**Comment by ammar08429** [comment] 2017-11-14 08:12
Ok ok that's great I will give it a try, we were using the last 0.12.9 version

**Comment by treble-snake** [comment] 2017-11-14 09:14
@elhigu Hi! 
I started getting those errors, like out of the blue, since I've updated knex from 0.13.0 to 0.14.0.
I'm using `mysql: 2.15.0`.
Is there a chance that something relevant to mysql reconnection was broken in 0.14.0 release?

**Comment by wubzz** [comment] 2017-11-14 09:53
@treble-snake Taking a shot out of the blue here, but given that this seems to be Pool issues, could you try to append `evictionRunIntervalMillis: 1000` to your pool config and see if that helps?

The upgrade of pool library could have more unexpected consequences than discovered in #2322.

**Comment by treble-snake** [comment] 2017-11-14 10:48
@wubzz Thanks, I'll give it a try!
Though, I don't have any reproduce strategy other than "wait for it" :)
So I'm gonna wait for it first to confirm it's not just some random thing and then try pool settings.

**Comment by ammar08429** [comment] 2017-11-14 12:05
@elhigu 
I updated the version of knex, When we downscale or restart MySQL server we still get this error
```Cannot enqueue Query after fatal error.
 at Protocol._validateEnqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:201:16)\\n    at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:139:13)\\n    at Connection.query (/usr/src/app/node_modules/mysql/lib/Connection.js:208:25)\\n    at /usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:156:18\\n    at Promise._execute (/usr/src/app/node_modules/bluebird/js/release/debuggability.js:303:9)\\n    at Promise._resolveFromExecutor (/usr/src/app/node_modules/bluebird/js/release/promise.js:483:18)\\n    at new Promise (/usr/src/app/node_modules/bluebird/js/release/promise.js:79:10)\\n    at Client_MySQL._query (/usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:150:12)\\n    at Client_MySQL.query (/usr/src/app/node_modules/knex/lib/client.js:211:17)\\n    at Runner.<anonymous> (/usr/src/app/node_modules/knex/lib/runner.js:149:36)\\n    at Runner.tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)\\n    at Runner.query (/usr/src/app/node_modules/bluebird/js/release/method.js:15:34)\\n    at /usr/src/app/node_modules/knex/lib/runner.js:61:21\\n    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)\\n    at /usr/src/app/node_modules/bluebird/js/release/using.js:185:26\\n    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)\",\"code\":\"PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR```

**Comment by treble-snake** [comment] 2017-11-14 12:24
Btw, is it possible to retrieve connection object in order to inject log statement like [this one](https://github.com/mysqljs/mysql/issues/1478#issuecomment-233737511)?

**Comment by ammar08429** [comment] 2017-11-14 12:40
@elhigu 
what exactly is `evictionRunIntervalMillis` this for?

**Comment by oliviertassinari** [comment] 2017-11-15 09:47
We have noticed the same issue upgrading from knex v0.13.0 to v0.14.0.

**Comment by oliviertassinari** [comment] 2017-11-15 09:49
It seems to be the same for @NemoAlex https://github.com/tgriesser/knex/issues/452#issuecomment-343397051.

**Comment by treble-snake** [comment] 2017-11-15 12:40
I've just performed some tests and can confirm it's reproducible.

- Install knex 0.14.0
- Use pretty much default config (see below)
- Run the app
- Restart MySQL server
- Got `PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR` on a next DB call

Same steps work OK (reconnect with no error) with knex **0.13.0**.

@wubzz I've tried adding `evictionRunIntervalMillis: 1000` to a pool's config, but unfortunately it doesn't help.

But I guess some other cases than MySQL server restarting can lead to that error, 'cause I most certainly haven't restarted remote MySQL server, but got the same error there.

Knex config:
```
  "database": {
    "client": "mysql",
    "connection": {
      "host": "127.0.0.1",
      "user": "<...>",
      "password": "<...>",
      "database": "<...>",
      "charset": "utf8"
    },
    "pool": {
      "min": 2,
      "max": 10
      [, "evictionRunIntervalMillis": 1000] // doesn't help
    },
    "migrations": {
      "tableName": "<...>",
      "directory": "<...>/migrations"
    },
    "seeds": {
      "directory": "<...>/seeds"
    }
  }
```

**Comment by treble-snake** [comment] 2017-11-15 12:43
@ammar08429 I'd suggest you use **0.13.0** version for now, it seems more stable

**Comment by elhigu** [comment] 2017-11-15 12:58
@treble-snake I'm fixing some new pool problems to 0.14.1

**Comment by ammar08429** [comment] 2017-11-15 14:04
@elhigu Please Re-open this issue
I tried what @treble-snake did.
And i get error in 0.14.0, but in 0.13.0 it reconnects properly

**Comment by elhigu** [comment] 2017-11-16 17:54
@ammar08429  I though this was a duplicate of https://github.com/tgriesser/knex/issues/2321 but looks like error message is a bit different. Better to reopen to make sure that this get fixed too.

**Comment by ckanthony** [comment] 2017-11-17 04:48
+1 on the same situation in 0.14.0

**Comment by elhigu** [comment] 2017-11-19 16:44
Please test this with 0.14.1 and lets reopen if there are still problems.

**Closed by elhigu** 2017-11-19 16:44 UTC

**Comment by treble-snake** [comment] 2017-11-20 13:54
Simple scenario with server's restarting seems to be fixed.

**Comment by ammar08429** [comment] 2017-11-21 21:21
Simple restart is working right now
