### ISSUE TITLE
Slow performance when selecting large strings

### ISSUE THREAD

**Issue by appedemic** [tgriesser/knex#1819] opened 2016-12-07 10:30 UTC
Using Postgres 9.6, I have a table "datasets" with about 20 fields, each field is a long text (it contains JSON but the field types are TEXT because I don't need to index or query within the data). I'm building an API with Hapi that needs to return a dataset for a user but I'm running into performance issues.

To drill down on the issue, consider the query to select all datasets. The table contains only one record. The record has a total size of about 20MB though.

```javascript
console.time('knex');
knex.select('*').from('datasets').then((result) => { console.timeEnd('knex') });
```
Results in: "knex: 17766.126ms"

When I do the same query using the pg driver directly its much, much faster:

```javascript
console.time('pg');
client.query('SELECT * FROM datasets', (err,result) => { console.timeEnd('pg') });
```
Results in: "pg: 516.070ms"

I've tried with both pg-native enabled and disabled, but knex is just a lot slower. What can be causing this and what can I do to work around this slow performance? Does it relate to the long strings being JSON data? Does knex do any postprocessing on TEXT values or is the result data copied around?

**Comment by appedemic** [comment] 2016-12-07 10:52
Sorry, it does seem to be related to pg-native. When I run the pg version of the query without pg-native I get the same slow performance. When I run the pg version using pg-native it's fast. I thought knex uses pg-native when available?

**Comment by chanon** [comment] 2017-02-12 15:56
I've looked through the code and Knex doesn't seem to use pg-native anymore. It is somewhat disappointing that it isn't.

**Comment by jabbatico** [comment] 2017-02-27 14:51
we just tested upgrading to .12.x and we are seeing scale and performance issues we do not see in .11.x with PG. could this be related to pg-native? do you now what version pg-native was depricated?

**Comment by mramato** [comment] 2017-08-31 13:48
I fixed a major read performance issue with `pg` a few months ago.  You can read all about it in #2052  This sounds like exactly the same problem so I assume this issue can be closed.

**Comment by elhigu** [comment] 2017-08-31 15:21
I wasn't able to reproduce this problem... @appedemic could you add the data initialization also. Or rerun your benchmarks with pg@7 and knex@0.13

**Comment by wubzz** [comment] 2018-02-12 13:45
Closing due to comments above. Reopen if issue persists.

**Closed by wubzz** 2018-02-12 13:45 UTC
