### ISSUE TITLE
How do I format connection string charset?

### ISSUE THREAD

**Issue by kevbaker** [tgriesser/knex#1593] opened 2016-07-26 04:39 UTC
I would like to use a connection string instead of the connection object for connecting to a database and be able to specify the `charset`.

Example:

`connection: 'mysql://root:secret@127.0.0.1:3306/test-db'` 

NOT

```
connection: {
            host     : '127.0.0.1',
            user     : 'root',
            password : 'secret',
            database : 'test-db',
            charset  : 'utf8'
        }
```

I have the connection string working, but I am not sure how to specify the `charset`.

**Comment by chrisbroome** [comment] 2016-07-26 14:10
You should be able to pass params as a querystring. From the [node-mysql](https://github.com/mysqljs/mysql) docs:

> In addition to passing these options as an object, you can also use a url string. For example:
>
> ```JavaScript
 var connection = mysql.createConnection('mysql://user:pass@host/db?debug=true&charset=BIG5_CHINESE_CI&timezone=-0700');
```

**Comment by glenjamin** [comment] 2017-06-02 13:23
Looks like a dupe of #1528

**Closed** 2017-06-07 18:13 UTC
