### ISSUE TITLE
Query falls on timeout if returns a large number of "count" operator 

### ISSUE THREAD

**Issue by Alextunchii** [tgriesser/knex#3015] opened 2019-01-28 11:01 UTC
Knex version: 0.16.3
Database + version: mssql
OS: IOS
client: 'mssql', version: 4.1.0

Hi! I struggle, as for me, with a simple thing, but maybe I'm doing something wrong just in case or it's really knex's disability.

All queries I use for tests are with operator `count(distinct something)`. I always return just a number, ex. 500
But if the result is more than 500K, 1M and so on I can't wait for the query to finish and falling with timeout(I laready set 150 sec)

I don't understand, it proceeds the same amount of data in the table but if the number of matches is low - it's ok, if high - it fails.

Why? 

If something is unclear or you need additional info, feel free to write everything out what I need to add.

Thanks!

**The query example:** 
```
getBase(recordsType, fileTypes) {
        return knex('dbo.pp as p')
            .select()
            .countDistinct(recordsType)
            .leftJoin('dbo.oo as od', 'od.u', 'p.u')
            .leftJoin('dbo.pid as x', 'x.u', 'p.u')
            .leftJoin('dbo.Organization as o', 'o.u', 'p.u')
            .leftJoin('dbo.address as a', 'a.u', 'o.u')
            .leftJoin('dbo.k12 as pc', 'p.personId', 'pc.PersonId')
            .leftJoin('dbo.supll as dosd', function () {
                this.on('dosd.org', '=', 'o.org')
                    .on('dosd.sup', knex.raw('?', [7]))
                    .on('dosd.des', knex.raw('?', ['Total Minority']))
            })
            .leftJoin('dbo.sup as cosd', function () {
                this.on('cosd.OrganizationUniqueID', '=', 'o.OrganizationUniqueID')
                    .on('cosd.SupplementalDataTypeId', knex.raw('?', [11]))
                    .on('cosd.Descriptor', knex.raw('?', ['Total Minority']))
            })
            .whereIn('o.fileType', fileTypes)
            .andWhere('pc.JobID', 'in',
                knex('dbo.bal as a')
                    .select()
                    .distinct('b.jobId')
                    .innerJoin('valJob as b', function () {
                        this.on('a.code', '=', 'b.code')
                            .andOn('a.ncode', '=', 'b.ncode')
                    })
                    .whereIn('b.status', [0, 1, 3])
                    .andWhere('b.priority', '!=', '8')
            )
            .andWhere('x.CWB_OrganizationClassID', '!=', 10)
```

And if in **fileTypes** only 1 argument - it will pass, but if 4-6 - fails

**Comment by elhigu** [comment] 2019-01-28 12:50
Please add complete and minimal reproduction code if you think this is a knex bug check CONTRIBUTING.md . Otherwise if this is just a knex usage question please use gitter or stackoverflow for that (as it is instructed in the issue template). 

Sounds like you have just written too slow queries and timeouts are happening because of that. Also you do not provide enough information how things fail if you add more fileTypes... Closing as cannot reproduce / not a bug for now.

Lets reopen if you can provide some  definite and simplified case showing that this is knex bug.

**Closed by elhigu** 2019-01-28 12:50 UTC

**Comment by Alextunchii** [comment] 2019-01-28 13:45
I think it's related to knex, because using just client: 'mssql' and sending just a string of this built(in knex) query I have a returned number. 
Using naked mssql and sending a query(just string) 3 times larger takes: 1m 25sec
Using knex and sending this query: 

```
const knex = require('knex')({
    client: 'mssql',
    connection: config,
    acquireConnectionTimeout: 150000,
    debug: false
});

module.exports = class Queries {

getBase(recordsType, fileTypes) {
        return knex('dbo.pp as p')
            .select()
            .countDistinct(recordsType) // p.PersonId
            .leftJoin('dbo.oo as od', 'od.u', 'p.u')
            .leftJoin('dbo.pid as x', 'x.u', 'p.u')
            .leftJoin('dbo.Organization as o', 'o.u', 'p.u')
            .leftJoin('dbo.address as a', 'a.u', 'o.u')
            .leftJoin('dbo.k12 as pc', 'p.personId', 'pc.PersonId')
            .leftJoin('dbo.supll as dosd', function () {
                this.on('dosd.org', '=', 'o.org')
                    .on('dosd.sup', knex.raw('?', [7]))
                    .on('dosd.des', knex.raw('?', ['Total Minority']))
            })
            .leftJoin('dbo.sup as cosd', function () {
                this.on('cosd.OrganizationUniqueID', '=', 'o.OrganizationUniqueID')
                    .on('cosd.SupplementalDataTypeId', knex.raw('?', [11]))
                    .on('cosd.Descriptor', knex.raw('?', ['Total Minority']))
            })
            .whereIn('o.fileType', fileTypes) // !!! For instance: where o.fileType in ('01', '02')
            .andWhere('pc.JobID', 'in',
                knex('dbo.bal as a')
                    .select()
                    .distinct('b.jobId')
                    .innerJoin('valJob as b', function () {
                        this.on('a.code', '=', 'b.code')
                            .andOn('a.ncode', '=', 'b.ncode')
                    })
                    .whereIn('b.status', [0, 1, 3])
                    .andWhere('b.priority', '!=', '8')
            )
            .andWhere('x.CWB_OrganizationClassID', '!=', 10)
            .andWhere('od.SchoolTypeDescription', 'is not', null);
}

```
:Another File(where I import this class with querybuilder for tests)
 
```
const dbQuery = require('../../../database/queriesForApi');
const queries = new dbQuery;

it('DRI for Special ED with Buyers', async function () {
csdbCount = await queries.getBase('p.personId', ['10'])
            .andWhere('p.BuyerFlag', '=', 1);
});
```

Let me to change the meaning, let's forget about o.fileType.

I have this query above:
1) If I run this query, it fails on: **requestTimeout**: 70000 that is used in config file which knex uses to connect,
* there are must be returned a number: ±3000000

2) If I run this query, using mssql directly where is sent the equivalent query string:
```
SELECT COUNT(distinct p.personId) FROM dbo.Person as p
left join dbo.oddao as od
 on od.oo = p.oo
left join dbo.PIDXrefLinks as x
 on x.oo = p.oo
left join dbo.ORGA as o
 on o.ooo = p.ooo
left join dbo.Pers as pc
    on p.personId = pc.PersonId
where pc.JobID in (
    select distinct b.jobId from dbo.OMS as a
    inner join valJob as b
         on a.historicAlphaCode = b.historicAlphaCode
         and a.historicNumericCode = b.historicNumericCode
    where b.status in (0, 1, 3)
    and b.priority != 8
)
and x.CWB_OrganizationClassID != 10
and o.FileType IN ('07', '02', '04')
and od.SchoolTypeDescription is not null
and p.BuyerFlag = 1;
```
it takes 30 sec and gets executed. 


So why with knex it then takes so much time to request? 
The query is built in accordance with specification, please, if your could tell then what wrong with "QueryBuilder" query that it doesn keep up?

**Comment by wubzz** [comment] 2019-01-28 15:25
> using mssql directly

Do you mean via the SQL Server Management Studio? If so, you could try to run the same query using only the driver module _(without knex)_ to see if there's a difference.

I would guess more on a driver issue than knex issue, since knex just generates the sql string and passes it to the driver. A `count` query doesn't return much data either, so it can't be a parsing issue.
