### ISSUE TITLE
Raw Binding String parameter always empty

### ISSUE THREAD

**Issue by purell** [tgriesser/knex#1307] opened 2016-03-24 12:09 UTC
Hi,

Maybe I'm doing something wrong but I'm unable to get a raw query properly work with parameter binding.

```knex
.table('Product')
.whereRaw("ProductName LIKE(:ProductName_1)", {ProductName_1 : '%foo%'})
.select('ID', 'ProductName')
.then(function (rows) {
    // rows is always an empty array
});
```

In the debug console :
```
{ method: 'select',
  options: {},
  bindings: [],
  sql: 'select "ID", "ProductName" from "Product" where ProductName LIKE (:Prod
uctName_1)' }
```

As you can see, the bindings is EMPTY. Why ?

I've also tried with :

```
.where( knex.raw("ProductName LIKE(:ProductName_1)", {ProductName_1 : '%foo%'}) )
```
But same problem.

If I use SQL equal operator it seem to work, but as soon as I use one of the following operators "LIKE, IN, NOT IN", knex discard my binding.

My configuration :
```
knex 0.10.0
sqlite.
Node .0.12.0
```

**Comment by purell** [comment] 2016-03-24 12:35
On the other hand if I use the "question mark" parameter binding instead of "named" binding it works properly. So could it be a bug ?

**Comment by wubzz** [comment] 2016-03-24 12:35
@purell Hi, perhaps this is related to #1251 which is currently merged but not yet published?

The sum of the issue is that `(:ProductName_1)` would not work while `( :ProductName_1)` would work. The pull request fixes this by changing the regular expression so that a space is not required.

Testing this locally I'm almost certain that's the issue. Can you verify?

**Comment by purell** [comment] 2016-03-24 12:53
Yes, it seem to work. I already tried what was propose in the #1251 but I did put the space in the wrong place.

I was trying :
``` 
.whereRaw("ProductName LIKE (:ProductName_1)", {ProductName_1 : '%foo%'})
``` 

Instead of :
```
.whereRaw("ProductName LIKE( :ProductName_1)", {ProductName_1 : '%foo%'}) 
```

Do you know WHEN the fix will be published (npm) ? I really need this to be working now :(

By the way, thank you for your help. It is greatly appreciated.

**Comment by wubzz** [comment] 2016-03-24 14:04
We have a few pull requests to get through before publishing, but it will hopefully be soon.

**Closed** 2016-03-24 14:04 UTC
Labels: question
