### ISSUE TITLE
ER_ACCESS_DENIED_ERROR after several hours of idle or minimal usage

### ISSUE THREAD

**Issue by dearsaturn** [tgriesser/knex#2939] opened 2018-12-03 20:04 UTC
# Environment
Knex version: 0.15.2
Database + version: MySQL 5.7.22 (on RDS)
OS: 64bit Amazon Linux/4.5.3

knex configuration:
```js
{
    host: '...',
    port: 3306,
    user: '...',
    database: '...',
    charset: 'utf8mb4',
    dateStrings: true,
    pool: {
        min: 0,
        max: 25,
        acquireConnectionTimeout: 60000
    }
}
```

# Bug (or our own misuse)?
After an indeterminate (but usually, 11 hours or more) period of little or no usage, we start to see connections refused, with each call throwing `ER_ACCESS_DENIED_ERROR: Access denied for '...'@'an-ip-address'`. It isn't after the _first_ request comes through, but typically an hour or two after activity starts picking up.

Some finer details about how we use `knex`:

- We use Koa, and connections are attached to the context in a middleware, using `getConnection(read or write db name)` (declaration below).
- `mysqlConfiguration` is a static function that returns the knex config above.
- We have a write db and read replica that we have separate configurations for.
- Restarting our node server fixes the issue.

```js
const connections = {};

export function getConnection(connectionName) {
    if (!connections[connectionName]) {
        const connectionConfig = Environment.mysqlConfiguration[connectionName];

        const connection: knex = knex({
            ...connectionConfig,
            asyncStackTraces: true
        });

        connections[connectionName] = connection;
    }

    return connections[connectionName];
}
```

My guess is that whoever wrote this initially wanted to hold onto the connection instance from the first module resolution and have that persist for the lifetime of the application. We were using a very old version of Knex that didn't have these issues until I recently upgraded us from `0.9` to `0.15.2`. My other guess is that RDS has killed some stale connections in the first instance's pool, and they're not getting pruned.

Should we _not_ be doing this, and instead call `knex(connectionConfig)` for a fresh `knex` instance on each request?

**Comment by elhigu** [comment] 2018-12-03 20:48
You should use always the same knex instance which is initialized just once when node process is started (or multiple knex instances if you need to connect to multiple databases).

The configuration you pasted in the original post does not seem correct. It doesn't describe which database client you are using and pool setup should be done in upper level than connection details. However I don't think that it is the problem in your case... except for that pool setup which might mess up something.

Try to print out some debug information about how many connections there are in pool etc. Check out tarn.js documentation, how to get data about pool internals. Pool can be found from knex instance from `knex.client.pool`.

**Comment by elhigu** [comment] 2018-12-03 20:48
Also closing currently as cannot be reproduced :(

**Closed by elhigu** 2018-12-03 20:48 UTC

**Comment by elhigu** [comment] 2018-12-03 22:19
No worries, let me know if you are able to see that there indeed is situations, where RDS closes connections in a way that knex doesn't notice. Also would be good to make sure that you have latest version of mysql driver installed.

**Comment by dearsaturn** [comment] 2018-12-03 22:33
Sure thing. I may honestly opt for instance restarting until I have the bandwidth to get to the bottom of this. If it is of any use, before it starts happening, we see:

`Connection Error: Error: Connection lost: The server closed the connection.`
I see that warning [comes from the validate function](https://github.com/tgriesser/knex/blob/46dbe917d7cbc1748aba2ee9050dafea0b840fc0/src/client.js#L279) in the Tarn config. Since it's happening in `validate`, that would mean that the `ER_ACCESS_DENIED_ERROR` is occurring after acquiring new connections, not because of stale ones, right?

**Comment by elhigu** [comment] 2018-12-03 23:21
> Since it's happening in validate, that would mean that the ER_ACCESS_DENIED_ERROR is occurring after acquiring new connections, not because of stale ones, right?

Yes, sounds like old connections are disposed just fine, but new ones cannot be created anymore...  but that error is coming from database server so I have no idea why it could stop accepting old credentials or maybe that error code can mean something else too.

You can also monitor connection count etc. from RDS while figuring it out. Other old trick has been to add debug printouts to nearby the places where errors are thrown directly to a code inside node_modules, for example nearby this /var/app/current/node_modules/knex/lib/util/make-knex.js:40:19.

**Comment by dearsaturn** [comment] 2018-12-08 03:08
@elhigu I wanted to mention that I see this in the mysql logs right before this happens. Additionally, it's not all connections in the pool that fail, just some.

```
2018-12-08T01:32:19.402149Z 2360156 [Note] Access denied for user 'socialnative'@'REDACTED_2' (using password: YES)
2018-12-08T01:32:19.404563Z 2360157 [Note] Access denied for user 'socialnative'@'REDACTED_2' (using password: YES)
2018-12-08T01:32:34.824238Z 2358993 [Note] Aborted connection 2358993 to db: 'DB_NAME_REDACTED' user: 'socialnative' host: 'REDACTED_2' (Got an error reading communication packets)
2018-12-08T01:32:34.824380Z 2360027 [Note] Aborted connection 2360027 to db: 'DB_NAME_REDACTED' user: 'socialnative' host: 'REDACTED_2' (Got an error reading communication packets)
2018-12-08T01:37:41.369732Z 2360694 [Warning] IP address 'REDACTED_1' could not be resolved: Name or service not known
```

It looks like an issue where DNS resolution fails (which isn't extraordinary in my opinion) but the pool isn't discarding the connection mysql aborted. It continues to try to run queries on it and gets back `ER_ACCESS_DENIED_ERROR` and that bubbles up to our application. I also tweaked our max connections to 15, 25, and 50 and still saw this.

**I also ought to remark that I saw this after a hefty knex upgrade**. We began seeing this issue after going from `0.9` to `0.15.2`, which makes me think it's a regression -- it's just too coincidental to me not to be.

Finally, I'm sorry if I'm being a pest here. :/

**Comment by elhigu** [comment] 2018-12-09 23:36
Does all errors go away if you replace REDACTED_1 / REDACTED_2 with real IP instead of DNS name or if you add IP:s for those hosts to be resolved locally by application server i.e. in `/etc/hosts`? 

That sounds like a bug somewhere if connections are not discarded from pool in case of DNS error... can that be reproduced by just trying to connect to some invalid DNS name? If that can be reproduced, it will be easy to debug where the problem lies.

**Comment by dearsaturn** [comment] 2018-12-10 00:06
They _are_ real IPs, I think MySQL does the reverse lookup regardless if `skip_name_resolve` is false.

So far, I've been getting around this by terminating the process and restarting it, but I think it can be reproduced by throttling the mysql host's dns server.

I can't really edit /etc/hosts because I'm spinning up new hosts pretty often.

I think I can also work around by setting `skip_name_resolve` to true. I'm fine without having that check.

**Comment by elhigu** [comment] 2018-12-10 06:32
> I can't really edit /etc/hosts because I'm spinning up new hosts pretty often.

I meant to just try it out if it that actually fixes the problem, it could be caused by that DNS server problem... but if it is because of reverse DNS resolution I'm not sure if /etc/hosts is even used for that.

Sounds pretty far fetched that reverse lookup would be causing the problem, mysql should do it only once per IP address https://dev.mysql.com/doc/refman/8.0/en/host-cache.html 

> ... I think it can be reproduced by throttling the mysql host's dns server

Anyways let me know if you are able to reproduce it. Would be interesting to see if mysql driver doesn't notify about broken connection  in that scenario and `knex` pooling really breaks.

**Comment by dearsaturn** [comment] 2018-12-10 06:46
Thanks for the guidance, I really appreciate it. I'll try to reproduce this and will report back here. Something absolutely strange I'm seeing is that our host_cache table is empty?? That's probably why it's doing reverse lookups up all the time. Will be a fun little adventure figuring that one out!
