### ISSUE TITLE
SQLite - Querying with where

### ISSUE THREAD

**Issue by abhishekbhardwaj** [tgriesser/knex#1850] opened 2017-01-04 09:46 UTC
So I was just testing waters with Knex and SQLite3. I am trying to query with a simple where clause and SQLite returns an empty array while I get the correct response from MySQL.

I have a simple `users` table with the columns `id, name, email, password, timestamps`. I had a simple query:

`knex.from('users').select().where('id', '=', 2)`

This returned an empty array. I ran the exact same migration and seeds on a MySQL database and when queried with Knex, got the correct data out.

**Comment by elhigu** [comment] 2017-01-04 10:05
Generated query seems to be correct:

```js
knex = require('knex')({client: 'sqlite3' });
knex.from('users').select().where('id', '=', 2).toSQL();

{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 2 ],
  __knexQueryUid: '085abaa2-f39a-4fac-9d0a-24b035219330',
  sql: 'select * from "users" where "id" = ?' }
```

Try to open your sqlite database with sqlite commandline shell and check if it really has the data you think it has. If you are using inmemory database and e.g. recreate connection all the data will be lost in the process.

I'm closing this since it doesn't seem to be knex related issue. If you have more info about the case or steps to reproduce please keep commenting here and we'll help if possible.

**Closed by elhigu** 2017-01-04 10:05 UTC

**Comment by abhishekbhardwaj** [comment] 2017-01-04 10:35
> If you are using inmemory database and e.g. recreate connection all the data will be lost in the process.

It is an in-memory database being used for running mocha tests. I am inserting a record first and then in the returned promise I query again for the single record that was created. 

I guess for the second query, it might be creating a new connection. But I just tried removing the `where` clause for the second query and it returned 3 records (2 from seed and 1 inserted from the test) so I don't think it's loosing that data.

**Comment by elhigu** [comment] 2017-01-04 11:29
Please add single file test file here, that I can run to reproduce the problem, I'm sure this is an user error.

**Comment by abhishekbhardwaj** [comment] 2017-01-04 12:25
Sure, will do so in the morning.

**Comment by abhishekbhardwaj** [comment] 2017-01-04 12:41
I tried recreating the problem with a single test file but it works perfectly there.

```js
var Knex = require('knex');

var knex = Knex({
    client: 'sqlite3',
    connection: {
        filename: ':memory:',
    },
    useNullAsDefault: false
});

// Setup
knex.schema.createTable('users', function (table) {
    table.increments();
    table.string('name');
}).then(function() {

    knex('users').insert({ name: 'Test 1' }).then(function(id) {
        knex('users').first().where('id', '=', 1).then(function(data) {
            console.log(data);
        });
    });

});
```

Might be something going on with my application code but I'm not really doing anything SQLite specific in that code (exact replica of the code above). It works fine with MySQL so it should work with SQLite too. I'll take a look again!

Thanks for your help! 👍

**Comment by elhigu** [comment] 2017-01-04 13:05
Try to use named sqlite db instead of inmemory one. That way you can verify if the problem indeed is that you accidentally create new connection to empty inmemory database somewhere in the code.

**Comment by abhishekbhardwaj** [comment] 2017-01-05 07:16
Tried multiple things but in the end, it came down to the value available in the promise after insert is processed.

```js
knex('users').insert({ name: 'Test 1' }).then(function(__ID__) {
    knex('users').first().where('id', '=', __ID__).then(function(data) {
        console.log(data);
    });
});
```

`__ID__` is an array containing the id (or id's) of the row(s) inserted, and I didn't realize this stupidity initially but I was feeding an array to the second query when it should have been just a single integer. With an array, it works with MySQL (`select * from users where id = [1]`) but not with SQLite apparantly.
