### ISSUE TITLE
you cant make Object.prototype will cause knexjs to fail without errors

### ISSUE THREAD

**Issue by dleeq8** [tgriesser/knex#1139] opened 2016-01-15 00:54 UTC
```
Object.prototype.anyfun=function(){}
```

```
var knex = require('knex')({
  dialect: 'sqlite3',
  connection: {
    filename: './NewFileName.db'
  }
});

knex.schema.createTable( .. ) // will never fire
.catch( .. )  // never fire
.done||finally( .. )  // never fire 
```

Remove Object prototype all this problems go

so is this knex problem or promise? not sure yet

i waste two days fixing the problem then finally when i remove Object prototype every thing works fine

i open this here so any one have unknown problem(no debug/errors) with knexjs will see this

**Comment by chrisbroome** [comment] 2016-01-15 15:12
Can you run your app with `DEBUG=knex:* node app.js` (or whatever your app file is) and look at the output of that to see what's going on?

Also, as a general rule, it's considered extremely bad practice to modify the prototype of built-in objects, specifically because it affects *every* object in the system of that type. Many libraries assume (rightfully so) that the environment is untainted by modified prototypes - to do otherwise would make the library much less useful and/or only useful in the prototype-modified context.

I strongly encourage you to rethink your approach. At the very least, instead of modifying prototypes, move those functions to a utility module and use that instead.

Instead of 
``` JavaScript
Object.prototype.anyfun = function() {
  // presumably using 'this' pointer in here somewhere to refer the object
}
```

do this:

``` JavaScript
// utility-file.js

module.exports = {
  anyfun: function(obj) {
    // you now have an explicit 'obj' instead of relying on this
  }
};
```

See also http://stackoverflow.com/a/14034242/436977

**Comment by wubzz** [comment] 2018-07-17 06:29
Closing, cannot reproduce in latest knex.

**Closed by wubzz** 2018-07-17 06:29 UTC
