### ISSUE TITLE
Inserting empty array inserts a record with default values.

### ISSUE THREAD

**Issue by rhys-vdw** [tgriesser/knex#589] opened 2014-12-03 01:23 UTC
``` javascript
knex('test').insert({}).toString()
"insert into "test" default values"
knex('test').insert([{}]).toString()
"insert into "test" default values"
```

These two use cases make sense, but I think that the logic has incorrectly been extended to the following:

``` javascript
knex('test').insert([]).toString()
"insert into "test" default values"
```

Can I propose that inserting an empty array should either be a no-op or throw an error?

I can't think of a case where an empty array would be intentionally used to to insert a single record. A no-op would be ideal, this way it saves the client checking for empty arrays on every insert.

At the moment I use this (shitty) workaround:

``` coffee
safeInsert = (k, table, rows, returning) ->
  if _.isEmpty rows then [] else k(table).insert rows, returning or 'id'
```

**Comment by rhys-vdw** [comment] 2015-01-09 00:52
Hey guys, I could have a crack at fixing this. I'm not familiar with the codebase yet, but I'm interested in contributing to the project and would like this issue resolved.

I'd rather not invest the time if this is not desired functionality, so I'm asking here before attempting a pull request.

**Comment by bendrucker** [comment] 2015-01-09 01:27
Yes, please send a PR with updates to the relevant tests. I'll make the final call here and say that passing any empty array should be a noop.

**Comment by rhys-vdw** [comment] 2015-01-09 01:29
Great. I'm quite busy, but I'll try to get around to it in the next couple
of weeks.

**Comment by tgriesser** [comment] 2015-04-01 23:53
So do we think should this be a no-op or an error? Just want to adjust the tests in the next branch

**Comment by bendrucker** [comment] 2015-04-02 00:29
A noop

**Comment by drvanhalen** [comment] 2015-04-16 11:56
> Just want to adjust the tests in the next branch

@tgriesser sounds like this fix is underway already? Happy to help out if needed.

**Comment by tgriesser** [comment] 2015-04-21 18:56
Yeah, so it turns out there's a bunch of cases in the tests that I'm looking to break because they might not make sense, or they're not applicable across all drivers.

Just want to sanity check this - an array passed to insert will have any non object values filtered out:

```js
// current: inserts one row, 
// 0.8: noop
knex.insert([null]) 

// current: inserts two rows if possible, 
// 0.8: noop
knex.insert([null, null]) 

// current: inserts one row
// 0.8: noop
knex.insert() 

// current: insert one row
// 0.8: same behavior
knex.insert({})

// current: - insert one row
// 0.8: same behavior
knex.insert([{}]) 

// current: insert two rows in mysql, fails in PG, Oracle, SQLite3
// 0.8: should this work for mysql and throw for others?
knex.insert([{}, {}]) 
```

**Comment by myndzi** [comment] 2015-04-21 20:12
I find inserting "{}" to be a much more intuitive way to say "insert a row with all defaults" than "null". Inserting a value without saying what column it goes to has no meaning anyway, so filtering them out seems good by me, but `insert([{}])` and `insert([{}, {}])` failing is definitely not intuitive. 

I'm not exactly sure what this translates to in SQL: INSERT INTO table () VALUES () or something? What would be valid? Could you then do VALUES (),() ?

Seems and edge case all around, but it'd be nice if it was consistent.

**Comment by tgriesser** [comment] 2015-04-21 21:24
>  but insert([{}]) and insert([{}, {}]) failing is definitely not intuitive.

The thing is they the `(), ()` is valid in mysql but not in others where inserting default is
`insert into table default values` and you can't do the default values thing twice... so either we run multiple queries or we fail.

**Comment by myndzi** [comment] 2015-04-21 21:29
Gotcha. To be honest, it's almost worth running multiple queries or not supporting the syntax at all, to me. What would make the most sense is .insertDefault() or something and just require sane arguments to .insert()

**Comment by rhys-vdw** [comment] 2015-04-21 22:25
> you can't do the default values thing twice... so either we run multiple queries or we fail.

Are there other times when knex will fire multiple queries for a single call? I'd expect insert to be atomic, and would usually want to use a transaction for multiple inserts.

Failing in the case of trying to insert multiple empty records (`{}, {}`) in PostgreSQL (and others) seems appropriate, since it's actually a limit of the system, and equivalent to writing bad SQL.

I think your proposed behaviour is appropriate, @tgriesser.

**Comment by PierBover** [comment] 2017-06-19 01:22
If anyone stumbles upon this, the only way that works is by inserting one element at a time with:
```
.insert({});
.insert({});
```

IMO `.insert([{},{}]);` makes sense (although it doesn't work);

**Comment by tahv0** [comment] 2017-07-14 08:17
I faced this problem too. It would be nice to be able to call insert([{}, {}, ...])

**Comment by elhigu** [comment] 2017-07-14 12:08
@tahv0 @PierBover As mentioned above, that is not possible in most of the DBs without making multiple queries. 

Making multiple queries from one builder is just not supported by knex (migration schema APIs are exception to this). 

It is pretty fundamental principle in this lib that you get just one query and its result. Allowing multiple queries would open door to implement all kind of hacky compatibility work arounds and I don't think that is in the scope that `knex` should do (just making basic parts work well has proven to be hard and time consuming enough).

So throwing an error would be good solution here for unsupported dialects... that array is already looped through to find out missin keys etc. so it wouldn't affect performance either.

Or is someone comes up with single query that makes this possible would be even better. Something like this could work: 

```
.insert([{id: knex.raw('DEFAULT')}, {}, {}, {}])
```

but the problem is that we don't know even the `id` column name for sure.

**Comment by wubzz** [comment] 2018-02-16 07:34
Closing this as the original issue has already been adjusted by Tim into a `noop` long ago. 

Unfortunately the `noop` in this case is an empty SQL string sent to db. Imo a real `noop` would imply no database connection at all, but that can be a potential improvement.

**Closed by wubzz** 2018-02-16 07:34 UTC
Labels: feature request
