### ISSUE TITLE
Memory leak with knex 0.12.6

### ISSUE THREAD

**Issue by skumar568** [tgriesser/knex#2106] opened 2017-06-05 13:24 UTC
Hi,

We were using knex 0.11.6 so far and all was working well. But, couple of months back, we upgraded knex to 0.12.6 with Node 6.9.x and since then, memory leak is observed. We even tried knex 0.13.0 with Node 6.9.10 and same issue is there. 

But, when we again ran tests with knex 0.11.6 with Node 6.9.x, memory leak is not observed.

Regards,
Sanjeev

**Comment by elhigu** [comment] 2017-06-09 22:48
Please add steps to reproduce.

**Comment by ayyasamy-murugesan** [comment] 2017-06-10 10:15
how u detected that memory leak issue..? 
i'm also using  0.12.6

**Comment by jacobheric** [comment] 2017-06-16 12:33
FYI, we saw a leak against mysql since the switch to the generic-pool in 0.12.*. See here for steps to reproduce: https://github.com/tgriesser/knex/issues/1969.  We had to switch back to 0.11.* to stabilize our app that uses knex.

**Comment by alexkrolick** [comment] 2017-06-22 17:46
We're seeing `Possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit` in our test suite with 0.13.0 - the db thread pool seems to not be cleaned up.

**Comment by wubzz** [comment] 2017-11-01 07:33
Based on tests in #2165 this should also be fixed by #2208 in 0.14. If not, please reopen.

**Closed by wubzz** 2017-11-01 07:33 UTC
Labels: pool

**Comment by skumar568** [comment] 2017-11-03 10:38
@wubzz  is 0.14 available now as http://knexjs.org/ still says 0.13.0 is the latest release. Please confirm.

**Comment by wubzz** [comment] 2017-11-03 11:18
@skumar568 No, 0.14 is not available now.

**Comment by skumar568** [comment] 2017-11-03 11:54
What is the ETA for this release?

**Comment by elhigu** [comment] 2017-11-03 16:00
This year

**Comment by tragiclifestories** [comment] 2017-11-06 11:34
@lucagrulla FYI
