### ISSUE TITLE
inversal methods for clear<Statement> (clearWhere) functions

### ISSUE THREAD

**Issue by atassis** [tgriesser/knex#3280] opened 2019-06-12 06:54 UTC
I am using [knex-hooks](https://github.com/alekbarszczewski/knex-hooks) to fire events after database events happening. I want to get the data for already made update queries, but can't get it properly from query builder object. It would be nice to have method to parse for example where statements from the query to use them next in new ones. It might be looking as 'extractWhere' or modifier function for `.modify ` method.

**Comment by elhigu** [comment] 2019-06-12 07:24
Not following issue template + duplicate of many issues, for example https://github.com/tgriesser/knex/issues/624 https://github.com/tgriesser/knex/issues/1893

**Closed by elhigu** 2019-06-12 07:24 UTC
