### ISSUE TITLE
Seeding Fails FK Constraints

### ISSUE THREAD

**Issue by jcrawford** [tgriesser/knex#2236] opened 2017-09-21 18:05 UTC
I have foreign keys in my database tables and while ```migrate:rollback``` works ```seed:run``` does not work more than once.  As soon as it tried to run the ```.del()``` it fails due to FK Constraints.

```
Using environment: development    
{ method: 'del',    
  options: {},    
  timeout: false,    
  cancelOnTimeout: false,  
  bindings: [],  
  __knexQueryUid: '6a8391bc-4815-4f1b-a202-734f148d640f',  
  sql: 'delete from `users`'
}  
Error: ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`tuna`.`users_roles`, CONSTRAINT `users_roles_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))
```

Once seeded for the first time I cannot seed again which means that I have to rollback all migrations, migrate again and then seed.  This has to happen every-time that I add a new migration and seeder to my project so it's a pain in the rear.

If it is not possible to fix this error with the seeders then I would suggest the creation of a ```migration:reset``` command that would rollback all migrations at one time that way it would be easier to re-generate the tables with seeded data. 

May I also suggest a ```migrate:latest -- seed``` command so that the migrations are run and then seeds are run?

I did also try the solution for #218 and that did not work for me for the seeds.

**Comment by elhigu** [comment] 2017-09-21 19:13
If you have designed that your seed file should be possible to be run multiple times and it fails when you run it again, sounds like your seed file is doing something wrong.

Are you trying to delete everything from DB before running the seed?  Are you deleting everything from your tuna table before trying to delete users?

**Comment by elhigu** [comment] 2017-09-21 19:18
Also you can easily write your own script, which runs migrations and then seeds for example to package.json scripts. I don't see that this issue is caused by knex bugs so closing, but feel free to keep discussing here.

**Closed by elhigu** 2017-09-21 19:18 UTC

**Comment by jcrawford** [comment] 2017-09-21 19:23
Here are what my seed files look like, when I run ```knex seed:run``` it complains about the FK Constraints.

Filename: 01_Users.js
```
let GUID = require('node-uuid');
let bcrypt = require('bcrypt');

exports.seed = function(knex, Promise) {
  let tableName = 'users';
  let rows = [
    {
      name: 'User One',
      username: 'user1',
      password_digest: bcrypt.hashSync('user1', 12),
      email: 'user1@domain.com',
      guid: GUID.v4()
    },
    {
      name: 'User Two',
      username: 'user2',
      password_digest: bcrypt.hashSync('user2', 12),
      email: 'user2@domain.com',
      guid: GUID.v4()
    },
    {
      name: 'User Three',
      username: 'use3',
      password_digest: bcrypt.hashSync('user3', 12),
      email: 'user3@domain.com',
      guid: GUID.v4()
    }
  ];

  return knex(tableName)
  // Empty the table (DELETE)
  .del()
    .then(function () {
      // Inserts seed entries
      return knex.insert(rows).into(tableName);
    });
};

```
Filename: 02_Roles.js
```
exports.seed = function(knex, Promise) {
  let tableName = 'roles';
  let rows = [
    {id: 1, role: 'user'},
    {id: 2, role: 'admin'},
    {id: 3, role: 'owner'}
  ];

  return knex(tableName)
  // Empty the table (DELETE)
  .del()
    .then(function () {
      // Inserts seed entries
      return knex.insert(rows).into(tableName);
    });
};
```

Filename: 03_UserRoles.js
```
exports.seed = function(knex, Promise) {
  let tableName = 'users_roles';
  let rows = [
    {id: 1, user_id: '1', role_id: '3'},
    {id: 2, user_id: '2', role_id: '3'},
    {id: 3, user_id: '3', role_id: '1'},
  ];

  return knex(tableName)
  // Empty the table (DELETE)
  .del()
    .then(function () {
      // Inserts seed entries
      return knex.insert(rows).into(tableName);
    });
};
```

**Comment by elhigu** [comment] 2017-09-21 20:30
Ofcourse it does throw an error since you are trying to delete all users and there are FK references to them from other tables. Create new seed file, which deletes everything in correct order and keep that uptodate when adding new seed files.

Also I can see that you are giving id's in seed files, remember to fix your id sequences afterwards so that next insert won't try to create duplicate ids with those you have already entered.

**Comment by elhigu** [comment] 2017-09-21 20:32
Btw. if you like to truncate multiple tables at the same time knex-db-manager can help you with that. It works currently for postgresql and mysql.

**Comment by jcrawford** [comment] 2017-09-21 20:38
Thanks for pointing out my issue, I will also take a look into knex-db-manager.

**Comment by jcrawford** [comment] 2017-09-21 20:50
Any reason something like this would not work?

```
exports.seed = function(knex, Promise) {
  let tables = ['users_roles', 'users_channels', 'users', 'roles', 'categories', 'channels'];
  tables.forEach(function(table) {
    knex.table(table).truncate();
  });
};
```

**Comment by jcrawford** [comment] 2017-09-21 21:11
Thank you for the assistance and suggestion.  I was able to get the knex-db-manager integrated for the truncate seed file.

**Comment by stoplion** [comment] 2019-07-01 23:09
issue comes up a lot on GH issues.. might be worth mentioning in the docs

**Comment by elhigu** [comment] 2019-07-02 09:43
> issue comes up a lot on GH issues.. might be worth mentioning in the docs

I don't think we should start teaching how SQL databases work in the docs. That is nothing specific to knex.

**Comment by ike18t** [comment] 2020-08-07 14:58
I saw this issue while investigating a solution. I ended up with an approach like @jcrawford inquired about and made sure is the first seed executed.

```
exports.seed = function (knex) {
  // has to be in the appropriate order :-/
  const tables = ['users_roles', 'users_channels', 'users', 'roles', 'categories', 'channels'];

  Promise.all(tables.map(table => knex(table).del()));
};

```
