### ISSUE TITLE
Oracle : Not able to lock tables on oracle database using transaction

### ISSUE THREAD

**Issue by apurvshah** [tgriesser/knex#3021] opened 2019-01-31 04:40 UTC
# Environment
node: v8.9.2
Knex version: 0.16.2
oracledb: 3.0.1 
Database + version: Oracle 11g/12C
OS: Windows8.1 Pro

Select applicable tempalate from below.
If issue is about oracledb@3.0.1 support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. In Oracle database tables are not getting locked. I am using 'knex.transaction(trx)' and then subsequent transacting(trx)/trx.commit for any database operation. My code base is same for both MSSQL and Oracle database. It is able to lock the tables in MSSQL, but doesn't lock tables in Oracle database.

# Feature discussion / request

1. I would like to lock the tables whenever I perform any CRUD operation on database. How can I achieve using 'knex'?

@atiertant

**Comment by elhigu** [comment] 2019-01-31 05:02
Transaction itself should not lock any tables. Please add reproduction code. There are tests for example that select for update works and locks everything correctly.

That being said, I would not be surprised if there are still bugs in oracledb client's transaction implementation.

Closing as cannot reproduce. Can be re-opened if repro code is added. More info about minimal reproduction case is found in CONTRIBUTING.md

**Closed by elhigu** 2019-01-31 05:02 UTC
