### ISSUE TITLE
Query Builder MERGE aka UPSERT

### ISSUE THREAD

**Issue by willfarrell** [tgriesser/knex#1351] opened 2016-04-15 20:40 UTC
The ability to uniformly apply and UPSERT to multiple languages.

Great summary of the different SQL implementations: https://en.wikipedia.org/wiki/Merge_(SQL)

Possible Syntax: `knex().insert({...}).upsert([keys]).update({...})`

**Comment by rhys-vdw** [comment] 2016-05-07 09:41
I'd like to see a discussion of the API, but `upsert` support would be great.

**Comment by rhys-vdw** [comment] 2016-05-10 03:54
Duplicate of #54

**Closed by rhys-vdw** 2016-05-10 03:54 UTC
Labels: duplicate, feature request
