### ISSUE TITLE
Transaction in raw queries doesn't work

### ISSUE THREAD

**Issue by tavolate** [tgriesser/knex#3452] opened 2019-09-24 09:27 UTC
# Environment

Knex version: 0.19.4
Database + version: Mysql v5.7.27
OS: OSX

# Bug

If I use transaction with a raw query, when an error occurs, the rollback function is called but without effect into the database.
 
Is it possible to use transaction with raw queries?

Below the snippet of my code:

`const trx = await knex.transaction();`
 `trx.raw('INSERT INTO...").then(trx.commit).catch(trx.rollback);`

**Comment by elhigu** [comment] 2019-09-24 19:11
Please add error message that you are getting.

**Comment by elhigu** [comment] 2019-09-24 19:13
Also what do you mean by "without effect into the database"... if rollback is called, there should be no effect.

**Comment by tavolate** [comment] 2019-09-24 20:15
I mean the Knex rollback funtion is called but the just inserted rows are
still there

Il giorno mar 24 set 2019 alle 21:13 Mikael Lepistö <
notifications@github.com> ha scritto:

**Comment by elhigu** [comment] 2019-09-24 22:02
does it work if you are doing the same query with `.insert` without using knex.raw? Which error are you getting? I mean you example code should not insert anything if error is thrown and that nothing should be removed anyways if rollback is executed...

Please add complete reproduction code.

**Comment by KristjanTammekivi** [comment] 2019-09-25 08:19
Failed to reproduce on postgres with same knex version
```typescript

    await db.raw(`CREATE TABLE IF NOT EXISTS test(a text)`);
    await db
        .transaction(async (trx) => {
            try {
                await trx.raw(`INSERT INTO test(a) VALUES ('lol')`);
                await trx.raw(`INSERT INTO test(b) VALUES (5)`);
                await trx.commit();
            } catch (e) {
                await trx.rollback();
            }
        })
        .catch(console.error);
    console.log((await db.raw('SELECT * FROM test')).rows.length); // === 0
    await db.raw('DROP TABLE test');

```

**Comment by elhigu** [comment] 2019-09-25 08:21
Closing until complete reproduction code is provided.

**Closed by elhigu** 2019-09-25 08:21 UTC

**Comment by tavolate** [comment] 2019-09-25 09:47
You can use this snippet to reproduce the issue

```
  const trx = await knex.transaction();

  await trx.schema.createTable("test", function(table) {
    table.increments();
    table.string("name");
  });

  await trx("test").insert({ name: "foo1" });
  await trx("test").insert({ name: "foo2" });

  await trx.rollback();
```

The behavior expected is no table created into the database, but the table is there instead

**Comment by KristjanTammekivi** [comment] 2019-09-25 10:08
Apparently in MySQL creating a table causes an implicit commit https://dev.mysql.com/doc/refman/5.6/en/implicit-commit.html

**Comment by tavolate** [comment] 2019-09-25 10:14
Ok, but the two rows are inside the table as well. According to your supposition, I would expect just an empty table

**Comment by elhigu** [comment] 2019-09-25 10:17
@KristjanTammekivi is correct.

Transaction gets committed directly after `createTable` is executed. Then when you send new inserts to that connection `trx` they are just executed in implicit transaction and finally when you try to rollback, there is actually nothing to rollback, since there is no active transaction going on.

Would be good if we are able to recognize when implicit commits are happening and also commit transaction on knex side at the same moment.

I don't know if mysql driver provides any events to catch those though.

**Comment by elhigu** [comment] 2019-09-25 10:19
Effectively `trx` returned by knex.transaction() is just a knex instance, which is bound to always use the same connection and with couple of extra methods for commit / rollback.

**Comment by tavolate** [comment] 2019-09-25 11:03
this snippet works correctly

  ```
await knex.schema.createTable("test", function(table) {
    table.increments();
    table.string("name");
  });

  const trx = await knex.transaction();

  await trx("test").insert({ name: "foo1" });
  await trx("test").insert({ name: "foo2" });

  await trx.rollback();
```

As you can see, if I don't use the transaction to create the table, the transaction is correctly rollbacked and the table is empty.

Maybe, can I use the transactionProvider to fix the issue?

**Comment by elhigu** [comment] 2019-09-25 12:39
> this snippet works correctly
> 
> ```
> await knex.schema.createTable("test", function(table) {
>   table.increments();
>   table.string("name");
> });
> 
> const trx = await knex.transaction();
> 
> await trx("test").insert({ name: "foo1" });
> await trx("test").insert({ name: "foo2" });
> 
> await trx.rollback();
> ```
> 
> As you can see, if I don't use the transaction to create the table, the transaction is correctly rollbacked and the table is empty.
> 
> Maybe, can I use the transactionProvider to fix the issue?

If that works perfectly, what is the issue that you are thinking of fixing with transactionProvider?

**Comment by tavolate** [comment] 2019-09-25 12:51
According @KristjanTammekivi the create table does an implicit commit. As you can see, I don't use the transaction to create the table.

I would like to use everywhere the transaction, but I think it's a technical limit of mysql. If so, for me the issue is closed.
