### ISSUE TITLE
pool: connection ending in fatal error are not removed from the generic pool

### ISSUE THREAD

**Issue by syndr0m** [tgriesser/knex#452] opened 2014-09-01 07:58 UTC
when having a fatal error on a mysql connection using knex 0.6.22 & pool & mysql driver,  the connection is not removed from the pool.

Further requests using this connection end in mysql driver error "cannot enqueue ... after fatal error" (PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR)

a workaround :
```
var knex;

var connectionErrorHandler = function (connection, err) {
  if (connection && err && err.fatal) {
    if (connection.removedFromThePool)
      return;
    connection.removedFromThePool = true;
    knex.client.pool.genericPool.destroy(connection);
  }
};

var config =  {
  client: 'mysql',
  (...)
  pool: {
    (...)
    afterCreate: function (connection, callback) {
      connection.on('error', connectionErrorHandler.bind(null, connection));
      connection.on('end', connectionErrorHandler.bind(null, connection));
      callback();
    }
  }
};

knex = knexInit(config);
```

it might be linked to #206

**Comment by wubzz** [comment] 2016-05-19 18:10
The recent changes to pool handling in knex from 0.9 and onwards seems to have addressed most issues. We also discovered this kind of behaviour specifically for mysql2.

I'm going to close this and consider it resolved, but feel free to add a new issue if the error persists.

**Closed by wubzz** 2016-05-19 18:10 UTC

**Comment by NemoAlex** [comment] 2017-11-10 07:38
I just experienced this error on 0.14.0.

**Comment by elhigu** [comment] 2017-11-10 17:35
@NemoAlex do you have some test code to reproduce that?

**Comment by shwuhk** [comment] 2017-11-15 15:40
I have encountered into this issue too.
We use mysql with pool. This error happen when the connection is idle for a long time(like more than ten minutes) and then we do some query.
I suspect that this was happening because knex is trying to use a connection which is already timeout.
Any ideas?

**Comment by elhigu** [comment] 2017-11-16 17:50
@shwuhk I would recommend to not use 0.14 until 0.14.1 is released. There are couple of nasty issues which were missed when generic-pool was updated. I'm working on those and hope to get 0.14.1 out this week.

**Comment by shwuhk** [comment] 2017-11-17 07:28
I would try it again then when 0.14.1 is out. Thanks.

**Comment by elhigu** [comment] 2017-11-20 16:50
@shwuhk 0.14.1 it is out
