### ISSUE TITLE
Adding support for transaction savepoint

### ISSUE THREAD

**Issue by SohumB** [tgriesser/knex#318] opened 2014-06-13 13:28 UTC
```
var knex = require('knex').initialize({..});

var q1 = knex('books').insert({ name: 'Canterbury Tales' });
var q2 = knex('books').insert({ name: 'Moby Dick' });

knex.transaction(function(t) {
  return q1.transacting(t).then(function(a) {
    return knex.transaction(function(t2) {
      return q2.transacting(t2).then(function(b) {
      });
    });
  });
}).then(function() { console.log('fine'); process.exit(0); },
        function() { console.log('problem'); process.exit(1); });
```

This script succeeds under normal operation on a simple `books` schema. But under `pool: { max: 1, min: 1 }`, it hangs.

**Comment by juanimarchese** [comment] 2016-01-09 01:50
I was writing some tests, and specially when you combine before and after with beforeEach and afterEach, SAVEPOINTS are very usefull!

Hope someone add this features in the future! Bookshelf should add this as well!

**Comment by chrisbroome** [comment] 2016-01-09 02:05
@juanimarchese They should already be supported via `transaction.transaction()`:

``` JavaScript

knex.transaction(transaction1 => {
  return transaction1.transaction(transaction2 => {
    // do something ...
  });
});

```

**Comment by shinzui** [comment] 2016-05-19 14:33
Is this still an issue? Does knex support savepoints now?

**Comment by jurko-gospodnetic** [comment] 2016-05-19 14:47
Yup, knex supports savepoints, as mentioned in https://github.com/tgriesser/knex/issues/318#issuecomment-170179070.

**Comment by shinzui** [comment] 2016-05-19 15:49
@jurko-gospodnetic I am curious why the issue is still open then. I am new to knex and bookshelf, and while I really like the libraries so far, I am having a hard time navigating the issues. It's hard to tell from reading the conversations which items are actual issues.

**Comment by jurko-gospodnetic** [comment] 2016-05-19 16:02
Let's close it and see if anyone yells :-)

P.S. I confirmed it on the internal maintainer chat first :-D

**Closed by jurko-gospodnetic** 2016-05-19 16:02 UTC
Labels: question

**Comment by kaplona** [comment] 2024-01-20 01:48
Its exciting to see that SAVEPOINTS are supported by knex, but it's really hidden. There is nothing in the documentation about it. Would be nice to have https://github.com/knex/knex/issues/318#issuecomment-170179070 example in the docs, so people don't need to go fishing for answers in github issues.

> Note that Amazon Redshift does not support savepoints in transactions

This is literally the only line that is there about SAVEPOINTS in the [docs](https://knexjs.org/guide/transactions.html#transaction-modes).
