### ISSUE TITLE
Race condition in knex?

### ISSUE THREAD

**Issue by ivan-kleshnin** [tgriesser/knex#618] opened 2015-01-06 08:59 UTC
Code is very complex so I presented only those parts, required to explain.
Basically, I want to mark the end of deeply nested async computations. There is no single 
"end callback", so I have `tasks` Array which is pushed on new task and popped on completion. I check that `tasks` are empty with `setInterval` handler below.

```javascript
var tasks = [];
knex("users").select("*").limit(10).map(function(row) {
   ...
   tasks.push(1);
   lib.makeImages(imagePath, function(err, images) {
     if (err) { throw err; }
     ...
     knex("images").insert(record).exec(function(err, ids) {
       if (err) { throw err; }
       tasks.pop();                                     // buggy variant
       // setTimeout(function() { tasks.pop(); }, 100); // hacked variant
      });
...
}).then(function() {
  var endInterval = setInterval(function() {
    // tasks are guaranteed to be ready at this stage...
    if (!tasks.length) {
      clearInterval(endInterval);
      knex.destroy(); // this line halts sometimes!
      console.timeEnd("total");
    }
  }, 100);
})
```

About 50% of runs it ends with:

```
Error: The genericPool is not initialized.
```

at `knex.destroy()`

When I replaced `tasks.pop()` with `setTimeout(function() { tasks.pop(); }, 100);` it now runs without error. Can somebody help me to understand what's the problem here? My expectations are falsy or is it real race condition in **knex**?

**Comment by bendrucker** [comment] 2015-01-06 12:43
There are a lot of anti-patterns here you should fix, most prominently checking a task queue on a loop. You should always invoke a function recursively from within itself instead of using timers.

Others:

* Combining the knex callback and promise interfaces (promises only)
* Leaking errors (all your `throw` calls will bubble up to the `process` and crash it)
* Nesting callbacks (see [Bluebird's promisification API](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object) so you can return promises from your `lib` module

The exception you're seeing has means a connection is trying to be acquired (or more likely released) unexpectedly. If you can reproduce this without `setInterval` and with only knex + the Bluebird API, I'm happy to take a look and get this fixed. Otherwise it's basically impossible to pin this down.

**Comment by ivan-kleshnin** [comment] 2015-01-06 17:46
Thank you!

This is a fragment from a script file, not a part of a server app so I don't care about process crashing. I actually want it to crash on first error.

> Checking a task queue on a loop. 
I only heard about timing differences between `setInterval` and recursive `setTimeout`. Could you elaborate why `setInterval` is "bad"?

> Combining the knex callback and promise interfaces (promises only)
Why is it bad? Because of mental overhead?

**Comment by bendrucker** [comment] 2015-01-06 19:06
Re: errors, you may want the process to crash, but you also have no ability to change your mind about that. When properly written, promise chains give you very easy flow control that would allow you to maintain that behavior with very little extra code. If someday you change your mind and want to try to recover from an error, this is going to become even more callback spaghetti than it is already.

The difference between the two is that `setInterval` schedules an invocation every `n` milliseconds. If the function's execution time is more than `n`, the next invocation will just happen immediately after the execution of the function completes. You basically never want the behavior `setInterval` provides. With recursive behavior, you pretty much always want "run me again `n` ms after I finish."

And finally, on promises/callbacks in combination, it's not just mental overhead. You're making all these async calls inside your `map` function and there is no way for you to propagate the results or errors. The point of promises is to allow an function to do something without explicitly calling a callback with the async result. You're writing code that's going to be massively frustrating to maintain because it's so tightly coupled to the exact way it's organized now.

**Comment by bendrucker** [comment] 2015-01-06 19:10
I'm closing this because there just isn't anything actionable we can do for this right now. I need to see this happening with code I can run.

**Closed by bendrucker** 2015-01-06 19:10 UTC

**Comment by ivan-kleshnin** [comment] 2015-01-06 19:33
You are very helpful, Ben, thank you again. A lot of information to reconsider.

**Comment by bendrucker** [comment] 2015-01-06 19:37
You're quite welcome. If you want an idea of how nicely promises work with task pipelines, check out this:

https://github.com/valet-io/send-sms

It chunks its workload and runs recursively until an "empty" condition is met.
