### ISSUE TITLE
ER_NO_DB_ERROR

### ISSUE THREAD

**Issue by DivenireCode** [tgriesser/knex#2034] opened 2017-04-28 03:48 UTC
when I send too many request in front side, the knex throw ER_NO_DB_ERROR or ER_NO_SUCH_TABLE.
but the less request, it would return true reponse.
client: mysql

**Comment by aalencar** [comment] 2017-04-28 16:38
Could you provide more context?

**Comment by DivenireCode** [comment] 2017-05-02 13:07
In front side, I send many request at the same time. 
like this;
`
for (let i = 0; i < 10; i++) {
    ajax({
        url: 'http://127.0.0.1:3000/api/v1/database/schema1/table1/' + i,
        success: function (r) { }
    });
    
    TT.ajax({
        url:'http://127.0.0.1:3000/api/v1/database/schema2/table2/' + i,
        success: function (r) {  }
    });
}
`

In the server side.
`
// koa
// koa-router
// app.js about knex init
const knex =  require('knex');
let databaseConnection = knex ({
    client: 'mysql',
    connection: {
        host: databaseConfig.host,
        user: databaseConfig.user,
        password: databaseConfig.password,
        port: databaseConfig.port,
        insecureAuth: true
    });
...
// route.js
router.use('/api/v1/database/:schema/:table/:id', function *(next) {
    yield databaseConnection.raw('use :schema:', this.params.schema);
    let r = databaseConnection(this.params.table).select().where('id', this.params.id);
    this.body = r;
})
`

so, I accept many request at the same time. 
it would happen that ‘use schema1’ but ‘select * from schema2.table2 where id = ?’

**Comment by elhigu** [comment] 2017-05-02 19:11
Hi, Please try to drop express from your test code and provide runnable single file example how to reproduce the problem. 

Also are you sure this one is doing correct query?

```
databaseConnection.raw('use :schema:', this.params.schema);
```

I'm pretty sure it sends just:

```
use :schema:;
```

to DB.

It probably should be:

```
databaseConnection.raw('use :schema:', this.params);
```

You can see what queries are sent to DB by setting `DEBUG=knex:*` environment variable to shell where you start your backend process.

**Comment by DivenireCode** [comment] 2017-05-04 03:37
sorry, This may be my server bug. 
I would do processing in each layer of route.
1. the top route '/:schema' we  would do `use :schema:;`' and turn to the next route
2. the second route '/:table' we would do `connection.shema.withSchema(’schema').hasTable(‘table’)` to make sure table exists and turn to the next route
3 the underlying route ‘/:id’  we would get data with id.
Through debugging i found that the bug happen in the second route '/:table'. i drop `connection.shema.withSchema(’schema').hasTable(‘table’)` and the server work well.
at the end, sorry for my bad English.

**Comment by elhigu** [comment] 2017-05-04 13:11
I'll close this, since according to discussion this doesn't seem to be a bug in knex

**Closed by elhigu** 2017-05-04 13:11 UTC
