### ISSUE TITLE
jest Not Closing

### ISSUE THREAD

**Issue by travistrue2008** [tgriesser/knex#2686] opened 2018-07-04 20:41 UTC
# Environment

Knex version: 0.15.0
Database + version: MySQL 5.7.21
OS: macOS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I'm not completely sure this is a bug or even knex-related, but I thought I'd post this here to at least get confirmation. I'm writing tests using `jest` where I create a database during `globalSetup`, and then tear it down in `globalTeardown`. `jest` closes as expected when I create and drop the database, but it will hang if I make any queries using knex in my tests. The queries do perform as expected, and don't output any errors

2. Error message
`jest` detects an open handle, but it's not related to knex.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

_setup.js_
```
import db from '../../src/db'

module.exports = async () => {
  await db.createDatabase()
}
```
_teardown.js_
```
import db from '../../src/db'

module.exports = async () => {
  await db.dropDatabase()
}
```

db.js
```
import knex from 'knex'

import knexfile from '../../knexfile'

let pool = knex(knexfile)

// create the connection pool
async function createPool () {
  pool.min = 0
  await pool.destroy()
  pool = knex(knexfile)
}

async function createDatabase (name) {
  const dbName = name || connInfo.database
  const dbConfig = Object.assign({}, knexfile)
  delete dbConfig.connection.database

  // re-create the connection pool with no database name, create the database, and use it
  await createPool()
  await pool.raw(`
    CREATE DATABASE IF NOT EXISTS ${dbName}
      DEFAULT CHARACTER SET = utf8mb4
      DEFAULT COLLATE = utf8mb4_unicode_ci
  `)

  // re-add the database name to the knexfile config
  console.info(`Database has been created: ${dbName}`)
  dbConfig.connection.database = dbName
  await createPool() // re-create the pool using the database once again
  console.info('DONE DONE DONE DONE DONE')
}

async function dropDatabase () {
  // drop the database using the existing connection pool
  await pool.schema.raw(`DROP DATABASE IF EXISTS ${connInfo.database}`)
  await pool.destroy()
  pool = null

  console.info('Database has been dropped')
}

export default {
  createDatabase,
  dropDatabase,

  get pool () {
    return pool
  },
}
```

**Comment by elhigu** [comment] 2018-07-04 22:19
Please add single file minimal test case for reproducing the problem without jest. If the problem is that jest is doing something mystic which causes the behaviour then issue should be opened to jest support forum. Also knexfile contents is important to add.

Im 60% certain that you’ll find what is causing the behavior you are experiencing while writing that minimal test case.

I would close this as cannot reproduce for now. There is more info how minimal repro should lopk like in CONTRIBUTING.md

**Comment by travistrue2008** [comment] 2018-07-06 01:54
@elhigu Thanks for the heads-up! I created a minimum repo, and couldn't reproduce it myself. I eventually came up with a workaround: create a raw `mysql` connection to create/drop the database. Then, I added initialize()/shutdown() functions that serve as wrapper functions to create and destroy the pool within along with a few other precautions.

**Comment by ricardograca** [comment] 2018-07-06 08:45
If you or someone else runs into this issue again and can create a reproducible test case we can reopen it.

**Closed** 2018-07-06 08:44 UTC
Labels: invalid

**Comment by good-idea** [comment] 2019-10-23 00:25
For those coming here with the same (or similar) issue, "cleaning up" knex in jest is a little confusing.

Your `globalTeardown` file is the place to empty (or drop) the database. But, you still need to `kill` the knex connection. There is a new connection for *each test file*, so you need to clean that up separately, with:

```js
afterAll(async(done) => {
   await knex.destroy()
   done()
})
```

You can either put this in each of your test files, or in a single script that is loaded with `setupTestFileAfterEnv` in the jest config.

**Comment by elhigu** [comment] 2019-10-23 05:56
@good-idea Sounds like you are initializing new knex instance (with new pool) in every test file... If you would be using the same knex instance in every test file, then single global `.destroy()` should be enough.

**Comment by barroudjo** [comment] 2020-05-26 09:19
Long after the battle, but it might still be useful:
@elhigu in fact in jest each test file is executed independently (so that they can be run in parallel). So each creates its own node export singletons, meaning each does indeed have its own knex instance, no way around it...
Here's the jest issue explaining this: https://github.com/facebook/jest/issues/7184
So  @good-idea 's way is the only way as far as I can tell...

**Comment by Jwiggiff** [comment] 2024-02-06 20:23
Just found this thread. I'm not sure if knex has been updated since but I am trying to add the code snippet from @good-idea's answer but it says that `property destroy does not exist on type typeof knex`. I have each of my functions that I am testing in a different file which each import a common `db.js` which exports a function that returns a knex object. I have no access to the internal knex instance that each function is using.
