### ISSUE TITLE
Corrupt migration directory

### ISSUE THREAD

**Issue by annnfrann** [tgriesser/knex#1747] opened 2016-10-18 22:05 UTC
Every time I try to run a migration to production, I get the following error: `Error: The migration directory is corrupt, the following files are missing: 20160712115200_create_books.js`. This is an old migration file, not in the database I'm trying to migrate, and has quite probably been deleted. I've checked other issues and the docs, but I haven't found anything to help me with this problem. I'm not sure what to do.

**Comment by elhigu** [comment] 2016-10-18 22:23
If you are sure your database is in consistent state with your set of migrations you can look your `migrations` table from the database and remove the row, which mentions the missing migration file.

Other way to get rid of the error is to create migration file, which actually doesn't do anything with name: `20160712115200_create_books.js`. There is no checksum of the original migration file stored, so system will think that your newly created file was the one it sees in the `migrations`table.

Please close this issue afterwards if one of the tricks did work for you.

**Comment by DariaDesiderata** [comment] 2017-12-05 01:06
I am having the same issue. The solution proposed by @elhigu has absolutely nothing to do with the problem. Knex is somehow looking at old migrations folder instead of the current one. In my case the old folder is from March 2017 and the current one is from December 2017.

**Comment by elhigu** [comment] 2017-12-05 16:44
@DariaDesiderata knex tries to look migrations from the folder that is mentioned in knexfile. I might be able to help if you can show me the list of your migration files in those directories and contents of your `migrations` table.

If you have once ran migrations from your `March 2017` directory to your database, then you cannot just change the migration directory to point to `December 2017`, because knex requires that old migration files are not removed.

If you change the folder, then knex will think that there are some migrations missing. tdlr; knex does not support running migrations from multiple separate folders to the same database.

**Closed by elhigu** 2017-12-05 16:44 UTC

**Comment by elhigu** [comment] 2017-12-05 16:48
Though there is no reason why it couldn't support that. 

So if you make feature request for some option to disable migration directory consistency check I don't see why it couldn't be implemented if someone is motivated enough to do it.

**Comment by abemm7787** [comment] 2021-07-18 08:22
@annnfrann 
I would just copy and paste the 20160712115200_create_books.js  back into the explorer.

**Comment by badbabykosh** [comment] 2022-05-01 02:53
No one seems to be listening to the women here. I quote @dariawhitecastle..."I am having the same issue. The solution proposed by @elhigu has absolutely nothing to do with the problem. Knex is somehow looking at old migrations folder instead of the current one. In my case the old folder is from March 2017 and the current one is from December 2017." 
...This statement is STILL relevant today as of April 2022. I am having the EXACT same issue as are my students. I have two entirely separate apps located in two entirely different locations on my file system. And knex is looking for the migration files from the first app when I run "npx knex migrate:latest" on my second app. The apps are unrelated and DO NOT share table names at all.

**Comment by kibertoad** [comment] 2022-05-01 09:21
@badbabykosh Can you share your knexfile (sans password)? migration directory comes from knexfile, past migrations come for the knex_changelog in the db, comparison is between the two. if there is stuff in changelog that shouldn't be there, delete it from your db.

**Comment by dschwan21** [comment] 2022-05-19 20:33
Having the same issue with #5177 , wondering if any solution has been found yet? The migrations that show up as missing are from totally unrelated projects, not previously deleted files.

**Comment by ibrahimjamil** [comment] 2022-07-21 23:46
@dschwan21 any solution for that issue

**Comment by munyirik** [comment] 2024-08-14 18:33
In my case, what solved the issue is not to use a database url (or "connection string"). In your config use: 'user', 'password', etc.
This is such a strange issue. I still have no idea how knex was listing non-existent migration files (since I had deleted previous dbs). Unless there's some cache it keeps in the file system?
