### ISSUE TITLE
MySQL float (precision, scale) should be optional

### ISSUE THREAD

**Issue by dsego** [tgriesser/knex#2411] opened 2018-01-04 19:11 UTC
# Environment

Knex version: 0.14.2
Database + version: MySql 5.6.37
OS: ubuntu 

# Feature discussion 

Currently, knex defaults to `float(8,2)` instead  of simply `float` without precision & scale.
The undocumented `double` method actually does the right thing and doesn't default to some arbitrary precision.
```
  double(precision, scale) {
    if (!precision) return 'double'
    return `double(${this._num(precision, 8)}, ${this._num(scale, 2)})`
  },
```

This just seems common sense, no? 
There should be a way to specify I don't want precision & scale.

[MySQL docs on floating point type](https://dev.mysql.com/doc/refman/5.6/en/floating-point-types.html)

**Comment by elhigu** [comment] 2018-01-07 22:10
Is this duplicate of https://github.com/tgriesser/knex/pull/2353 ?

**Comment by dsego** [comment] 2018-01-08 00:08
Not really, that one is for decimal, this is for float.

**Comment by elhigu** [comment] 2018-01-08 06:47
I mean the part of reasoning why to not change the current default behaviour and how the support can be implemented if someone likes to implement it. I'll reopen and change description a bit so that this is open for anyone to implement.

**Comment by dsego** [comment] 2018-01-08 15:46
A general solution would be to have something like `knex:upgrade_migrations`. It's ridiculous to have the API stuck with bad decisions from the past.

**Comment by elhigu** [comment] 2018-01-08 15:59
@dsego I know. There are lots of API changes that I would like to do, but this is not right time for that. Writing completely new migration APIs and slowly deprecating old ones would be pretty safe path, but just breaking one API every now and then would be pretty annoying for everyone and wont make overall quality of migration APIs much better.

**Comment by dsego** [comment] 2018-01-08 16:26
I'm not in favor of that decimal solution, it does not spark joy.  This should be fixed in some future version, but `specificType` is better than retrofitting special values. I am all for closing this issue and moving on

**Comment by elhigu** [comment] 2018-01-08 16:33
I would do the same :)

**Closed by elhigu** 2018-01-08 16:33 UTC
Labels: PR please
