### ISSUE TITLE
Incorrect delimiters used on column names with sqlite3.

### ISSUE THREAD

**Issue by rhys-vdw** [tgriesser/knex#1048] opened 2015-11-05 07:42 UTC
I'm not sure of the standards for each DBMS, but this behaviour is surely wrong. Initially reported in tgriesser/bookshelf#948.

``` js
sqlite3('table').select('hello').toString();
// select "hello" from "table"
```

``` sql
create table t(id integer primary key, name text);
insert into t (name) values ('Rhys');

select * from t;
-- 1|Rhys

select "name", "hello" from t;
-- Rhys|hello

select `name`, `hello` from t;
-- Error: no such column: hello
```

The backtick delimiters differentiate between string literal (which is a valid SELECT argument) and column name.

**Comment by chrisbroome** [comment] 2015-11-05 14:31
So the issue is that sqlite is ambiguous in its column/string delimiters? If at all possible, double quotes should be used for column names and single quotes for string literals (standard behavior).

**Comment by irsl** [comment] 2016-06-05 17:25
Any news on this? Knex should wrap field names into backticks. The current behaviour is especially bad with where conditions :(

```
console.log(knex("sessions").select("s_id").where({s_id: 123}).toString())
=>
select "s_id" from "sessions" where "s_id" = 123
```

**Comment by elhigu** [comment] 2016-06-05 18:09
@irsl could you also add example how correct result should be for that query?

**Comment by irsl** [comment] 2016-06-05 18:20
The problem is the above query will never match any rows, since the constant string "s_id" is never the same as 123.

Column names should be wrapped into backticks both in columnize and in the various where filters too. The above query should look like this:

```
select `s_id` from `sessions` where `s_id` = 123
```

**Comment by yasir095** [comment] 2016-06-19 09:29
Is this fixed. really need a fix on it. As mysql doesn't support double quoted table names.

**Comment by elhigu** [comment] 2016-06-19 10:46
@yasir095 With mysql backticks are used:

```js
knex = require('knex')({client: 'mysql'});
console.log(knex("sessions").select("s_id").where({s_id: 123}).toString())
// select `s_id` from `sessions` where `s_id` = 123
```

**Comment by yasir095** [comment] 2016-06-19 12:01
awesome thanks

**Comment by Kryten0807** [comment] 2016-11-23 15:04
I'm still seeing this behaviour with sqlite3 version 3.1.8 and knex version 0.12.6:

The query was created with:

    this.database.select('group_id').from('users_to_groups').where('user_id', '=', 1)

The debug output is

    { method: 'select',
      options: {},
      timeout: false,
      cancelOnTimeout: false,
      bindings: [ 1 ],
      __knexQueryUid: '365a3dc6-d107-4abb-9c7f-1ef1dba621db',
      sql: 'select "group_id" from "users_to_groups" where "user_id" = ?' }

it's pretty clear that this arises due to differences in string delimiters between sqlite and the other DBMS, but I'm not sure what the differences are, exactly (or how to go about fixing them).

Queries with an empty `select()` list work fine, so I can work around this by picking out the column I want from each row. But this is a serious issue with sqlite support. I'd go so far as to say it's broken.

**Comment by carragom** [comment] 2017-06-04 17:24
According to the SQLite [docs](https://sqlite.org/lang_keywords.html), the standard quote character for identifiers is `"`. Here is an extract of the docs:

**'keyword'**	A keyword in single quotes is a string literal.
**"keyword"**	A keyword in double-quotes is an identifier.
**[keyword]**	A keyword enclosed in square brackets is an identifier. This is not standard SQL. This quoting mechanism is used by MS Access and SQL Server and is included in SQLite for compatibility.
**\`keyword\`**	A keyword enclosed in grave accents (ASCII code 96) is an identifier. This is not standard SQL. This quoting mechanism is used by MySQL and is included in SQLite for compatibility.

The `"` is the standard according to SQL-99, more info [here](https://stackoverflow.com/questions/2901453/sql-standard-to-escape-column-names).

@irsl  You mention that `"s_id"` is considered a constant string. But that does not seem to be the case in my tests with SQLite and the docs say otherwise too.

Here is an example of my point:
```
$ sqlite3 test.sqlite3
SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.
sqlite> create table test ("s_id" int, "s_name" text);
sqlite> insert into test values (123, 'Jhon Doe');
sqlite> select * from test where "s_id" = 123;
123|Jhon Doe
```

If you run that example you can see that `"s_id"` is actually considered a column identifier and not really a constant or literal string. If you want a literal string you have to wrap it in single-quotes `'`.

**Comment by elhigu** [comment] 2017-06-07 17:44
@carragom check this comment https://github.com/tgriesser/knex/issues/1048#issue-115226160 there are shown how they actually work. Double quotes are interpreted as string if column by that name is not found. Anyways, this is now implemented, closing.

**Closed by elhigu** 2017-06-07 17:44 UTC
Labels: bug
