### ISSUE TITLE
Maria Runner Incorrectly Parsing DATETIME

### ISSUE THREAD

**Issue by niftylettuce** [tgriesser/knex#524] opened 2014-10-10 16:33 UTC
I have UTC values stored in my DB as the value of `DATETIME`.

However here <https://github.com/tgriesser/knex/blob/9777a1c3dea044666e3066b76935dd45ee8a6a84/lib/dialects/maria/runner.js#L89-L91> you can see that the `DATETIME` is parsed the same as `TIMESTAMP`.

```js
function parseType(value, type) {
  switch (type) {
    case 'DATETIME': // <-------
    case 'TIMESTAMP':
      return new Date(value);
    case 'INTEGER':
      return parseInt(value, 10);
    default:
      return value;
  }
}
```

Is it possible to be able to pass some information on the timezone here?

**Comment by elhigu** [comment] 2016-05-31 18:20
I'll close this as duplicate of #1461. Newer ticket has more discussion and proposed fix to allow users override how types returned from mariasql driver to javascript values.

**Closed by elhigu** 2016-05-31 18:20 UTC
Labels: bug
