### ISSUE TITLE
Destroy method doesn't wait for client shutdown

### ISSUE THREAD

**Issue by simontabor** [tgriesser/knex#1872] opened 2017-01-19 15:54 UTC
`knex.destroy()` resolves before the clients in the pool are actually destroyed. I believe the `destroyRawConnection` method should listen for the relevant client event (usually `end`) and only resolve when all clients have emitted an end/close event.

Seems like quite a major oversight that knex doesn't cleanly shut down.

**Comment by elhigu** [comment] 2017-01-20 08:36
Can't reproduce... did you try on 0.12.6?

```
knex = require('knex')({ client: 'pg', connection: 'postgres:///objection_test'});
Promise.all([knex.raw('select 1'), knex.raw('select 1')])
  .then(() => knex.destroy())
  .then(() => console.log("==================== DESTROY RESOLVED ======================"))

>   knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=2 +1m
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=1 +2ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query select 1 +2ms
  knex:bindings [] +0ms
  knex:query select 1 +1ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid1 +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=1 +0ms
  knex:client releasing connection to pool: __knexUid2 +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=2 +0ms
  knex:pool INFO pool postgresql:pg:client0 - draining +0ms
  knex:pool INFO pool postgresql:pg:client0 - force destroying all objects +0ms
==================== DESTROY RESOLVED ======================
```

Closing for now until there is way to reproduce...

**Closed by elhigu** 2017-01-20 08:36 UTC
