### ISSUE TITLE
knex production distribution pulls @types/bluebird and @babel/polyfill 

### ISSUE THREAD

**Issue by osher** [tgriesser/knex#3097] opened 2019-03-09 14:59 UTC
# Environment

Knex version: `-- knex@0.16.3`
Database + version: irrelevant, but well... - mysql 5.7
OS: irrelevant, but well - windows 10 with GNU on Windows (GOW)

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Having installed `knex` as a dependency - I Expect in `node_modules` only dependencies REQUIRED for `production` env.

### Installing knex

Scenario: 
 - run `npm intall knex`.
 - Look in your node_modules

Expect:
- only production time dependencies.

Found:
 - @types/bluebird and @babel/polyfill

Given:
 - some migrations, and some seeds

### running it without the suspected unecessary dependenceis

Scenario:
 - run `rm -rf node_modules/@types/bluebird node_modules/@babel/polyfill
 - run `knex migrate:latest`
 - run `knex seed:run`

Expect (if to believe the `dependencies` section of the `package.json`):
 - an error

Found:
 - the migrations and seeds ran successfully.

I did not proceed to check the rest of the dependencies - so there could be more irrelevant dependencies. I simply knew that `babel` and `types` are not supposed to be in production dependencies section 😕 and knew it would be super easy to test

Thanks, and keep up the good work!

**Comment by kibertoad** [comment] 2019-03-09 15:20
Appreciate the effort put! We did get rid of polyfills at some point, and see comment next to PR with explanation why bluebird types are needed. See https://github.com/tgriesser/knex/issues/2948 that was raised when we removed types.
Thank you! Since this is not a bug, I'm closing the issue.

**Closed by kibertoad** 2019-03-09 15:20 UTC

**Comment by kibertoad** [comment] 2019-03-09 15:21
I wonder if there is a better solution that wouldn't require people to include typings manually, though, or would at least inform them about what the problem is and how they can address it.

**Comment by osher** [comment] 2019-03-10 17:41
Excuse me, I cannot understand the sense of your answer - as far as I understand - your answer refers to **development** time, not **production** time.... I'm sure of that because interfaces belong to the IDE, not to production time.
Can you please help me understand what am I getting wrong?

**Comment by kibertoad** [comment] 2019-03-10 18:10
@osher See https://stackoverflow.com/a/46011417

Basically imagine you are a developer and you pull in knex as a dependency. Suddenly you are getting build errors because you also need bluebird typings that knex depend upon and does not bring transitively (since devDependencies are not resolved transitively). Unfortunately, npm provides no mechanism for transitive devDependencies, hence bundling bluebird types as production dependency at this point look like the lesser of two evils. However, Objection.js picked a different approach (do not bundle types from knex and bluebird), and I am open to be convinced otherwise. @elhigu, what do you think?
