### ISSUE TITLE
Insert doesn't work all the time

### ISSUE THREAD

**Issue by mihaivinaga** [tgriesser/knex#3261] opened 2019-06-05 23:42 UTC
Knex 0.17.3
mysql 5.7
OS: macos

Full disclousre, I am new to knex, hell I am new to nodejs and I am having a difficult time getting knex to insert multiple rows on a consistent basis. I am running the following query:

```
db('website_attributes').insert(technologies).then(function (result) {
    console.log(result);
});
```
 And most of the time it works but  once in a while I get the following error:

```
TypeError: this.client.acquireConnection(...).catch(...).disposer is not a function
    at Runner.ensureConnection (/var/www/soleadify-wappalyzer/node_modules/knex/lib/runner.js:233:8)
    at Runner.run (/var/www/soleadify-wappalyzer/node_modules/knex/lib/runner.js:33:41)
    at Builder.Target.then (/var/www/soleadify-wappalyzer/node_modules/knex/lib/interface.js:23:43)
    at wappalyzer.analyze.then.rawTechnologies (/var/www/soleadify-wappalyzer/process_wappalyzer.js:78:67)
```
 
Any thoughts with what I am doing wrong?

**Comment by knoxcard** [comment] 2019-06-06 05:22
Does this only happen when you a run a lot of queries at once?

**Comment by elhigu** [comment] 2019-06-06 11:28
@mihaivinaga please add complete reproduction code (single js file, which runs knex queries in a way that you get that error) for the issue. Problem is not in the code that you pasted.

Closing as cannot reproduce.

**Closed by elhigu** 2019-06-06 11:28 UTC
