### ISSUE TITLE
.toString() and .toSQL() methods don't escape '?' character.

### ISSUE THREAD

**Issue by mstralenya** [tgriesser/knex#2150] opened 2017-07-06 12:30 UTC
Hi, I'm using 'toString' method to store generated queries before inserting them. If column name contains a question mark, then knex generates wrong column names for insert query(e.g. column name can take one of inserted value in addition to its name). 
Also, I checked toSQL method - if column name contains a question mark, then I'm getting knex errors in 'raw' method even if I escape this character by '\\\\'.

**Comment by elhigu** [comment] 2017-07-06 15:58
Please add an example to reproduce this.

**Comment by mstralenya** [comment] 2017-07-07 08:01
@elhigu [there it is](https://gist.github.com/mstralenya/35a06ae7aefc976426d4b145ad650285)

**Comment by wilsonpage** [comment] 2017-07-13 15:57
I'm also seeing `?` replaced by `$1`, `$2`, etc when inserting data into `json`/`jsonb` columns using the `knex.raw(...)` syntax. Here's my code:

```js
module.exports = ({ knex, table, data, constraint }) => {
  const insert = knex(table).insert(data);
  const updateData = Object.assign({}, data);

  // don't change the createdAt date when updating
  delete updateData.createdAt;
  const update = knex.queryBuilder().update(updateData);

  const query = knex.raw(`${insert} ON CONFLICT (${constraint}) DO ${update} returning *`);
  return query.then((result) => result.rows[0]);
};
```

If I use the normal `knex.insert()` API all is fine. I tried escaping the `?` using:
  - `/?`
  - `//?`
  - `///?`
  - `??`

But nothing seems to work.

**Comment by elhigu** [comment] 2017-07-13 16:05
@wilsonpage you shouldn't convert queries to strings with js template strings `${}`

```
const query = knex.raw(`${insert} ON CONFLICT (${constraint}) DO ${update} returning *`);
```

this way value bindings are kept as value bindings and passed correctly to db driver

```
const query = knex.raw(`? ON CONFLICT (??) DO ? returning *`, [insert, constraint, update]);
```

**Comment by wilsonpage** [comment] 2017-07-13 16:11
@elhigu what's the solution then?

**Comment by wilsonpage** [comment] 2017-07-13 16:23
This alternative `upsert` method solved the problem for me. Still not sure what the cause was though.

**Comment by elhigu** [comment] 2017-07-13 16:57
@mstralenya ? -marks in identifier names are tough. Currently they are not escaped... this problem is pretty complex. Maybe it would be better if identifier wrapper would automatically escape question marks in identifiers. I'm closing this as a duplicate in favor to https://github.com/tgriesser/knex/issues/2152 which already contain some more discussion about the issue.

**Closed by elhigu** 2017-07-13 16:57 UTC

**Comment by elhigu** [comment] 2017-07-13 17:00
@wilsonpage when you use ${} to render queries, knex interpolates all strings and escapes values by itself. So query is passed as plain string to DB driver with all the values (including json data string containing ? -marks) are inlined. 

When subqueries are passed with ? bindings to knex.raw, all their internal values are still passed as safe parameter bindings to db driver, so knex converting ? -> $1, $2 etc. won't break...

**Comment by ssgtcookie** [comment] 2017-09-06 09:54
Use this; https://laravel.com/docs/5.5/database#listening-for-query-events

**Comment by rpuls** [comment] 2018-06-19 07:28
There seem to be some inconsistency depending on what environment you are running. At least what have worked for some does not work for other. What I did that solved my problem was this:
`INSERT INTO db."table"("id", "bodyText") VALUES (1234, '\? - \\? - \\\? - \\\\? # /? - //? - ///? - ////?');`
In my case the output was: `? - $13 - ? - $14 # /$15 - //$16 - ///$17 - ////$18` ie. I am now using single backslash for escaping the question mark which works with my environment. My knex version is 0.14.6, 
but I can't promise that I don't have any other node packages that touches my queries before they are executed.
