### ISSUE TITLE
Insert where not exists support

### ISSUE THREAD

**Issue by andrezzoid** [tgriesser/knex#1322] opened 2016-03-31 16:40 UTC
Hi there,

first of all, great work on knex, it's being wonderful working with it!

With that said, just wanted to check if `WHERE` statements still aren't supported on inserts? (issues  https://github.com/tgriesser/knex/issues/211 and https://github.com/tgriesser/knex/issues/378)

**Comment by rhys-vdw** [comment] 2016-03-31 23:28
They currently are supported:

```js
knex('users').insert(
  knex
    .select('john.doe@email.com', 'John Doe')
    .whereNotExists(knex('users').where('email', 'john.doe@email.com'))
)
```

```sql
insert into "users" select "john"."doe@email"."com", "John Doe" where not exists (select * from "users" where "email" = 'john.doe@email.com')
```

We should get this example into the docs under `insert`.

**Comment by wubzz** [comment] 2016-04-01 06:01
@rhys-vdw The email string selection is interesting, tho. :fearful:   *"john"**.**"doe@email"**.**"com"*

I think you'd have to `knex.select(knex.raw('"john.doe@email.com"'), 'John Doe')` to bypass that.

**Comment by rhys-vdw** [comment] 2016-04-01 16:26
Oh yeah, whoops. Also it's actually not working because the `VALUES` clause is not there! I'm going to close this as a duplicate of #1323 because it has more information.

**Closed** 2016-04-02 14:13 UTC
Labels: duplicate

**Comment by TSiege** [comment] 2020-06-05 16:38
If anyone else has stumbled here trying to do this with a `whereNotExists` clause here's an example I have working with my own code.
```js
knex(
  // insert values clause
  knex.raw('?? (??, ??, ??)', ['posts_authors', 'author_id', 'post_id', 'sort_order'])
).insert(
  // select where not exists clause
  knex.select(
    knex.raw('?, ?, ?', [author_id, post_id, sort_order])
  ).whereNotExists(
    knex('posts_authors').select('id').where({ author_id, post_id: id })
  )
)
```

**Comment by aggaton** [comment] 2021-01-04 22:48
Just want to point out for any poor Oracle souls out there. To get above code working on Oracle you need a .from('DUAL') right before .whereNotExists, in case you haven't already spotted it.

**Comment by rhys-vdw** [comment] 2021-01-05 22:08
@aggaton you should create a new issue for this.
