### ISSUE TITLE
Error: Failed to load external module coffee-script/register,coffee-script

### ISSUE THREAD

**Issue by light24bulbs** [tgriesser/knex#1137] opened 2016-01-14 08:57 UTC
Any idea what this error is about?  Happens on command: ```knex migrate:latest```
  Coffeescript is installed in the local node-modules.  If I open a node repl, I can require coffee-script register fine.  Node is installed through NVM..  All my knex config is coffeescript.

**Comment by johnnypez** [comment] 2016-01-14 10:26
+1

**Comment by light24bulbs** [comment] 2016-01-14 18:17
This is happening for you, too, @johnnypez?  I wonder if there was a recent breaking change or something.  Please let me know if you figure out what is up.  This has totally blocked development.  I've tried everything I could think of.  Some folks seem to think it may be related to my NODE_PATH env var, but when I set that it still doesn't work.  I may try rolling back knex and seeing if that fixes it.

**Comment by johnnypez** [comment] 2016-01-14 21:13
To work around it, I just dropped back to plain js.
From what I could see, it looked like an array of ['coffee-script/register','coffee-script'] was being passed to require and I think only require('coffee-script/register') is necessary. I didn't have time to dig any further though.

**Comment by svicalifornia** [comment] 2016-01-15 05:30
+1

**Comment by svicalifornia** [comment] 2016-01-15 05:41
**It works in knex 0.8.6.** Seems to be a new bug introduced in knex 0.9.0.

**Comment by light24bulbs** [comment] 2016-01-15 22:55
Confirmed, working in 0.8.6.  Took me a while to figure this out because I needed to change the version of the GLOBAL knex, not the local one. So:  

```npm remove -g knex```
```npm install -g knex@0.8.6```

**Comment by wreckah** [comment] 2016-02-03 13:24
+1

**Comment by light24bulbs** [comment] 2016-02-03 18:57
Coffeescript support is currently broken!! @tgriesser

**Comment by svicalifornia** [comment] 2016-02-23 03:42
@tgriesser CoffeeScript support is still broken in 0.10.0

**Comment by mjhm** [comment] 2016-03-11 20:43
It looks like this is a problem where [liftoff.js](https://github.com/js-cli/js-liftoff/issues/47) isn't fully compatible with an update to [js-interpret](https://github.com/js-cli/js-interpret/issues/25)

**Comment by phated** [comment] 2016-03-12 01:08
Due to the diligent work by @mjhm, I was able to track this down quickly.  It seems that the `interpret` dependency was bumped but the `liftoff` dependency stayed pinned at `~2.0.0` but we added support for the extended syntax in 2.1.0 which wouldn't be installed unless the version was changed to `^2.0.0` or manually bumped to 2.1.0 or 2.2.0.  It was just added functionality in liftoff and didn't require a major bump (and we still support the old syntax from 0.5.x, I believe).

**Comment by tjwebb** [comment] 2016-03-12 05:45
@phated @mjhm can someone clue me in to what this has to do with knex, and how we can fix it?

**Comment by phated** [comment] 2016-03-12 07:04
Yes, that's what my post stated :/

**Comment by light24bulbs** [comment] 2016-03-16 21:47
Does this mean that manually updating liftoff to 2.2.0 will fix this
issue?  So updating knex's package requirements to the higher version
requirement would fix this issue?

On Fri, Mar 11, 2016 at 11:04 PM, Blaine Bublitz <notifications@github.com>
wrote:

> Yes, that's what my post stated :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgriesser/knex/issues/1137#issuecomment-195676436>.
>



-- 
-Forrest

**Comment by rhys-vdw** [comment] 2016-03-16 23:01
@phated Would you provide a PR with the necessary updates? Currently I guess we have no tests for running CoffeeScript migrations. I wonder if it would be worth adding something simple to guard against regressions? For now just bumping the relevant dependencies should be sufficient.

**Comment by phated** [comment] 2016-03-16 23:54
@rhys-vdw sorry, no time currently.  Like you said, the version bump is sufficient and should have been done when bumping the interpret dependency.

**Comment by light24bulbs** [comment] 2016-03-17 20:13
Confirmed this fixes it.  Created a pull request here https://github.com/tgriesser/knex/pull/1292

**Comment by rhys-vdw** [comment] 2016-03-18 03:14
Thanks @light24bulbs. Merged.

**Closed by rhys-vdw** 2016-03-18 03:14 UTC
Labels: bug, migrations, PR please

**Comment by svicalifornia** [comment] 2016-03-20 18:49
Awesome, thanks! When will this fix be released to NPM?

**Comment by svicalifornia** [comment] 2016-04-11 08:20
@rhys-vdw Can we get a 0.10.1 bug-fix release to knex on npm?

**Comment by mjhm** [comment] 2016-04-11 16:20
+1 for a bug-fix release.  @svicalifornia As a stopgap I added this to my `package.json: scripts`
```
"postinstall": "(cd node_modules/knex; npm uninstall liftoff)"
```
and added `"liftoff": "^2.2.1"` as an explicit dependency.

**Comment by morungos** [comment] 2016-06-03 14:37
Still an issue in 0.11.5 :-(
