### ISSUE TITLE
New method: knex.columnRef(), wraps column identifiers in backticks / quotes

### ISSUE THREAD

**Issue by cspotcode** [tgriesser/knex#872] opened 2015-06-21 00:48 UTC
Many knex methods expect a column name and wrap it in quotes or backticks to disambiguate it from any SQL keywords of the same name.

```
knex('post').leftJoin('user', 'author', 'user.id').select()
select * from `post` left join `user` on `author` = `user`.`id` -- MySQL
select * from "post" left join "user" on "author" = "user"."id" -- Postgres and SQLite
```

However, in cases where knex is expecting a bound value, not a column identifer, I use `knex.raw`.

```
queryBuilder.where('price', '<', knex.raw('`user`.`accountBalance`'))
```

Backticks are MySQL-specific.  I'd rather write DB-agnostic code where possible.

I realize "user.accountBalance" isn't going to cause any problems without backticks, but "email.from" might cause problems, and I write some code where I can't enforce sane column naming.

What if there was a method, `columnRef`, to be used in such situations?

```
knex('item').where('price', '<', knex.columnRef('user.accountBalance'))
select * from `item` where `price` < `user`.`accountBalance`
```

Apologies if such a method already exists.  I couldn't find it in the documentation or the source.  I did find `columnize` and wrote the following implementation of a `columnRef` method:

```
knex.columnRef = function(columnName) {
    return this.raw(this.client.queryCompiler(this.queryBuilder()).formatter.columnize(columnName));
}
```

**Comment by hotaru355** [comment] 2015-07-03 01:31
I have always been looking for this. :+1:  if it doesn't exist :).

**Comment by whitelynx** [comment] 2015-07-10 21:18
Possible duplicate of (or at least related to) #723.

**Comment by elhigu** [comment] 2015-07-13 06:25
+1 i've been hoping to see this function too

**Comment by absolux** [comment] 2017-03-02 11:18
A painless solution
```js
qb.whereRaw('price > ??', 'user.accountBalance'))
```

**Comment by cspotcode** [comment] 2017-03-02 14:24
@absolux Thanks!

Here's an implementation of `columnRef` / `identifier`. (Thanks @whitelynx for a much better name)
```
knex.identifier = function(columnName) {
    return knex.raw('??', columnName);
}
```

**Comment by wubzz** [comment] 2018-02-23 07:55
Closing in favor of discussion in #2507

**Closed by wubzz** 2018-02-23 07:55 UTC
