### ISSUE TITLE
this._factory.validate is not a function

### ISSUE THREAD

**Issue by pasupulaphani** [tgriesser/knex#1787] opened 2016-11-17 16:17 UTC
```
FULL BACKTRACE:
/app/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:304
/app/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:392
/app/node_modules/knex/lib/client.js:281
/app/node_modules/bluebird/js/release/debuggability.js:299
/app/node_modules/bluebird/js/release/promise.js:481
/app/node_modules/bluebird/js/release/promise.js:77
/app/node_modules/knex/lib/client.js:272
/app/node_modules/knex/lib/runner.js:200
/app/node_modules/bluebird/js/release/debuggability.js:299
/app/node_modules/bluebird/js/release/promise.js:481
/app/node_modules/bluebird/js/release/promise.js:77
/app/node_modules/knex/lib/runner.js:198
/app/node_modules/bluebird/js/release/util.js:16
/app/node_modules/bluebird/js/release/method.js:39
/app/node_modules/knex/lib/runner.js:197
/app/node_modules/knex/lib/runner.js:47
/app/node_modules/knex/lib/interface.js:35
/app/node_modules/bluebird/js/release/util.js:16
/app/node_modules/bluebird/js/release/thenables.js:63
/app/node_modules/bluebird/js/release/thenables.js:28
/app/node_modules/bluebird/js/release/generators.js:151
/app/node_modules/bluebird/js/release/generators.js:99
/app/node_modules/bluebird/js/release/generators.js:201
```

Has anyone experienced this?

**Comment by elhigu** [comment] 2016-11-18 09:43
Please provide some steps to reproduce this problem.

**Comment by pasupulaphani** [comment] 2016-11-21 12:41
we debugged a lot and found that the reference to``` this._factory``` is being lost somewhere. But Knex is passing the validate function correctly. Unfortunately we cannot reproduce the error locally.

This happens seldomly when there is a bulk of connection requests made.

**Comment by elhigu** [comment] 2016-11-21 13:48
cannot reproduce so I'm closing this for now.

**Closed by elhigu** 2016-11-21 13:48 UTC

**Comment by pasupulaphani** [comment] 2016-11-29 18:05
@elhigu this is happening a lot for us.

**Comment by elhigu** [comment] 2016-11-29 18:19
I suppose you could try to add some debug prints in your system to node_modules/generic-pool/lib/generic-pool.js and to knex and try to figure out that way why it is failing.
