### ISSUE TITLE
.limit(0) not limiting to empty array

### ISSUE THREAD

**Issue by leore** [tgriesser/knex#655] opened 2015-01-31 03:35 UTC
When I do .limit(0) I end up getting the entire dataset back. 0.6.* did not have this behaviour

**Comment by vschoettke** [comment] 2015-01-31 17:28
Duplicate of #585. This is already fixed in the repo but yet not published to npm.

Just out of curiosity, why do you want to execute limit(0) query?

**Closed by vschoettke** 2015-01-31 17:28 UTC

**Comment by leore** [comment] 2015-01-31 17:54
We have an API that takes count and offset as query parameters. Our users and apps that consume this api have corner cases where they pass in count=0 and expect to get an empty array not the full data set.

**Comment by leore** [comment] 2015-02-02 17:23
When do you think #585 will be published to npm?

**Comment by tgriesser** [comment] 2015-02-02 17:35
Ah sorry abt. that... I'll do a quick pass through and try and get a release out today
