### ISSUE TITLE
Can 't Create table

### ISSUE THREAD

**Issue by RamK777** [tgriesser/knex#3252] opened 2019-06-04 11:03 UTC
I am just installed knex version .
But i am not able to create table it always throws me an error 

`Error: create table `user` () - SQLITE_ERROR: near ")": syntax error`

`let knex = electron.remote.require("knex");`

  ```
const knexInstance = knex({
      dialect: "sqlite3",
      connection: {
        filename: pathname
      }
    });

knexInstance.schema.createTable('user', (table) => {
      table.increments('id')
      table.string('name')
      table.integer('age')
    })
    .then(() => {console.log('success')})
```

**Comment by elhigu** [comment] 2019-06-04 12:14
Try first to learn how to do it in node without electron. There are many tests, which creates tables with sqlite just like that. Im pretty sure that your problem is not in the code you pasted here. Also knex usage questions should go to stackoverflow or gitter. This tracker is for bugs. 

Closing as cannot reproduce.

```
knex = require('./lib')({client: 'sqlite', connection: ':memory:'}); knex.schema.createTable('user', (table) => {table.increments('id');table.string('name');table.integer('age');}).then((res) => console.log("SUCCESS"));  
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> SUCCESS
```

**Closed by elhigu** 2019-06-04 12:14 UTC

**Comment by hodgef** [comment] 2022-02-28 01:30
I had the same issue, this happens when you try to run knex in the renderer in newer Electron versions.

Essentially, you need to run the callback in the `main`, not the renderer. I was able to work around this issue by creating an interface.

eg:

main

```js
const knex = require('knex');
let db;

/**
 * Knex 
 */
global.knex = (options) => {
  db = knex(options);
};

global.db = ({
  createTable: (tableName, params = []) => {
    return db.schema.createTable(tableName, (table) => {
      params.forEach(({ name, type }) => {
        table[type](name);
      });
    });
  },

  /**
   * Insert
   */
  insert: (tableName, rows) => {
    return db(tableName).insert(rows);
  },

  /**
   * Select
   */
  select: (tableName, query) => {
    return db(tableName).select(query);
  },
});
```

renderer

```js
const remote = require("@electron/remote");
const knex = remote.getGlobal('knex');
const db = remote.getGlobal('db');

knex({
    client: "sqlite3",
    connection: {
      filename: "./file.db",
    },
    useNullAsDefault: true
});

await db.createTable("sites", [
  { name: "id", type: "increments" },
  { name: "uuid", type: "string" },
  { name: "name", type: "string" },
]);

await db.createTable("items", [
  { name: "id", type: "increments" },
  { name: "uuid", type: "string" },
  { name: "siteId", type: "string" },
]);
```
