### ISSUE TITLE
v0.16.1 messes with global Promise

### ISSUE THREAD

**Issue by MartinKolarik** [tgriesser/knex#2942] opened 2018-12-09 23:36 UTC
```js
global.Promise = require('bluebird');
console.log(Promise.map); // [Function]
require('knex');
console.log(Promise.map); // undefined
```

**Comment by elhigu** [comment] 2018-12-09 23:40
Might have something to do with a fact that babel compiles knex now compiles to ES6 target. I didn't find anywhere that knex source code would have messed with it.

**Comment by kibertoad** [comment] 2018-12-10 04:33
Let me catch my breath after the flight and I'll take a look... Thanks for the report! And it does look like polyfill thing indeed.

**Comment by elhigu** [comment] 2018-12-10 05:55
Marked as discussion, because I’m not so sure if this is a bug or documentation issue or what (it is a bit nasty to override global Promise to cause all the libs use something unexpected. Of course optimal thing would be to not to touch it by knex.

**Comment by kibertoad** [comment] 2018-12-10 15:32
@MartinKolarik I can't reproduce it in a test. Could you please specify a Node version that you are using?

**Comment by MartinKolarik** [comment] 2018-12-10 15:41
Was using `10.8.0` but now updated to `10.14.1` (windows) with the same result.

**Comment by MartinKolarik** [comment] 2018-12-10 15:46
https://runkit.com/martinkolarik/5c0e89d0abb5de00174c5b87 (it says knex 0.15.2 which is weird because that isn't the latest version and it even works with that version locally, but still)

**Comment by kibertoad** [comment] 2018-12-10 15:51
@MartinKolarik Thanks! Reproduced, fixed, waiting for review :)

**Comment by MartinKolarik** [comment] 2018-12-10 15:54
@kibertoad amazing, thanks!

**Closed** 2018-12-10 16:20 UTC
Labels: discussion
