### ISSUE TITLE
join using syntax error

### ISSUE THREAD

**Issue by s97712** [tgriesser/knex#2913] opened 2018-11-16 13:42 UTC
# Environment

Knex version: master
Database + version: postgresql 10
OS: archlinux

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
```
knex.from('tb1').join('tb2', function(){
  this.using('column')
});
```
That's my code, it should be generator `select * from tb1 inner join tb2 using(column)`  
But it actually generator  `select * from tb1 inner join tb2 using column` ,  `using` need followed by brackets

**Comment by kibertoad** [comment] 2018-11-16 13:45
@s97712 Thank you for your report! Would you consider contributing a failing test for this case?

**Comment by ManuelDevelopment** [comment] 2018-11-18 02:17
I'm experiencing this issue as well, but I also ran into problems when using sub-querys in the [#from()](https://knexjs.org/#Builder-from) method. The generated queries look fine, but are missing any parantheses, which makes them invalid for (in my case) _SQLite3_. Could this be a more general issue with brackets in queries?

**Comment by elhigu** [comment] 2018-11-18 15:31
@ManuelDevelopment open separate issue please

**Comment by elhigu** [comment] 2018-11-18 15:32
This report seems legit: https://runkit.com/embed/eopc3c8web21

https://www.postgresql.org/docs/9.2/queries-table-expressions.html

**Comment by wubzz** [comment] 2018-11-18 17:58
I believe this is fixed in next version. #2136 #2713

**Comment by kibertoad** [comment] 2018-11-18 18:00
@wubzz @elhigu We reaaaaaally need to push 0.16.0 out of the door. Can I help with those Oracle failures somehow?

**Comment by elhigu** [comment] 2018-11-18 21:33
Installing docker and running `npm run oracledb:test` runs tests in docker against oracle. I just tried it and it is column renaming test which seems to hang.

**Comment by kibertoad** [comment] 2018-11-18 21:41
@elhigu Took a look at how `renameColumn` is implemented in Oracle. Holy cow. I'm not surprised there's  a problem with it. Do you suspect that we actually have a regression?

**Comment by elhigu** [comment] 2018-11-18 22:03
I haven't checked when the problem started. If there was just a new integration test added in that case I suppose it has been broken all the time.

**Comment by kibertoad** [comment] 2018-11-18 22:15
@elhigu I don't have nearly enough Oracle expertise to fix the issue myself, unfortunately. What's our plan to proceeed with it? Do you think that you might have time in the nearby future to take a look at it yourself?

**Comment by elhigu** [comment] 2018-11-18 22:47
I think renameColumn should not have been implemented in knex side, because it seems to be far from trivial operation in many SQL dbs :) I'll check out if it is regression, probably it is not. In that case we can just throw an error on oracle to prevent it from hanging.

**Comment by elhigu** [comment] 2018-11-18 22:48
maybe add new feature request for it if someone is willing to fix the implementation.

**Comment by elhigu** [comment] 2018-11-18 23:48
closing this issue since it has been fixed in master as @wubzz mentioned.

**Closed by elhigu** 2018-11-18 23:48 UTC
