### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by shawnwhinnery** [tgriesser/knex#770] opened 2015-04-15 19:33 UTC
Strugling with knex setup with postgres. 

I've never run into a library that appears to handle errors so gracefully while totally neglecting to output anything useful for a developer. No error messages, no logged queries, no database connection issues. Nothing.

The internet claims debug:true will do this but it has no effect.

**Comment by tgriesser** [comment] 2015-04-22 19:51
Dupe of #769

**Closed by tgriesser** 2015-04-22 19:51 UTC
