### ISSUE TITLE
Add support for node-oracledb. https://github.com/oracle/node-oracledb

### ISSUE THREAD

**Issue by tombburnell** [tgriesser/knex#646] opened 2015-01-26 11:40 UTC
We have a desire to move our Node application which uses knex.js from Mysql to Oracle. Oracle has released a new node driver (https://github.com/oracle/node-oracledb). It would be good to have support for it within knex.js. Cross link for convenience: https://github.com/oracle/node-oracledb/issues/3

**Comment by llambda** [comment] 2015-01-26 16:40
Good idea. I just got node-oracledb compiled and working recently and will start looking into this.

**Comment by cjbj** [comment] 2015-01-27 04:26
Let me know if I can help.

**Comment by llambda** [comment] 2015-01-27 04:57
I'll take all the help I can get :-) I committed a patch with the beginnings of support at https://github.com/llambda/knex/commits/oracledb and it is so far able to do selects with knex.

**Comment by robertd** [comment] 2015-01-29 16:57
+1 on knex/oracle support

**Comment by pmarino90** [comment] 2015-02-03 10:46
+1

**Comment by bendrucker** [comment] 2015-02-03 23:20
Good to know folks are interested. No more +1s please. Would love a PR.

**Comment by llambda** [comment] 2015-02-18 23:02
Somebody else can pick this up. I don't have enough time sorry.

**Comment by cjbj** [comment] 2015-02-18 23:06
Calling all volunteers!  Any takers?

**Comment by ecowden** [comment] 2015-02-27 04:32
I'm interested and might even have some free time coming up this weekend. I could really use some guidance, though. Can anyone point me in the right direction?

From scanning through the existing codebase, I _think_ I have a general sense of how a dialect fits together. @llambda's approach makes sense, leveraging the existing query logic but overriding the connection bits. 

What needs to be done next?

**Comment by vschoettke** [comment] 2015-02-27 08:00
@ecowden I don't think there is much to it. All the SQL-workarounds for oracle are already done for node-oracle. Excluding the API differences you may need to change is the transaction related stuff and remove.
The problem with oracle's own db driver is that it still seems to have  a bug that need to be fixed for it to work ok (returning into) with knex and bookshelf. There is also no support for streams but you can work around that.
You may also remove need to set 'maxRows' that oracle's driver defaults to 100.

**Comment by cjbj** [comment] 2015-02-27 16:16
We are still getting input into how users might want to handle the values and arrays (potentially, if rarely, large arrays) that RETURNING INTO might return. This is why support is pending.  The issue is being tracked at https://github.com/oracle/node-oracledb/issues/4

**Comment by cjbj** [comment] 2015-05-11 23:30
@ecowden @vschoettke node-oracledb 0.5.0 supports RETURNING INTO now

**Comment by theothermattm** [comment] 2015-06-25 15:13
+1

**Comment by helios1138** [comment] 2015-07-15 14:58
+1

**Comment by cjbj** [comment] 2015-07-21 02:16
The node-oracledb driver is continuing to be enhanced.  Helping @llambda on knex support would be a great thing. https://github.com/llambda/knex/commits/oracledb

**Comment by tjwebb** [comment] 2015-08-17 18:35
+1

**Comment by atiertant** [comment] 2015-09-22 11:35
please test https://github.com/tgriesser/knex/pull/990

**Comment by bchr02** [comment] 2015-10-22 03:32
+1

**Comment by gouldner** [comment] 2015-11-05 00:40
+1

**Comment by rpavez** [comment] 2015-11-24 18:12
+1

**Comment by mikaturunen** [comment] 2016-04-18 05:23
:+1:

**Comment by rpavez** [comment] 2017-03-16 04:51
Any update on this?

**Comment by elhigu** [comment] 2017-03-16 11:42
This was implemented last year and also CI runs tests against oracle r11 express

**Closed by elhigu** 2017-03-16 11:42 UTC
