### ISSUE TITLE
Model not updated on knex migration.

### ISSUE THREAD

**Issue by monera23** [tgriesser/knex#1496] opened 2016-06-14 13:39 UTC
I ran couple of migration files on the db stored on digital ocean. I am not getting the updates on the addition of the columns on a table. When I check the knex_migration table it shows that the migration has been listed there, but the changes are not visible. And when I try to do knex migrate:latest --env staging It shows Already upto date.  What could I be doing wrong here ? The migration changes work properly on my local db.

**Comment by elhigu** [comment] 2016-06-14 15:10
Sounds like you have ran migrations so that file is listed in migration table and then you have changed the file contents later. You can verify if that is the case by checking when migration is executed to DB  (from migration table) and by checking timestamps of migration file / commit history of your migration.

If you see that none of the changes of migration file has not been applied to DB you can remove that migration row from migration table and re-run migrate:latest.

**Comment by monera23** [comment] 2016-06-14 16:03
Thanks a lot for your help. I did have a look  and I didn't make any changes to the file and also the timestamp is in order. What could have been the problem ?

**Comment by elhigu** [comment] 2016-06-15 07:17
@monera23 I have no idea :( if problem cannot be reproduced I would suspect some user error... anyways since there is no way to verify that there is a bug and no way to reproduce problem I'll close this for now. 

Please reopen this if you are able to reproduce this problem.

**Closed by elhigu** 2016-06-15 07:17 UTC
