### ISSUE TITLE
Pool was destroyed

### ISSUE THREAD

**Issue by BionanoDev** [tgriesser/knex#1202] opened 2016-02-14 22:58 UTC
Running knex 0.9.0 with PostgreSQL 1.20.   This is on a windows laptop.  Everything is local.  We have a web page that does a simple single table query.  If you sit on that page and start refreshing it after about 30 times, the page crashes with this error.  We tried playing with the min/max settings but nothing seems to prevent the error.  

Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: remaining connection slots are reserved for non-replication superuser connections
Unhandled rejection Error: Pool was destroyed at Pool._destroyPool

**Comment by elhigu** [comment] 2016-02-14 23:01
@BionanoDev What is PostgreSQL 1.20? Could you provide some test code to reproduce the problem?

**Comment by BionanoDev** [comment] 2016-02-14 23:14
our app.ts file routes to a function.   That function first opens a connection.  (We have been playing with different min/max values).

var knex = require('knex')({
        client: 'pg',
        connection: {
            host: '127.0.0.1',
            user: 'xxxx',
            password: 'xxx',
            database: 'ScoreAppDB'
        },
        pool: {
            min: 0,
            max: 1
        }
    });

then we do a select from the Event table and list the results on an ejs page.  

 knex('Event')
.innerJoin('Game', 'Event.GameFk', 'Game.GamePk')
.orderBy('EventCode')
.then(function (events) {
        res.render('eventList', { events });
});

nothing fancy.   It works and is fast, but after several refreshes it crashes with the error above.   Given that we may have 30-40 concurrent users our testers feel this is a valid test scenario.

**Comment by BionanoDev** [comment] 2016-02-14 23:30
we also see this with the error text:

Error: read ECONNRESET
    at exports._errnoException (util.js:849:11)
    at TCP.onread (net.js:544:26)

**Comment by elhigu** [comment] 2016-02-15 08:18
I would need complete test case which you first verify that doesn't work to start debugging.

Does this kind of code fail on your setup?

```js
knex = require('knex')({...opts...})

Promise.all(_.times(30, function () {
  return knex('Event').limit(10);
}).then(function(res) {
  console.log("Results", res);
}); 
```

**Comment by BionanoDev** [comment] 2016-02-15 16:11
Here is some testable code.  Your assistance is tremendously appreciated.  You are helping a high school robotics team.

first we have a connection file that holds my connection settings (connection.ts) so that I don't have them in each method that uses a connection.   Then I included the method from my route class.  so I put opening the connection inside the loop.   Was thinking this morning maybe we should share the connection in the express app across the route functions, but I'm not sure how to do that.  This test lists the team name about 30 times then fails with the econnreset error.  

-----
export function getConnection() {
    var knex = require('knex')({
        client: 'pg',
        connection: {
            host: '127.0.0.1',
            user: 'xxxx',
            password: 'xxxx',
            database: 'xxxx'
        },
        pool: {
            min: 0,
            max: 10,
         }
    });
    return knex;
};
-----

export function list(req: express.Request, res: express.Response) {
   
    //get database connection
    var conn = require('../data/connection');  
 
    for (var i = 0; i < 100; i++) {
        var knex = conn.getConnection();
        knex('Team').then(function (teams) {
            console.log(teams[0].TeamName);
        });
    } 
}

**Comment by BionanoDev** [comment] 2016-02-15 17:40
Hmmm, might have gotten it.  changed my connection.ts to match this one:

   https://github.com/bschwind/api-starter-kit/blob/master/apps/node/db.js

Then changed how I get the knex variable to match this:

   https://github.com/bschwind/api-starter-kit/blob/master/apps/node/controllers/authController.js

now I cannot get it to crash by looping or refreshing.   will do more testing and verify.

**Comment by elhigu** [comment] 2016-02-15 19:24
@BionanoDev great, let me know if there is still anything you need from us. I'll close this for now, since this is merely support issue than knex bug / feature :)

**Closed by elhigu** 2016-02-15 19:24 UTC
Labels: More information requested
