### ISSUE TITLE
Unhandled rejection Error: Cannot find module 'pg-native'

### ISSUE THREAD

**Issue by barisvelioglu** [tgriesser/knex#1439] opened 2016-05-22 09:59 UTC
> When I try to use hash properties , it throws an error 

Unhandled rejection Error: Cannot find module 'pg-native'

```
db('test').where({'id' : 1, 'name' : 'blabla'})     
                             .first('*').then(function(value){ console.log(value) });
```

> When I change it like below, it works. Whats the problem ?

```

db('test').where('id',  1)
             .andWhere('name', 'blabla')        
             .first('*').then(function(value){ console.log(value) });
```

**Comment by elhigu** [comment] 2016-05-22 10:18
Which version of knex? Does it throw some error also with 

```js
db('test').where({'id' : 1, 'name' : 'blabla'})  .first('*').toString()
```

I wasn't able to reproduce the problem.

Sounds like some knex.raw is passed until postgres driver... I would recommend to try if it works better with 0.11.4.

**Comment by barisvelioglu** [comment] 2016-05-22 10:24
I fixed the problem by installing pg-native to my app. Now it throws me a different error when I run the code you offer

db('test').where({'id' : 1, 'name' : 'blabla'})  .first('*').toString()

[TypeError: Converting circular structure to JSON]

**Comment by elhigu** [comment] 2016-05-22 10:34
installing pg-native won't fix the problem, it is just hiding one symptom. Query you mention should not cause that error though. This should be fixed in 0.11.4 which will be out later today.

**Comment by elhigu** [comment] 2016-05-22 10:37
If this keeps happening after 0.11.4 I'll dig in and check why knex.raw instance is passed until driver (which causes circular structure).

**Comment by barisvelioglu** [comment] 2016-05-22 10:46
I do update the module 0.11.3 but it keeps saying that. How to update it to 0.11.4 version ?

**Comment by elhigu** [comment] 2016-05-22 11:01
it will be released later today.  What does 0.11.3 say? Actually changes in 0.11.4 is just to fix how that behave inside transaction so 0.11.3 could work too.

**Comment by barisvelioglu** [comment] 2016-05-22 11:44
Actually I found why the problem is happening but I dont know the reason ?

Assume, I have two files on the projects.

```
extensions.js
app.js
```

**extensions.js**

```
"use strict"

Object.prototype.test1 = function(){
  return null;

};

Object.prototype.test2 = function(){
  
  return null;

};

```

**app.js**
  
require('./extensions');

var db = require('knex')({
      client: 'pg',
      connection: {
        host     : 'localhost',
        port : 5432,
        user     : 'sqluser',
        password : 'asdqwe',
        database : 'Omega2',
        charset  : 'utf8',
        multipleStatements: true
      }});

db("projects").update({'name' : "3434343"}).where({id : 2, name : '3434343'}).then(function(value){
			   			console.log(value);
			   });


If the extensions.js contains any Object extension, the problem happens. When I delete the Object.prototype.test1, problem goes away the query runs. Is there any reason why this is happening ?

**Comment by elhigu** [comment] 2016-05-22 15:50
Huh... I would need to get complete example to check what exactly is happening, but extending object prototype is generally bad idea. After that it is increasingly more probable that many js libraries will fail to very random errors.

**Comment by wubzz** [comment] 2016-05-22 16:05
I wasn't able to reproduce the `pg-native` error either, but I was able to get a query error about column `test1` not existing. I definitely don't condone extending the Object prototype as is done above, but in any case the culprit seems to be [this](https://github.com/tgriesser/knex/blob/master/src/query/builder.js#L262). Iterating `Object.keys` instead would solve this -- can't speak for any other implications, tho.

**Comment by elhigu** [comment] 2016-05-22 19:24
There seem to be many places where `for ... in` is used... not sure if it is feature or bug. One can use `Object.defineProperty` to create non-enumerable property... For now I would consider this as a feature.

Any comments @tgriesser @rhys-vdw ?

**Comment by barisvelioglu** [comment] 2016-05-23 04:59
Some queries work, some queries dont work. It should run all or none to named it as feature. It seems bug to me.

**Comment by elhigu** [comment] 2016-05-23 06:44
@barisvelioglu Even if that key traversing code is changed to use e.g. `Object.keys` still some queries will work and others will fail if you pass them invalid parameters to query builder. In this case modifying `Object.prototype` did broke the parameters, since you introduced new invalid enumerable property to an input object.  

Even if this one place is changed, there are still infinite different ways to mess with `Object.prototype` and make `knex` API to fail unexpectedly. 

What I meant with bug or feature was to ask that has it been intentional that `knex` traverse through all enumerable properties (i.e. is it intentional using `for ... in` loop)?

**Comment by wubzz** [comment] 2016-05-26 05:54
@elhigu I started getting this issue for inserts. I started debugging and ended up in the `pg` module's `utils.js` function `prepareObject` which is trying to `JSON.stringify(obj)` -- and `obj` is an instance of `Raw`...

Perhaps similar as #1451

**Comment by CreepGin** [comment] 2016-06-02 00:42
I just want to confirm that it does have something to do with JSON.stringify as @wubzz pointed out. Whenever I use console.json on a query object, I get the `Error: Cannot find module 'pg-native'`

**Comment by rhys-vdw** [comment] 2016-06-02 02:59
So, this is caused by a "getter" in the pg module throwing.

```js
var o = {};
Object.defineProperty(o, 'myObnoxiousProperty', {
  get: function() {
    throw new Error('This was a bad idea');
  }
});

var y = o.myObnoxiousProperty:
// ERROR: This was a bad idea

JSON.stringify(o);
// ERROR: This was a bad idea

var x = _.clone(o);
// ERROR: This was a bad idea

etc.
```

**Comment by kibertoad** [comment] 2018-10-21 18:34
@rhys-vdw Is this something that we may, need and want to address?

**Comment by elhigu** [comment] 2018-10-22 11:41
I don't think there is nothing to address here.

**Comment by elhigu** [comment] 2018-10-22 11:41
I don't think there is anything to address here.

**Closed by elhigu** 2018-10-22 11:41 UTC

**Comment by tahv0** [comment] 2019-03-28 12:11
Getting this message with knex 0.15.2

**Comment by elhigu** [comment] 2019-03-28 20:32
> Getting this message with knex 0.15.2

@tahv0 please provide also some code for reproduction if you think that is a bug.

**Comment by kibertoad** [comment] 2019-03-28 20:59
@elhigu Considering that we dont have pg-native dialect, isn't it obvious pg-native as driver won't work?

**Comment by elhigu** [comment] 2019-03-28 22:22
@kibertoad this issue is not much related to a that fact... I cannot remember where that original error actually ended up trying to require pg-native. Maybe code like stringifying value was trying to access require('pg').native or something....

**Comment by tahv0** [comment] 2019-03-29 11:45
> > Getting this message with knex 0.15.2
> 
> @tahv0 please provide also some code for reproduction if you think that is a bug.

I made some more research and my issue were not related to this library. Sorry for opening this thread for nothing.
