### ISSUE TITLE
MySQL ECONNRESET

### ISSUE THREAD

**Issue by CNaismith** [tgriesser/knex#2443] opened 2018-01-29 17:15 UTC
# Environment

Knex version: 0.14.2
Database + version: MySQL 5.5.56 (ClearDB)
OS: Windows 10 - Pro
Node: 8.9.3

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

After inactivity on a web app, I am receiving an ECONNRESET which after refreshing the page, appears to resolve the some connection issue. I am guessing it's an issue of MySQL ending the connection and knex being unable to realize that.

2. Error message
Terminal: `Knex:warning - Connection Error: Error: Connection lost: The server closed the connection.`

Knex response:

```
select * from `tblcustomers` where `idCustomers` = 60381 - read ECONNRESET
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
    --------------------
    at Protocol._enqueue (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Connection.query (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\mysql\lib\Connection.js:208:25)
    at D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\knex\lib\dialects\mysql\index.js:156:18
    at Promise._execute (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\promise.js:79:10)
    at Client_MySQL._query (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\knex\lib\dialects\mysql\index.js:150:12)
    at Client_MySQL.query (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\knex\lib\client.js:211:17)
    at Runner.<anonymous> (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\knex\lib\runner.js:149:36)
    at Runner.tryCatcher (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\util.js:16:23)
    at Runner.query (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\method.js:15:34)
    at D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\knex\lib\runner.js:61:21
    at tryCatcher (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Users\Chris-PC\Documents\Web Design\KnexIssueTest\node_modules\bluebird\js\release\promise.js:512:31)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

My config: 

```
const knex = require("knex")({
    client: 'mysql',
    connection: {
        host: '',
        user: '',
        password: '',
        database: '',
        //debug: true,
        pool: {
            min: 0,
            max: 2
        }
    }
});
```

**Comment by CNaismith** [comment] 2018-01-31 15:28
If there is anything else I can do to provide more information please let me know. As this is currently very frustrating as I have tried multiple different ways to handle this and none have seemed to work.

**Comment by elhigu** [comment] 2018-01-31 16:36
Please create single file testcase tonreproduce the issue. I was just today trying to reproduce similair issue with mysql and mariabd and neither of them did cut connection during 2 hours idle time in my test.

**Comment by elhigu** [comment] 2018-01-31 16:37
There is very little anyone can do if you are not able to isolate environment in which this happen.

**Comment by elhigu** [comment] 2018-01-31 16:44
Here is issue with testcode / env setup which was not able to show any connection timeouts https://github.com/tgriesser/knex/issues/2442

**Comment by CNaismith** [comment] 2018-02-02 00:54
After running the following code (which was provided in the other thread) with the connection to my ClearDB mysql database I got the error.

```
const knex = require('knex')({
    client: 'mysql',
    connection: {
        host: '',
        user: '',
        password: '',
        database: '',
        //debug: true,
        pool: {
            min: 2,
            max: 10
        }
    }
});

console.log(new Date());

const Bluebird = require('bluebird');
function periodOfTime () {
  return Bluebird.delay(1000 * 60 * 15);
}

async function main () {
  await knex.raw('select 1');
  await periodOfTime();
  await knex.raw('select 1');
}

main();
```

```
(node:16336) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: select 1 - read ECONNRESET
(node:16336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by zerolethanh** [comment] 2018-02-02 01:06
You do not catching a error, try: 
```js
async function main () {
 try{
  await knex.raw('select 1');
  await periodOfTime();
  await knex.raw('select 1');
 }catch(e=>console.error(e))
}

**Comment by CNaismith** [comment] 2018-02-02 01:25
```
2018-02-02T01:08:47.496Z
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
    --------------------
    at Protocol._enqueue (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Connection.query (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\mysql\lib\Connection.js:208:25)
    at d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\dialects\mysql\index.js:156:18
    at Promise._execute (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\promise.js:79:10)
    at Client_MySQL._query (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\dialects\mysql\index.js:150:12)
    at Client_MySQL.query (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\client.js:211:17)
    at Runner.<anonymous> (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\runner.js:149:36)
    at Runner.tryCatcher (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\util.js:16:23)
    at Runner.query (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\method.js:15:34)
    at d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\runner.js:61:21
    at tryCatcher (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\util.js:16:23)
    at d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (d:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\promise.js:512:31)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  fatal: true }

```

**Comment by elhigu** [comment] 2018-02-02 06:13
How long did you example ran before throwing the error 15 minutes? is there any way to get local ClearDB installation to try that out? I did ran that test code against mariadb and mysql and I never got any errors.

**Comment by elhigu** [comment] 2018-02-02 06:15
since that try - catch help I suppose the error is thrown from the second query... not during waiting period like in the other thread.

**Comment by CNaismith** [comment] 2018-02-02 18:49
I only ran it for 15 minutes, and the error is thrown on the second select. ClearDB is just a MySQL as a service provider.

**Comment by CNaismith** [comment] 2018-02-02 22:05
So ClearDB finally got back to me about their connection timeout, and they say that connections are cut after 90 seconds (I am following up if this is from initial connection or idle).

**Comment by elhigu** [comment] 2018-02-03 13:27
I'll try that with short timeout running mysql in docker. I haven't been able to have this kind of errors when I have tested doing queries to connections closed by server.

**Comment by CNaismith** [comment] 2018-02-04 21:32
@elhigu if needed, I can set up a test cleardb database if that would help at all

**Comment by elhigu** [comment] 2018-02-05 07:05
have you tried mysql2 dialect instead? I should be able to reproduce that with mysql and just setup connection timeout smaller.

**Comment by CNaismith** [comment] 2018-02-05 13:43
I attempted to use the mysql2 dialect which did not resolve anything, but I can attempt again using the one file to see if it has any success. ClearDB had mentioned using a keep-alive ping that would keep the connections alive. However in my testing when I had done this, I used a setInterval for 5000 ms, which would do `knex.raw("SELECT 1");` and did not seem to help. Is there perhaps a better way of doing a 'keep alive'/ping with knex?

**Comment by yolopunk** [comment] 2018-02-06 03:09
I have the same question. Anybody know the reason?

**Comment by yolopunk** [comment] 2018-02-06 06:56
My situation:
* knex: 0.14.2
* MySQL: 5.7.21

wait_timeout is default (28800)

caught the bellow error 8 hours later:
```
at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
    --------------------
    at Protocol._enqueue (/home/node/code/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/home/node/code/node_modules/mysql/lib/Connection.js:208:25)
    at /home/node/code/node_modules/knex/lib/dialects/mysql/index.js:156:18
    at Promise._execute (/home/node/code/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/node/code/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/node/code/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/home/node/code/node_modules/knex/lib/dialects/mysql/index.js:150:12)
    at Client_MySQL.query (/home/node/code/node_modules/knex/lib/client.js:211:17)
    at Runner.<anonymous> (/home/node/code/node_modules/knex/lib/runner.js:149:36)
    at Runner.tryCatcher (/home/node/code/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/home/node/code/node_modules/bluebird/js/release/method.js:15:34)
    at /home/node/code/node_modules/knex/lib/runner.js:61:21
    at tryCatcher (/home/node/code/node_modules/bluebird/js/release/util.js:16:23)
    at /home/node/code/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/node/code/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/code/node_modules/bluebird/js/release/promise.js:512:31)
```

**Comment by elhigu** [comment] 2018-02-07 08:59
@CNaismith I'll try to setup stress test script which uses some proxy for closing connections.

**Comment by elhigu** [comment] 2018-02-10 20:18
`mysql` driver doesn't seem to crash when connections are closed by proxy, @CNaismith could you verify it with cleardb?

**Comment by elhigu** [comment] 2018-02-16 08:05
This should be fixed in 0.14.4, reopen and more testing if after that it still fails.

**Closed by elhigu** 2018-02-16 08:05 UTC

**Comment by CNaismith** [comment] 2018-02-20 18:02
@elhigu I am still able to get this with 0.14.4

**Comment by elhigu** [comment] 2018-02-21 11:34
@CNaismith I need to see some complete test code since I'm not able to reproduce the problem. I've tried killing connections everywhere in midway of communication between client and server.

I have tried killing connections gracefully from db side and killing forcefully at router layer and both mysql and mysql2 are running stable without leaking exceptions nor memory.

**Comment by elhigu** [comment] 2018-02-21 11:41
Can you show output of this code?

```
const knex = require('knex')({
    client: 'mysql',
    connection: {
        host: '',
        user: '',
        password: '',
        database: '',
        //debug: true,
        pool: {
            min: 2,
            max: 10
        }
    }
});

console.log(new Date());

const Bluebird = require('bluebird');
function periodOfTime () {
  return Bluebird.delay(1000 * 60 * 15);
}

async function main () {
  try {
    await knex.raw('select 1');
    await periodOfTime();
    await knex.raw('select 1');
  } catch (e) {
    console.log(e);
  }
}

main().then(() => {
  console.log('Main ended with success');
});

process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at:', p, 'reason:', reason);
});

process.on('uncaughtException', (err) => {
  console.log('Unhandled Exception!', err);
});

```

**Comment by CNaismith** [comment] 2018-02-21 14:26
```
2018-02-21T14:08:58.364Z
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
    --------------------
    at Protocol._enqueue (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Connection.query (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\mysql\lib\Connection.js:208:25)
    at D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\dialects\mysql\index.js:161:18
    at Promise._execute (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\promise.js:79:10)
    at Client_MySQL._query (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\dialects\mysql\index.js:155:12)
    at Client_MySQL.query (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\client.js:199:17)
    at Runner.<anonymous> (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\runner.js:149:36)
    at Runner.tryCatcher (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\util.js:16:23)
    at Runner.query (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\method.js:15:34)
    at D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\knex\lib\runner.js:61:21
    at tryCatcher (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Users\Chris-PC\Documents\Web Design\KnexSecondTest\node_modules\bluebird\js\release\promise.js:512:31)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  fatal: true }
Main ended with success`
```

**Comment by elhigu** [comment] 2018-02-21 14:54
I cannot reproduce that functionality. 

Maybe cleardb is cutting connection in a way that it actually does not cut TCP connection straight away, but cuts it when next time data is tried to be sent through connection after certain timeout.

Could you get more info about how they are cutting connection in router layer?

```
Mikaels-MacBook-Pro-2:knex mikaelle$ node scripts/stress-test/mysql-not-recognizing-connection-drop.js 
Knex:warning - Connection Error: Error: Connection lost: The server closed the connection.
Main ended with success

^C
Mikaels-MacBook-Pro-2:knex mikaelle$ 
```

```js
const toxiproxy = require('toxiproxy-node-client');
const toxicli = new toxiproxy.Toxiproxy('http://localhost:8474');
const rp = require('request-promise-native');
const Bluebird = require('bluebird');

const knex = require('../../lib')({
  client: 'mysql',
  connection: 'mysql://root:mysqlrootpassword@localhost:23306/?charset=utf8',
  pool: {
      min: 2,
      max: 10
  }
});

async function main () {
  await recreateProxy('mysql', 23306, 3306);
  try {
    await knex.raw('select 1');
    await Bluebird.delay(1000 * 1);
    await recreateProxy('mysql', 23306, 3306); // cut connection router level
    await Bluebird.delay(1000 * 1);
    await knex.raw('select 1');
  } catch (e) {
    console.log(e);
  }
}

main().then(() => {
  console.log('Main ended with success');
});

process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at:', p, 'reason:', reason);
});

process.on('uncaughtException', (err) => {
  console.log('Unhandled Exception!', err);
});


async function recreateProxy(serviceName, listenPort, proxyToPort) {
  try {
    await rp.delete({
      url: `${toxicli.host}/proxies/${serviceName}`
    });  
  } catch(err) {}

  const proxy = await toxicli.createProxy({
    name: serviceName,
    listen: `0.0.0.0:${listenPort}`,
    upstream: `${serviceName}:${proxyToPort}`
  });
}
```

**Comment by elhigu** [comment] 2018-02-21 15:00
If clear DB is not showing us any event about connection being closed until data is sent, in that case there is no way that we can recognize before actually doing the query unless we add option for pool validate connection to test connection by sending en extra `select 1;` query before deciding if connection is fine or not. That will cause lots of innecessary queries going on.

Maybe in your case you could set some pool timeout setting to discard idle connections before cleardb breaks them?

**Comment by elhigu** [comment] 2018-02-21 15:03
tarn.js pool has timeout option for this:

```
  // free resouces are destroyed after this many milliseconds
  idleTimeoutMillis: 30000,
```

Looks like that default value should have already thrown away your idle connection...

**Comment by elhigu** [comment] 2018-02-21 15:19
Yep... looks like you should never keep idle connections in pool with cleardb. So maybe it starts working if you set your pool min to be 0 so that all idle connections will be discarded after `idleTimeoutMillis`.

**Comment by ytejas1701** [comment] 2023-06-29 16:36
@Naismith , very late to this, but were you able to solve this issue? I couldn't find a proper solution anywhere.
