### ISSUE TITLE
Knex randomly produces invalid syntax.

### ISSUE THREAD

**Issue by ProjectInfinity** [tgriesser/knex#2050] opened 2017-05-08 20:06 UTC
Hi, I am experiencing a really weird issue where Knex suddenly started generating invalid syntax SOMETIMES. However upon closer inspection trying the SQL it claims it generated works without errors.

Here's the stacktrace:
https://pastebin.com/raw/ving5Zat

Knex has worked fine for me for a while, then suddenly started acting up so I tried switching from MySQL2 to MySQL driver. No changes. This is also very random and the only thing that changes for every query is the identifier in which I have checked for any incorrectness... and there isn't any.

There's a connection pool with 6 connections at most.

MariaDB version: 10.1.23-MariaDB-1~xenial
Node v7.9.0
Npm v4.2.0
Ubuntu 16.04.1 LTS

Let me know if there's something else you need.

**Comment by elhigu** [comment] 2017-05-08 21:37
Could you send the knex code, which generates that query shown in stack trace?

**Comment by ProjectInfinity** [comment] 2017-05-09 09:04
`this.knex.select(
            'votes.id',
            'votes.player',
            'votes.ip',
            'servers.is_active',
            'servers.secret',
            'sites.domain'
        ).from('votes')
            .join('servers', 'votes.server_id', 'servers.id')
            .join('sites', 'votes.site_id', 'sites.id')
            .where({
                'votes.checked': 0,
                'servers.is_active': 1,
                'servers.identifier': identity
            }).limit(100)`

Here's another stack trace it just produced: 
https://pastebin.com/raw/dkzH7CLc

I hoped it was 0.13.0 causing it because the issue seems less prevalent on 0.12.9 but I am afraid the issue occurs there as well.

**Comment by elhigu** [comment] 2017-05-09 09:41
That sounds really strange. Looks like somehow the sent sql string seems to be corrupted... what is sent to mysql driver is something like

```js
knex.select( 'votes.id', 'votes.player', 'votes.ip', 'servers.is_active', 'servers.secret', 'sites.domain' ).from('votes') .join('servers', 'votes.server_id', 'servers.id') .join('sites', 'votes.site_id', 'sites.id') .where({ 'votes.checked': 0, 'servers.is_active': 1, 'servers.identifier': 'IDENTITY' }).limit(100).toSQL();
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0, 1, 'IDENTITY', 100 ],
  __knexQueryUid: '31d37a44-caac-4b7c-8648-ae034bd8d4ef',
  sql: 'select `votes`.`id`, `votes`.`player`, `votes`.`ip`, `servers`.`is_active`, `servers`.`secret`, `sites`.`domain` from `votes` inner join `servers` on `votes`.`server_id` = `servers`.`id` inner join `sites` on `votes`.`site_id` = `sites`.`id` where `votes`.`checked` = ? and `servers`.`is_active` = ? and `servers`.`identifier` = ? limit ?' }
```

Could you try to make test example (single runnable file) how this could be reproduced for example directly with mysql driver? 

Also if you could test if this fails also with mysql or is this mariadb specific?

Other thing that could help to trace the problem would be to add some debug code to mysql dialect in node_modules/knex to see what is actually sent to driver to verify if the problem is in knex or in some other part in the setup.

**Comment by ProjectInfinity** [comment] 2017-05-09 20:06
> Could you try to make test example (single runnable file) how this could be reproduced for example directly with mysql driver?

What do you mean? I have no idea how to replicate the issue as it randomly occurs and works fine _most_ of the time... is there any point in me using the mysql client directly and running the query in a single runnable file?

> Also if you could test if this fails also with mysql or is this mariadb specific?

Moving between databases could be problematic and time consuming, is there any reason to suspect this when knex used to work 100% of the time using MariaDB and nothing in that regard was changed?

> Other thing that could help to trace the problem would be to add some debug code to mysql dialect in node_modules/knex to see what is actually sent to driver to verify if the problem is in knex or in some other part in the setup.

I'll try. I'll also try to capture the objects and dump them for later inspection if an error occurs.

**Comment by ProjectInfinity** [comment] 2017-05-09 20:13
Also take a look at this one:
https://pastebin.com/raw/QSh1wY6h

I've seen a couple of these too. They are mostly correct except I never wrote "serwezs", but instead "servers".... ?!

**Comment by wubzz** [comment] 2017-05-09 20:22
Can you post the surrounding code that causes the issue? We don't have too much to go on.

My guess is this is either on the driver level or the actual database server. It makes no sense to say that a new instance of the knex query builder _sometimes_ generates the wrong sql string provided the same parameters and build-calls. If that were the case, there would most likely be way more reports on the matter (especially from production apps) and "_sometimes_" broken unit tests. For example knex would never randomly rename 'servers' to 'serwezs'.

**Comment by elhigu** [comment] 2017-05-10 12:41
>> Could you try to make test example (single runnable file) how this could be reproduced for example directly with mysql driver?

> What do you mean? I have no idea how to replicate the issue as it randomly occurs and works fine most of the time... is there any point in me using the mysql client directly and running the query in a single runnable file?

Ok, I though you were able to reproduce this error. Unless there is a way to reproduce this it is pretty much impossible to be able to trace the root cause of the behaviour.

As @wubuzz mentioned there shouldn't be any reason why knex would build the same query differently. Do you have multiple environments where this happens? Is your server installed locally? Does this happen also with node 6? 

Could it be that the server has broken memory or some other hardware failure? Can you run memory tester on the server or is it virtualized?

>> Also if you could test if this fails also with mysql or is this mariadb specific?

> Moving between databases could be problematic and time consuming, is there any reason to suspect this when knex used to work 100% of the time using MariaDB and nothing in that regard was changed?

Nothing has changed in that regard. I thought that if it only would happen on mariadb, in that case there could be something strange difference in driver -> DB protocol (but I'm quite sure that is not  the case).

**Comment by ProjectInfinity** [comment] 2017-05-10 12:47
> Do you have multiple environments where this happens? Is your server installed locally? Does this happen also with node 6?

I only have one environment with node 7.9.0 which it has ran fine on for a while.

The server is not local, it is production... And the issue is so rare that we're talking about 1-2 queries per couple of 10k queries. But it's enough to be able to cause issues and make me get spammed with exception reports (which I want because other issues may occur).

Running a memory test could be difficult... It's a virtualized server over at Scaleway and I have created a brand new server that I restored from my snapshot and both servers have the very same problem.

**Comment by elhigu** [comment] 2017-05-10 13:04
I would rule out hardware failure too for now since they are virtual servers... maybe some networking error? 

Only thing I could think of for debugging this further is to check what is passed to msyql driver from the knex by adding debug prints what are the values for sql and bindings here: https://github.com/tgriesser/knex/blob/master/src/dialects/mysql/index.js#L110

It will at least rule out that knex is not causing those problems (and in the best case reveals bug in knex).

**Comment by ProjectInfinity** [comment] 2017-05-10 17:40
I managed to capture something but it was in the lib and not src folder.

I left the output intact so you can take a look, gonna have to regenerate the user's identity now but at the very least you should see the output. This time it's a invalid utf8 character?..

https://pastebin.com/raw/q5AcCkpn

**Comment by elhigu** [comment] 2017-05-10 21:16
According to your debug pastebin the query that was passed to mysql driver was correct. So looks like that problem is outside of `knex` and there is not much we can do to help.  

```
3|pocketvo | { sql: 'select `votes`.`id`, `votes`.`player`, `votes`.`ip`, `servers`.`is_active`, `servers`.`secret`, `sites`.`domain` from `votes` inner join `servers` on `votes`.`server_id` = `servers`.`id` inner join `sites` on `votes`.`site_id` = `sites`.`id` where `votes`.`checked` = ? and `servers`.`is_active` = ? and `servers`.`identifier` = ? limit ?' }
3|pocketvo | [ 0, 1, '45KMM4N26EGR', 100 ]
```

Now that you know that mysql driver is getting correct data in, maybe people in mysql driver's issues knows if someone has experienced something similar.

Those errors that has garbage in are the ones returned by the db server, so it is not related to `knex` either since `knex` just shows the error that server returned and in this case there are some utf8 garbage in.

Sorry for not being able to help with this more. Closing, since there are no signs that this problem is actually caused by `knex`.

First I would try to downgrade node to version 6 and start downgrading other npm packages to see if the problem vanishes that way.

**Closed by elhigu** 2017-05-10 21:16 UTC

**Comment by ProjectInfinity** [comment] 2017-05-21 01:33
An update for anyone who might experience something similar. I moved away from Scaleway due to a network latency issue between the server hosting MySQL and the one hosting the API, turns out there also was packet loss.

On my new host this has not been an issue anymore.
