### ISSUE TITLE
knex.raw strange behavior

### ISSUE THREAD

**Issue by gmarcz** [tgriesser/knex#2985] opened 2019-01-08 20:31 UTC
# Environment

Knex version: 0.14.6
Database + version: PostgreSQL 9.4
OS: macOS Majove 10.14.2

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

My knex config is very simple, I use it only to generate SQL

```
const knex = require('knex')({
  client: 'pg'
});
```

First case:

```
knex('resp').insert({
  respondent_data: knex.raw('{"query": "?mode=start"}'),
  respondent_id: '3B80OyXQlOX'
}).toString()
```

Result:

`insert into "resp" ("respondent_data", "respondent_id") values ({"query": "'3B80OyXQlOX'mode=start"}, ?)`

Second case:

```
knex('resp').insert({
  respondent_data: knex.raw('{"query": "?mode=start"}'),
  resp_id: '3B80OyXQlOX'
}).toString()
```

Result:

`insert into "resp" ("resp_id", "respondent_data") values ('3B80OyXQlOX', {"query": "?mode=start"})`

In the first case the question mark in the "respondent_data" value is replaced with the "respondent_id" column value, but in the second case when the column is renamed to "resp_id" it is not.

I think the second case is the right one, but maybe there is something what I don't know :) about the knex.raw function.

**Comment by fl0w** [comment] 2019-01-10 14:04
Sure, Knex parses question marks and binds values.
However, why do you use `knex.raw` anyway? Why not simply a regular string?

```js
knex('resp').insert({
  respondent_data: '{"query": "?mode=start"}',
  respondent_id: '3B80OyXQlOX'
}).toString()
```

**Comment by elhigu** [comment] 2019-01-10 14:58
Also `.toString` / `.toQuery`  methods are not really useful for even debugging. because they doesn't show what kind of data is sent to driver. You will get better info with .toSQL() which returns sql string and bindings separately.

**Comment by elhigu** [comment] 2019-01-10 15:00
Closing as doesn't look like a bug

**Closed by elhigu** 2019-01-10 15:00 UTC

**Comment by elhigu** [comment] 2019-01-10 18:40
that is kind of strange, because sorting update keys was fixed in 0.14.0... #2171 can you show output of toSQL() ? my best bet that .toString() messes them up somehow.

**Comment by gmarcz** [comment] 2019-01-10 19:37
Just tried with the latest knex version 0.16.3 got the same result.

**Comment by gmarcz** [comment] 2019-01-10 19:49
Maybe knex.raw() should escape questions marks automatically if someone is calling it without the bindings params to avoid this situation ?

**Comment by elhigu** [comment] 2019-01-10 23:03
Not a bug. You should not pass values with knex raw, but use bindings and in case when you do it anyways, question marks should be escaped to prevent treating them as bindings. Somewhere in the issues there is more discussion of improvements  how knex.raw should work in future...

That sorting inserted keys is maybe something knex should not do, but so far there has not been any reports it causing any problems so I wouldnt bother changing it.

**Comment by rkaw92** [comment] 2019-02-27 17:14
Hi, I'm also running into difficulties using `knex.raw` to assemble queries from parts. For me, the use case is constructing an `INSERT` query, and appending some modifiers (such as `ON CONFLICT ...`) to the end, which this library does not apparently support natively.

Example code:
```js
'use strict';

const query = `insert into "projections"."supportQuestions" ("ID", "texts") values ('36d98724-10a4-4001-adb9-0423dd2e74f6', '{"en":"Have you tried turning it off and on again?"}')`;
const knex = require('knex')({ client: 'pg', connection: 'postgres://postgres:postgres@127.0.0.1:5532/postgres' });

const raw = knex.raw(query + ' ON CONFLICT DO NOTHING');
raw.then(function() {
	console.log('query executed');
}, function(error) {
	console.error(error);
});
```
This relies on the (incorrect) assumption that `knex.raw` will accept and execute the output of `query.toString()` reliably. It's a very useful assumption, however, as it allows one to build arbitrary queries by enriching them with prefixes, suffixes (as shown above), etc.

Is there another solution that lets the developer do this, without writing the entire query themselves?

**Comment by rkaw92** [comment] 2019-02-28 12:31
Aha, I think I've found a clean way to do it:
```js
const query = knex.raw('insert into "projections"."supportQuestions" ("ID", "texts") values (?, ?)', [ '36d98724-10a4-4001-adb9-0423dd2e74f6', '{"en":"Have you tried turning it off and on again?"}' ]);
const queryDescriptor = query.toSQL();
const enrichedQuery = knex.raw(queryDescriptor.sql + ' ON CONFLICT DO NOTHING', queryDescriptor.bindings);
// enrichedQuery.then(...)
```

**Comment by elhigu** [comment] 2019-02-28 13:50
You can pass query builders directly as bindings like:

 knex.raw(’? on conflict do nothing’, [query])

**Comment by rkaw92** [comment] 2019-02-28 13:53
@elhigu This works, thanks. It's still a bit weird that a single `?` can get replaced by a complete query builder - I was under the impression that you would need `??` for this (since it's not a value).

**Comment by elhigu** [comment] 2019-02-28 14:56
Both ? and ?? should work all the same and both are unintuitive in my opinion (not identifier and not really a value either) 🙂

**Comment by rkaw92** [comment] 2019-02-28 15:22
Time for `???` I guess...
(Seriously though, is this `.raw()` behavior in the doc? Seems similar to `.wrap()`, too.)

**Comment by elhigu** [comment] 2019-02-28 16:00
Yeah. I dont see any reason why knex would need that wrap method anymore unless it keeps return value prosessing of the query builder intact (unlike normal query builders knex.raw returns unprocessed result from db driver) and docs might be missing info about binding query builders as value.
