### ISSUE TITLE
Cannot update identity column 'id' in mssql

### ISSUE THREAD

**Issue by basir** [tgriesser/knex#1580] opened 2016-07-16 16:47 UTC
In this line
https://github.com/tgriesser/knex/blob/master/src/dialects/mssql/query/compiler.js#L77
There is bug in update for identity primary key. It geneterated following error:
"update [events] set [created_at] = @p0, [description] = @p1, [id] = @p2, [name] = @p3, [updated_at] = @p4, [user_id] = @p5 where [id] = @p6;select @@rowcount - Cannot update identity column 'id'."

**Comment by tmcdonnell87** [comment] 2017-06-15 03:37
Quick read of the description makes it look to be a duplicate of https://github.com/tgriesser/bookshelf/issues/1259

**Comment by elhigu** [comment] 2017-06-26 16:49
@basir I suppose you are trying to set id column implicitly why that error is thrown. Please add steps to reproduce (if bookshelf issue, then this is wrong tracker).

**Closed by elhigu** 2017-06-26 16:49 UTC
