### ISSUE TITLE
Migrations happening out of order?

### ISSUE THREAD

**Issue by nathasm** [tgriesser/knex#635] opened 2015-01-20 18:58 UTC
I have 3 migrations, the first sets up static reference tables, the second setups up a user/company, and the third sets up foreign keys. For some reason, the 1st and 3rd migrations are happening (from what I can tell from the debug logs) before the 2nd migration:

Configuration for knex looks like: 

    test: {
      debug: true,
      client: 'mysql',
      connection: {
      },
      migrations: {
        tableName: 'knex_migrations',
        directory: '../db/migrations'
      },
      seeds: {
        directory: '../db/seeds'
      },
      pool: {
        max: 1
      }
    }

Migration files:

    # 20150114051223_create_static.js    
    exports.up = function(knex, Promise) {
      return knex.transaction(function(trx) {
        return trx.schema.createTable('ages', function(t) {
          t.increments('id').primary();
          t.string('name').unique().notNull();
        }).createTable('demographics', function(t) {
          t.increments('id').primary();
          t.string('name').unique().notNull();
        }).createTable('email_list_sizes', function(t) {
          t.increments('id').primary();
          t.string('name').unique().notNull();
        });
      });
    };
    
    exports.down = function(knex, Promise) {
      return knex.schema
      .dropTable('ages')
      .dropTable('demographics')
      .dropTable('email_list_sizes');
    };

    #20150114051636_users_companies.js
    exports.up = function(knex, Promise) {
      return knex.transaction(function(trx) {
        return trx.schema.createTable('users', function(t) {

          t.increments('id').primary();
          t.string('username').unique().notNull();
          t.string('email').unique().notNull();
          t.string('password').notNull();

          t.timestamps();

        }).createTable('companies', function(t) {

          t.increments('id').primary();
          t.string('name').unique().notNull();
          t.timestamps();
        });
      });
    };

    exports.down = function(knex, Promise) {
      return knex.schema.dropTable('companies').dropTable('users');
    };

    #20150117235632_user_company_fk.js
    exports.up = function(knex, Promise) {
      return knex.transaction(function(trx) {
        return trx.schema.table('companies', function(t) {

          t.integer('user_id').unsigned().references('id').inTable('users');
          t.integer('demographics_id').unsigned().references('id').inTable('demographics');
          t.integer('ages_id').unsigned().references('id').inTable('ages');
          t.integer('email_list_sizes_id').unsigned().references('id').inTable('email_list_sizes');
        });
      });
    };

    exports.down = function(knex, Promise) {

    };

And the logs from the migration:

<pre>
web_1 | { __cid: '__cid1',
web_1 |   sql: 'select * from information_schema.tables where table_schema = ? and table_name = ?',
web_1 |   output: [Function],
web_1 |   bindings: [ 'test', 'knex_migrations' ] }
web_1 | { __cid: '__cid1',
web_1 |   method: 'select',
web_1 |   options: undefined,
web_1 |   bindings: [],
web_1 |   sql: 'select `name` from `knex_migrations` order by `id` asc' }
web_1 | { __cid: '__cid1',
web_1 |   method: 'select',
web_1 |   options: undefined,
web_1 |   bindings: [],
web_1 |   sql: 'select max(`batch`) as `batchNo` from `knex_migrations`' }
web_1 | { __cid: '__cid1', sql: 'begin;' }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'create table `ages` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null) default character set utf8',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'alter table `ages` add unique ages_name_unique(`name`)',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'create table `demographics` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null) default character set utf8',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'alter table `demographics` add unique demographics_name_unique(`name`)',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'create table `email_list_sizes` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null) default character set utf8',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'alter table `email_list_sizes` add unique email_list_sizes_name_unique(`name`)',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1', sql: 'commit;' }
web_1 | { __cid: '__cid1',
web_1 |   method: 'insert',
web_1 |   options: undefined,
web_1 |   bindings:
web_1 |    [ 2,
web_1 |      Tue Jan 20 2015 18:55:30 GMT+0000 (UTC),
web_1 |      '20150114051223_create_static.js' ],
web_1 |   sql: 'insert into `knex_migrations` (`batch`, `migration_time`, `name`) values (?, ?, ?)' }
web_1 | { __cid: '__cid1', sql: 'begin;' }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'alter table `companies` add `user_id` int unsigned, add `demographics_id` int unsigned, add `ages_id` int unsigned, add `email_list_sizes_id` int unsigned',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1', sql: 'rollback;' }
web_1 | Possibly unhandled Error: ER_NO_SUCH_TABLE: Table 'test.companies' doesn't exist
web_1 |     at Query.Sequence._packetToError (/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
web_1 |     at Query.ErrorPacket (/src/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
web_1 |     at Protocol._parsePacket (/src/node_modules/mysql/lib/protocol/Protocol.js:271:23)
web_1 |     at Parser.write (/src/node_modules/mysql/lib/protocol/Parser.js:77:12)
web_1 |     at Protocol.write (/src/node_modules/mysql/lib/protocol/Protocol.js:39:16)
web_1 |     at Socket.<anonymous> (/src/node_modules/mysql/lib/Connection.js:82:28)
web_1 |     at Socket.emit (events.js:95:17)
web_1 |     at Socket.<anonymous> (_stream_readable.js:765:14)
web_1 |     at Socket.emit (events.js:92:17)
web_1 |     at emitReadable_ (_stream_readable.js:427:10)
web_1 |     at emitReadable (_stream_readable.js:423:5)
web_1 |     at readableAddChunk (_stream_readable.js:166:9)
web_1 |     at Socket.Readable.push (_stream_readable.js:128:10)
web_1 |     at TCP.onread (net.js:529:21)
web_1 |     --------------------
web_1 |     at Protocol._enqueue (/src/node_modules/mysql/lib/protocol/Protocol.js:135:48)
web_1 |     at Connection.query (/src/node_modules/mysql/lib/Connection.js:185:25)
web_1 |     at /src/node_modules/knex/lib/dialects/mysql/runner.js:42:16
web_1 |     at tryCatcher (/src/node_modules/bluebird/js/main/util.js:24:31)
web_1 |     at Promise._resolveFromResolver (/src/node_modules/bluebird/js/main/promise.js:559:31)
web_1 |     at new Promise (/src/node_modules/bluebird/js/main/promise.js:59:37)
web_1 |     at Runner_MySQL.<anonymous> (/src/node_modules/knex/lib/dialects/mysql/runner.js:41:10)
web_1 |     at Runner_MySQL.tryCatcher (/src/node_modules/bluebird/js/main/util.js:24:31)
web_1 |     at Runner_MySQL._query (/src/node_modules/bluebird/js/main/promise.js:185:34)
web_1 |     at Runner_MySQL.<anonymous> (/src/node_modules/knex/lib/runner.js:125:15)
web_1 |     at Runner_MySQL.tryCatcher (/src/node_modules/bluebird/js/main/util.js:24:31)
web_1 |     at Runner_MySQL.query (/src/node_modules/bluebird/js/main/promise.js:185:34)
web_1 |     at Runner_MySQL.<anonymous> (/src/node_modules/knex/lib/runner.js:134:19)
web_1 |     at Runner_MySQL.tryCatcher (/src/node_modules/bluebird/js/main/util.js:24:31)
web_1 |     at ReductionPromiseArray._promiseFulfilled (/src/node_modules/bluebird/js/main/reduce.js:121:18)
web_1 |     at ReductionPromiseArray.init [as _init$] (/src/node_modules/bluebird/js/main/promise_array.js:94:18)
web_1 |     at Promise._settlePromiseAt (/src/node_modules/bluebird/js/main/promise.js:741:21)
web_1 |     at Promise._settlePromises (/src/node_modules/bluebird/js/main/promise.js:861:14)
web_1 |     at Async._drainQueue (/src/node_modules/bluebird/js/main/async.js:79:16)
web_1 |     at Async._drainQueues (/src/node_modules/bluebird/js/main/async.js:89:10)
web_1 |     at Async.drainQueues (/src/node_modules/bluebird/js/main/async.js:14:14)
web_1 |     at process._tickCallback (node.js:442:13)
web_1 |       1) "before all" hook
web_1 | { __cid: '__cid1',
web_1 |   sql: 'select * from information_schema.tables where table_schema = ? and table_name = ?',
web_1 |   output: [Function],
web_1 |   bindings: [ 'test', 'knex_migrations' ] }
web_1 | { __cid: '__cid1',
web_1 |   method: 'select',
web_1 |   options: undefined,
web_1 |   bindings: [],
web_1 |   sql: 'select `name` from `knex_migrations` order by `id` asc' }
web_1 | { __cid: '__cid1',
web_1 |   method: 'select',
web_1 |   options: undefined,
web_1 |   bindings: [],
web_1 |   sql: 'select * from `knex_migrations` where `batch` = (select MAX(batch) from `knex_migrations`) order by `id` desc' }
web_1 | { __cid: '__cid1',
web_1 |   method: 'select',
web_1 |   options: undefined,
web_1 |   bindings: [],
web_1 |   sql: 'select max(`batch`) as `batchNo` from `knex_migrations`' }
web_1 | { __cid: '__cid1', sql: 'drop table `ages`', bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'drop table `demographics`',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   sql: 'drop table `email_list_sizes`',
web_1 |   bindings: [] }
web_1 | { __cid: '__cid1',
web_1 |   method: 'del',
web_1 |   options: undefined,
web_1 |   bindings: [ '20150114051223_create_static.js' ],
web_1 |   sql: 'delete from `knex_migrations` where `name` = ?' }
</pre>

**Comment by bendrucker** [comment] 2015-01-20 20:22
That's very odd. Can you extract just this code into a repo that I can clone and then call `npm i && npm test` to run?

**Comment by nathasm** [comment] 2015-01-21 03:52
https://github.com/nathasm/knex_migration

To run:
    fig build; fig up

To make matters more interesting, this will fail on my Ubuntu 14.04 LTS machine, but when running via boot2docker on my OSX box, everything passes as expected.

**Comment by bendrucker** [comment] 2015-01-21 13:02
Please pull out everything that's not related to the problem, including Docker, gulp, etc. It's way easier for me to look if there's nothing in the way. Plus I don't want to go spend time installing the Docker deps.

**Comment by nathasm** [comment] 2015-01-21 13:33
You don't need to use Docker/Fig, I just put those there for the mysql connection. All relevant pieces are in test/server for the tests that do the migration and server/db/migrations where the migrations are actually stored.

But everything should be cleaned up now.

**Comment by bendrucker** [comment] 2015-01-21 16:18
This is still not set up right. The paths are wrong and you're calling the seed API for things that don't exist.

**Comment by nathasm** [comment] 2015-01-22 00:10
Sorry about that. I believe everything is set up properly now

**Comment by bendrucker** [comment] 2015-01-22 02:32
Cool. Just ran this locally without any issues. On OS X. Any other ideas?

**Comment by zcei** [comment] 2015-01-23 14:10
In the logs, just before the error occurs:
``` sql: 'insert into `knex_migrations` (`batch`, `migration_time`, `name`) values (?, ?, ?)' ```
Isn't the log statement intended to be the actual run query? (I do know that question marks get replaced by values)

Apart from this: as I learned in my PR there is no need to wrap it in a transaction, as schema building gets committed implicit.
Maybe it's some quirks with MySQL & transactions (and even OS dependent versions) that causes it?

I'm also on OS X, thus no point in investigating :(

Just my two cents..

**Comment by bendrucker** [comment] 2015-01-23 14:25
No, you'll see the query statements and the bindings in the log. That's expected.

And yeah, that's a good idea to pull the transactions out. Of course the ideal fix is to switch to Postgres! :stuck_out_tongue: 

Would love to hear what's up here if you can figure it out. If you are able to pin this on Knex in the environment where you can reproduce it, happy to reopen.

**Closed by bendrucker** 2015-01-23 14:25 UTC
