### ISSUE TITLE
SQLite - query not working as expected

### ISSUE THREAD

**Issue by DanrwAU** [tgriesser/knex#2984] opened 2019-01-06 06:58 UTC
# Environment

Knex version: latest
Database + version: sqlite
OS: Windows

# Bug

Query not working with Knex - works fine when run as a query directly on the sqlite database.

Original Query
`UPDATE messages SET alias_id = (SELECT id FROM capcodes WHERE messages.address LIKE address ORDER BY REPLACE(address, '_', '%') DESC LIMIT 1)`

Knex Code
```
db('messages').update('alias_id', function() {
    this.select('id')
        .from('capcodes')
        .where('address', 'like', 'messages.address')
        .orderByRaw("REPLACE(address, '_', '%') DESC LIMIT 1")
  })
```

Knex output
```
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'messages.address' ],
  __knexQueryUid: 'cfae967e-c0c2-4b4c-b1c4-8e43c3532a06',
  sql:
   'update `messages` set `alias_id` = (select `id` from `capcodes` where `address` like ? order by REPLACE(address, \'_\', \'%\') DESC LIMIT 1)' }
```

It's currently setting every alias_id to NULL.
Pasting the SQL from the Knex debugging into sqlite and remove the escaping around the single quotes works correctly.

I'm 50/50 this is something i'm doing wrong, but can't figure it out.

**Comment by elhigu** [comment] 2019-01-06 23:39
Generated query looks the way it should look with given query builder. Closing as not a bug. Stackoverflow should be used for knex usage support. 

ps. maybe this do what you were trying to do:

```
db('messages').update('alias_id', function() {
    this.select('id')
        .from('capcodes')
        .where('address', 'like', knex.ref('messages.address'))
        .orderByRaw("REPLACE(address, '_', '%') DESC LIMIT 1")
  })
```

**Closed by elhigu** 2019-01-06 23:39 UTC
