### ISSUE TITLE
Anyway to forward the logging to other loggers such as bunyan ?

### ISSUE THREAD

**Issue by nixgadget** [tgriesser/knex#1495] opened 2016-06-14 10:07 UTC
Im not sure if this question was asked here before but i cannot see any information regarding ?
Can you provide a mechanism to forward the warnings/errors to another logger such as bunyan ?

For instance I'm particularly interested in errors such as,

`Knex:Error Pool2 - Error: ORA-12154: TNS:could not resolve the connect identifier specified`

I see that internally it uses `console.log` but this may not be ideal when using production monitoring such as Splunk.

**Comment by rhys-vdw** [comment] 2016-06-14 11:45
Duplicate of #1483. I'm going to respond there in more detail.

**Closed by rhys-vdw** 2016-06-14 11:45 UTC
Labels: duplicate, question
