### ISSUE TITLE
Still seeing generic-pool errors in 0.14.4

### ISSUE THREAD

**Issue by GeekyDeaks** [tgriesser/knex#2522] opened 2018-03-01 16:09 UTC
# Environment

Knex version: 0.14.4
Database + version: MSSQL (Azure)
OS: Windows (Azure Web App)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Seeing errors from `generic-pool`, even though it was dropped for `tarn`

2. Error message
```
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (D:\home\site\wwwroot\node_modules\generic-pool\lib\ResourceRequest.js:62:17)
    at Timeout.bound (D:\home\site\wwwroot\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

To explain, I recently updated to 0.14.4 from 0.14.2 due to the above error intermittently appearing on production causing the app to become unstable and require a restart.  0.14.4's move to `tarn` appeared to fix the problem, but actually made the above error significantly less likely to occur and it now seems to take around 20 hours to trigger instead of failing after ~90 minutes.

I think I have an idea what might be going on.

In `knex/src/dialect/mssql/index.js` we have the following:

```
  // Get a raw connection, called by the `pool` whenever a new
  // connection needs to be added to the pool.
  acquireRawConnection() {
    return new Promise((resolver, rejecter) => {
      const connection = new this.driver.ConnectionPool(this.connectionSettings);
      connection.connect((err) => {
```
So it's still getting a connection pool from the mssql driver.  Unfortunately, mssql appears to make a pool of size 10 by default:

in: `mssql/lib/base.js`:
```
    // prepare pool
    this.pool = gp.createPool({
        create: this._poolCreate.bind(this),
        validate: this._poolValidate.bind(this),
        destroy: this._poolDestroy.bind(this)
    }, Object.assign({
        max: 10,
        min: 0,
```
This kinda explains why it's taking longer to trigger for me.  As an attempt at a workaround, I have tried setting the pool parameters in the connection:
```
connection: {
    pool: {
        min: 0,
        max: 1
    },
    host : 'acme.database.windows.net',
    ...
}
```
This is a complete shot in the dark though.  Any ideas how to turn pooling off in mssql?  Even the `connect()` method seems to return a pool.

@Grimace1975

**Comment by elhigu** [comment] 2018-03-01 16:37
Mssql driver is internally using generic-pool there are some problems. I'm working on this and also setting pool size min:1, max:1. If it looks like mssql driver is not fixed we might need to change to use driectly tedious driver.

**Comment by GeekyDeaks** [comment] 2018-03-01 16:59
thanks @elhigu, can I help with anything? I'm still getting up to speed with knex, but if there is anything that's just tedious busy work (pun intended), I am happy to try and help.

**Comment by elhigu** [comment] 2018-03-04 14:03
@GeekyDeaks thanks for the offer, but for this particular issue there is not much that you could do, unless you are able to track down why tedious is not throwing `connect` event in some weird edge cases :)

**Comment by elhigu** [comment] 2018-03-04 21:04
I just finished PR for fixing mssql driver, now I still need to check if I can write workaround for that in knex, while it has not been merged / released https://github.com/tediousjs/node-mssql/pull/614

Also I will setup default values for mssql's internal pool to have 1 and only 1 connection available.

**Comment by mrparkers** [comment] 2018-06-29 14:05
Hi @elhigu, I am also getting generic-pool errors in one of my projects that uses mssql and I'm looking for a solution that doesn't involve replacing Knex with something else.

Was any progress made on this issue via #2637?  If not, is there anything you need help with?  I'd much rather spend my time fixing the root cause in Knex instead of removing it from my project.

As far as workarounds go, do you think it would be reasonable (at least for now) to just restart my app if I encounter any errors that were thrown by generic-pool?

**Comment by elhigu** [comment] 2018-06-30 00:07
Try if 0.15 version works better. I tried to fix bunch of mssql problems in that. It will be released on next sunday I hope 🤞

**Closed** 2018-06-30 00:08 UTC
