### ISSUE TITLE
Drop-and-recreate migration scripts do not work correctly with async/await

### ISSUE THREAD

**Issue by igor-savin-ht** [tgriesser/knex#2581] opened 2018-04-26 12:30 UTC
# Environment

Knex 0.14.6
PostgreSQL 10.1

# Bug

If migration script relies on async/await to wait for a column to be dropped before being created again, "column already exists" error is thrown. Same code works fine if .then block is used instead.

Code example:

```
exports.up = async (knex) => {
    await knex.schema.withSchema(`${SCHEMA}`).table('users', function (table) {
        table.dropColumn('officeId');
    });

    await knex.schema.withSchema(`${SCHEMA}`).table('users', function (table) {
        table.string('officeId', 255);
    });
};
```

**Comment by igor-savin-ht** [comment] 2018-04-27 11:35
@elhigu Yup, that works just fine.

**Comment by elhigu** [comment] 2019-03-03 19:36
That is really weird and doesn't make sense at all... if someone likes to write test case and figure out what is going on please do.

**Comment by kibertoad** [comment] 2019-03-05 00:04
Closing as cannot reproduce anymore. Added tests that are not failing in master.

**Closed by kibertoad** 2019-03-05 00:04 UTC
Labels: bug, good first issue, help wanted

**Comment by laurent22** [comment] 2021-07-03 08:55
Happened to me too with this kind of migration:

```typescript
export async function up(db: DbConnection): Promise<any> {
	await db.schema.alterTable('users', function(table: Knex.CreateTableBuilder) {
		table.dropColumn('max_item_size');
		table.dropColumn('can_share_folder');
		table.dropColumn('can_share_note');
	});

	await db.schema.alterTable('users', function(table: Knex.CreateTableBuilder) {
		table.integer('max_item_size').defaultTo(null).nullable();
		table.specificType('can_share_folder', 'smallint').defaultTo(null).nullable();
		table.specificType('can_share_note', 'smallint').defaultTo(null).nullable();
		table.bigInteger('max_total_item_size').defaultTo(null).nullable();
	});
}
```

My fix was to split it into two migrations, although it would be nice if it could be done without hack.

**Comment by laurent22** [comment] 2021-07-03 09:01
Additionally, this doesn't work either:

```typescript
await db.schema.alterTable('users', function(table: Knex.CreateTableBuilder) {
	table.dropColumn('max_item_size');
	table.dropColumn('can_share_folder');
	table.dropColumn('can_share_note');

	table.integer('max_item_size').defaultTo(null).nullable();
	table.specificType('can_share_folder', 'smallint').defaultTo(null).nullable();
	table.specificType('can_share_note', 'smallint').defaultTo(null).nullable();
	table.bigInteger('max_total_item_size').defaultTo(null).nullable();
});
```

**Comment by elhigu** [comment] 2021-07-17 20:35
@laurent22 your problem is not the same that in original post, but something else: https://runkit.com/embed/aj7p07d29vz0 

It clearly looks like a bug though, so please open a separate bug report for that.
