### ISSUE TITLE
Query Chaining 

### ISSUE THREAD

**Issue by bfletcherbiggs** [tgriesser/knex#2005] opened 2017-04-12 00:58 UTC
Trying to chain some queries but I'm have some async issues. I need the use the result of the previous queries to perform 4 joins. Sometimes the result is as expected but other times the call finishes before all of the data is collected. Here is one of my recent attempts - this is all within a function that get's called to do a final fetch of my updated dated.

Any tips would be appreciated.

```js

return db.with('stuff', result => {
    result.from('purchases')
    .where('user_id',userId)
    .andWhere('purchases.id',purchase_id)
    .whereIn('goals.id', goalIDs)
    .join('goals','purchases.id','goals.purchase_id')
    .orderBy('goals.purchase_id')
    .select('status','purchases.updated_at','url','name','goals.purchase_id','quantity','task','quantity_complete','goals.id as goal_id','user_id')
    })
    .with('stuff2', result2 => {
    result2.from('stuff')
    .leftOuterJoin('purchase_groups', function() {
      this.on('stuff.purchase_id', '=','purchase_groups.purchase_id')
     })
    .select('purchase_groups.group_id as purchase_group_id','status','updated_at','url','name','stuff.purchase_id','quantity','task','quantity_complete','goal_id','stuff.user_id')
    })
    .with('stuff3', result3 => {
    result3.from('stuff2')
    .leftOuterJoin('usergroups', function() {
        this.on('stuff2.purchase_group_id', '=', 'usergroups.id')
    })
    .select('title as purchase_group_name','purchase_group_id','status','updated_at','url','name','stuff2.purchase_id','quantity','task','quantity_complete','stuff2.goal_id','stuff2.user_id')
    })
    .with('stuff4', result4 =>{
    result4.from('stuff3')
    .leftOuterJoin('goal_groups', function() {
        this.on('stuff3.goal_id', '=', 'goal_groups.goal_id')
    })
    .select('goal_groups.group_id as goal_group_id','purchase_group_id','status','updated_at','url','name','stuff3.purchase_id','quantity','task','quantity_complete','stuff3.goal_id','stuff3.user_id','purchase_group_name')
    })
    .with('stuff5',result5 =>{
    result5.from('stuff4')
    .leftOuterJoin('usergroups', function() {
      this.on('stuff4.goal_group_id', '=', 'usergroups.id')
    })
    .select('title as goal_group_name','goal_group_id','purchase_group_id','status','updated_at','url','name','purchase_id','quantity','task','quantity_complete','stuff4.goal_id', 'purchase_group_name','stuff4.user_id')
    })
    
```

**Comment by elhigu** [comment] 2017-04-12 08:03
Query you have written should be single query sent to the DB without any async issues. Check what kind of query it outputs with `.toSQL()`.

**Comment by bfletcherbiggs** [comment] 2017-04-12 14:31
Just so I understand - is your snippet functioning differently than mine with the 'with' grouping?  I was able to write it all using knew.raw but it still required a setTimeout function to not return an empty response, which is why I assumed it was an async issue.

**Comment by bfletcherbiggs** [comment] 2017-04-12 14:40
```
return db.raw(
        WITH pgsort AS(
        	SELECT purchases.status
        ,purchases.updated_at,purchases.url,purchases.name,goals.purchase_id,goals.quantity,goals.task,goals.quantity_complete,goals.id as goal_id,purchases.user_id
        	FROM purchases
        	JOIN goals ON goals.purchase_id=purchases.id
        	WHERE purchases.id=${purchase_id}
        ),pggroups AS (
        	SELECT pgsort.status,pgsort.updated_at,pgsort.url,pgsort.name,pgsort.purchase_id,pgsort.quantity,pgsort.task,pgsort.quantity_complete,pgsort.goal_id,pgsort.user_id,purchase_groups.group_id as purchase_group_id
        	FROM pgsort
        	JOIN purchase_groups ON pgsort.purchase_id=purchase_groups.purchase_id
        ),pggtitle AS(
        	SELECT pggroups.status,pggroups.updated_at,pggroups.url,pggroups.name,pggroups.purchase_id,pggroups.quantity,pggroups.task,pggroups.quantity_complete,pggroups.goal_id,pggroups.user_id,pggroups.purchase_group_id, usergroups.title as purchase_group_name
        	FROM pggroups
        	JOIN usergroups ON pggroups.purchase_group_id = usergroups.id
        ),gggroups AS (
        	SELECT pggtitle.status,pggtitle.updated_at,pggtitle.url,pggtitle.name,pggtitle.purchase_id,pggtitle.quantity,pggtitle.task,pggtitle.quantity_complete,pggtitle.goal_id,pggtitle.user_id,pggtitle.purchase_group_id, pggtitle.purchase_group_name,goal_groups.group_id as goal_group_id
        	FROM pggtitle
        	JOIN goal_groups ON goal_groups.goal_id = pggtitle.goal_id
        ),ggtitle AS(
        	SELECT gggroups.status,gggroups.updated_at,gggroups.url,gggroups.name,gggroups.purchase_id,gggroups.quantity,gggroups.task,gggroups.quantity_complete,gggroups.goal_id,gggroups.user_id,gggroups.purchase_group_id, gggroups.purchase_group_name,gggroups.goal_group_id,usergroups.title as goal_group_name
        	FROM gggroups
        	JOIN usergroups ON usergroups.id = gggroups.goal_group_id
        )
        SELECT *
        FROM ggtitle;
        
```  @elhigu

**Comment by elhigu** [comment] 2017-04-12 14:49
I just copied your query, and checked what was the query it outputted. 

You problem is most probably elsewhere in your code. Try to create minimal test case which allows you to reproduce your problem.

I'm closing this issue, since this doesn't seem to be knex bug, but just an user error. Usually user problems should be asked in stackoverflow.

**Closed by elhigu** 2017-04-12 14:49 UTC

**Comment by bfletcherbiggs** [comment] 2017-04-12 15:09
If I just do a simple Get Call with this query with no other functions - it will come up with an empty array unless I use a setTimeout
@elhigu

**Comment by elhigu** [comment] 2017-04-12 15:26
@bfletcherbiggs please send here an example code (one file) to reproduce the problem...

**Comment by bfletcherbiggs** [comment] 2017-04-12 15:47
Here you go - not sure if you need more, but that's all the context of the function call.
[knexRawExample.js.zip](https://github.com/tgriesser/knex/files/917114/knexRawExample.js.zip)

**Comment by elhigu** [comment] 2017-04-13 08:33
yeah I cannot run that... its not even initializing knex and doesn't show the real place where the error in the code is. Complete test case should be runnable code, which creates table and inserts test data etc. anything that is required to really reproduce your specific problem.

Looking your code my best guess is that you are not waiting that query which initializes your DB is not completed and you try to query DB too early. There is no reason why that setTimeout is necessary.

**Comment by bfletcherbiggs** [comment] 2017-04-14 16:01
I was able to solve it with a promise resolution

`return new Promise(resolve =>
            db.raw(
            `WITH pgsort AS(
            	SELECT purchases.status
            ,purchases.updated_at,purchases.url,purchases.name,goals.purchase_id,goals.quantity,goals.task,goals.quantity_complete,goals.id as goal_id,purchases.user_id
            	FROM purchases
            	JOIN goals ON goals.purchase_id=purchases.id
            	WHERE purchases.id=${purchase_id}
            ),pggroups AS (
            	SELECT pgsort.status,pgsort.updated_at,pgsort.url,pgsort.name,pgsort.purchase_id,pgsort.quantity,pgsort.task,pgsort.quantity_complete,pgsort.goal_id,pgsort.user_id,purchase_groups.group_id as purchase_group_id
            	FROM pgsort
            	JOIN purchase_groups ON pgsort.purchase_id=purchase_groups.purchase_id
            ),pggtitle AS(
            	SELECT pggroups.status,pggroups.updated_at,pggroups.url,pggroups.name,pggroups.purchase_id,pggroups.quantity,pggroups.task,pggroups.quantity_complete,pggroups.goal_id,pggroups.user_id,pggroups.purchase_group_id, usergroups.title as purchase_group_name
            	FROM pggroups
            	JOIN usergroups ON pggroups.purchase_group_id = usergroups.id
            ),gggroups AS (
            	SELECT pggtitle.status,pggtitle.updated_at,pggtitle.url,pggtitle.name,pggtitle.purchase_id,pggtitle.quantity,pggtitle.task,pggtitle.quantity_complete,pggtitle.goal_id,pggtitle.user_id,pggtitle.purchase_group_id, pggtitle.purchase_group_name,goal_groups.group_id as goal_group_id
            	FROM pggtitle
            	JOIN goal_groups ON goal_groups.goal_id = pggtitle.goal_id
            ),ggtitle AS(
            	SELECT gggroups.status,gggroups.updated_at,gggroups.url,gggroups.name,gggroups.purchase_id,gggroups.quantity,gggroups.task,gggroups.quantity_complete,gggroups.goal_id,gggroups.user_id,gggroups.purchase_group_id, gggroups.purchase_group_name,gggroups.goal_group_id,usergroups.title as goal_group_name
            	FROM gggroups
            	JOIN usergroups ON usergroups.id = gggroups.goal_group_id
            )
            SELECT *
            FROM ggtitle;
            `
        ).then(response => resolve(response))
    )`

**Comment by elhigu** [comment] 2017-04-14 16:15
That code is equivalent with return db.raw(...) except new promise wrapping causes rejections to be ignored.

**Comment by bfletcherbiggs** [comment] 2017-04-14 20:28
Whatever the case - without the promise I couldn't get the query to work.  Typing in the raw SQL works great in Postico so I don't think it's a query issue.  Without the promise - I get an empty array. @elhigu

**Comment by elhigu** [comment] 2017-04-15 10:30
I don't believe it is the query either. Anyhow having to build up workarounds as you have added above means that you are doing something wrong in your knex code.

No one can help you to track out what it is because you are not providing runnable example code how anyone can reproduce the problem you are experiencing.
