### ISSUE TITLE
when passing empty list in `.whereIn()`

### ISSUE THREAD

**Issue by HurSungYun** [tgriesser/knex#2897] opened 2018-11-08 09:00 UTC
# Environment

Knex version: 0.15.0
Database + version: mysql 5.7
OS: mac OS X

# Bug

I tried this
```
slots_db.client('table')
  .select()
  .where({ 'name': 'a' })
  .whereIn('release', []);
```

expected
```
select * from `table` where `name` = ?
```

but actually
```
select * from `table` where `name` = ? and 1 = ?
```

I believe it should be either the first one or throwing error.

I'd like to work on this issue.

**Comment by wubzz** [comment] 2018-11-08 09:11
Honestly I think its perfectly fine the way it is. When calling `.whereIn` you are expecting to return rows based on specific criteria, in this case a list of values. If that list happens to be empty, we shouldn't ignore the fact that it was still a criteria for the query to begin with. Right now knex solves this by doing a `1 = 0` query returning no rows at all.

To me this is the same as saying an undefined value in `.where({column: undefined})` should ignore the `column` criteria in the where clause, which feels very dangerous, especially in dynamic situations. Maybe a bad example since this throws `Undefined Bindings` error, but the point is the same.

**Comment by HurSungYun** [comment] 2018-11-08 09:17
@wubzz I agree with your point.

thanks for your explanation in detail :)

**Comment by HurSungYun** [comment] 2018-11-08 09:29
I think that throwing error can be a better solution for this situation.

In my use case, it makes business logic broken when ignoring empty list and returning nothing.

I believe it can be safer when knex throws an error. Users can realize their bugs more quickly, if we throw errors.

How do you think about it? @wubzz

**Comment by wubzz** [comment] 2018-11-08 13:01
I still think its wrong to throw an error. You could just simply do this:

```
const releaseIds = [];
const builder = slots_db.client('table')
  .select()
  .where({ 'name': 'a' });

if(releaseIds.length) {
 builder.whereIn('release', releaseIds);
}
```

Most use-cases consist around argument to `whereIn` being a dynamically populated array, which may very well be an empty array sometimes. Changing this to throw an error is not only a breaking change, but also a hazzle in practise. Doing so would result in __always__ having to do the example above unless your list of IDs is always __static__.

This is just my personal opinion, maybe better to get some more input.

@elhigu @tgriesser @kibertoad

**Comment by kibertoad** [comment] 2018-11-08 13:05
@wubzz I wouldn't call it a breaking change since current behaviour doesn't seem to be documented, and I don't think it's the one that most users would expect. 
Can you imagine a real-world use-case when you would actually prefer query to return nothing when some filtering criteria is empty?
I agree with @HurSungYun here, if we don't want to surprise users, it makes sense to require them to be more explicit in their intention instead of silently returning data that is different from what most users would expect.

**Comment by wubzz** [comment] 2018-11-08 14:59
@kibertoad If we're evaluating breaking changes as something that must exist in documentation then I guess we are free to change or remove _a lot_ in Knex without a breaking-change warning..

The reason I call it a breaking change is because for some applications that may have used Knex extensively will undoubtedly have used `.whereIn` in this exact context. Changing something like this in a minor version _(that is to say __not__ a breaking change)_ could potentially result in applications breaking left right and center. If that's not a breaking change, I don't know what is.

I don't see why `.whereIn` should silently ignore this scenario if all other `.whereX` functions throw errors, such as `.whereExists(<empty>)`, `.where({column: undefined})`, etc etc.. Surely it's more "surprising" the user to completely ignore a requested criteria.

@tgriesser What are your thoughts on this now compared to few years ago #477 ?

**Comment by kibertoad** [comment] 2018-11-08 15:06
@wubzz I'm basing this on precedents within the project; previously @elhigu mentioned that he does not consider changing ambiguous undocumented aspects of functionality a breaking change (e. g. how "schema.tableName" syntax became unsupported without a prior warning in some places). Which actually did break some production code :).

I agree that ignoring criteria is also going to be surprising, personally I'm more in favour of throwing an error.

**Comment by wubzz** [comment] 2018-11-08 20:46
I feel there's a need to differentiate between accidental and deliberate breaking changes, documented or not. Don't know about the change you're referring to _(even if maybe I should)_ and if it was deliberate or not, but in this case we'd know the outcome beforehand.

We seem to agree that silently ignoring is out of the question. The remaining alternative is to throw an error. Neither of these changes solve what is described in the issue example in terms of output. For dynamic lists you would __always__ have to `if(condition) { builder.whereIn() }`

Turns out `.whereIn` is also consistent with the other `.where` functions when it comes to undefined values, so there's no consistency to be gained from this. An empty array `[]` surely is technically valid?

__So I guess my question is:__ What is to be gained from changing this given the facts above?

My two cents is to keep it the way it is, but add it to docs.

**Comment by kibertoad** [comment] 2018-11-08 20:53
@wubzz I mean https://github.com/tgriesser/knex/issues/2499 which was caused by https://github.com/tgriesser/knex/commit/7ff766f7a380dbea97b99e4d3bd2077a7b9f8f35 - but you are right, there wasn't originally an expectation it will break anything.

> `Turns out .whereIn is also consistent with the other .where functions when it comes to undefined values`  

Documentation claims otherwise: 
`Supplying knex with an undefined value to any of the where functions will cause knex to throw an error during sql compilation. This is both for yours and our sake. Knex cannot know what to do with undefined values in a where clause, and generally it would be a programmatic error to supply one to begin with. `

` For dynamic lists you would always have to if(condition) { builder.whereIn() }`

But you already need to do this for .where() statements.

> An empty array [] surely is technically valid?

Yes, but in all cases you would want to short-circuit call and never hit DB in the first place if you already know at query building time that you are getting 0 results no matter what. Meaning that remaining cases are almost always going to be due to users being negligent.

**Comment by HurSungYun** [comment] 2018-11-09 01:43
Of course, everyone should write code like this `if(condition) { builder.whereIn() }` and I agree with it.

However, in my case of using Knex for the first time, I didn't know that fact and made a mistake of not checking the `list.length`.

Because Knex ignores invalid input and builds query like `1 = 0`, I spent lots of time to understand the reason my query doesn't work well.

I believe if Knex throws error when empty list is passed, users can figure out the fact that they need to check the length of list more quickly.

Shouldn't we guide users to use Knex.js properly with errors when invalid input is passed? I believe it would be a more generous way than ignore it silently.

**Comment by elhigu** [comment] 2018-11-09 07:18
This is actually a feature and it works like this by design. So closing as not a bug. Could be documented though.

**Closed by elhigu** 2018-11-09 07:18 UTC
Labels: breaking change, discussion

**Comment by kibertoad** [comment] 2018-11-09 08:49
Right, so we have team majority on the issue and path forward is clear 👍.
I'll update documentation.

**Comment by ricardograca** [comment] 2018-11-09 09:48
OTOH, `whereIn([])` seems it should logically map to `WHERE something IN ()` which is invalid syntax, so the fact that in knex it still generates a valid syntax could be a bit unexpected.

**Comment by kibertoad** [comment] 2018-11-09 09:49
@ricardograca Yup, that's pretty much how I personally see it, for me empty array is pretty much same thing as undefined in this case.

**Comment by elhigu** [comment] 2018-11-09 10:03
Main point is that it was done current way by design and it was not an accident and it is the same way that many other ORMs handle it (like e.g. hibernate). It is just the way Tim wanted it to work originally, because it is more convenient for the end user of knex API.

> OTOH, whereIn([]) seems it should logically map to WHERE something IN () which is invalid syntax, so the fact that in knex it still generates a valid syntax could be a bit unexpected.

For average user of knex `.whereIn('colName', [])` throwing an error because of invalid SQL syntax is very unexpected behavior. They would expect it to match with nothing (because average knex user actually seems to have very limited knowledge of SQL).

**Comment by ricardograca** [comment] 2018-11-09 10:11
That makes sense as long as it's documented, so I think this should be reopened until the docs are updated.

**Comment by kibertoad** [comment] 2018-11-09 10:13
@ricardograca I've created separate issue in doc repo for that.

**Comment by vantaboard** [comment] 2023-02-06 22:56
Is there some shorthand that we could use though? A shorthand that checks the length and then skips the query if the length is falsy?
