### ISSUE TITLE
"With" knex... error table or view doesn't exist

### ISSUE THREAD

**Issue by CamShft** [tgriesser/knex#3166] opened 2019-04-25 18:21 UTC
# VSCode

Knex version: 0.14.5
Database + version:  Oracle - 10.2.0.3.0
OS:  window 7

 @atiertant 

# Bug
i tried to implement the "With" like the doc said: https://knexjs.org/#Builder-with
but i got a bug.
1. The bug is when i tried to get a result from this query : 
knex queryBuilder: 
```
let query = client
      .distinct(' T.FSID activitySubTypeId')
      .select('T.DESCRIPTION descr', ' VIEW_X.STATUT')
      .with('VIEW_X', (qb: knex.QueryBuilder) => {
        qb.distinct('TABLE_2.ID')
          .select(' TABLE_2.STATUT')
          .from('REP.TABLE_2')
          .where('TABLE_2.OID', buildingId)
          .andWhere('TABLE_2.FID', activityTypeId)
          .andWhere('TABLE_2.STATUT', status ? maintenanceMangerStatus[status.toUpperCase()] : maintenanceMangerStatus.ACTIVE);
      })
      .from('TABLE_1.TYPE T, VIEW_X')
      .where('T.FID', activityTypeId)
      .andWhereRaw(`T.FSID = VIEW_X.FSID`);

    const sort = orderBy.length
      ? orderBy
      : [{ field: 'activitySubTypeId', direction: direction.ASC }];
    query = orderByIterator(query, sort);
```
sql genereated : 
```
WITH
    VIEW_X
    AS
        (SELECT DISTINCT TABLE_2.ID, TABLE_2.STATUT
           FROM REP.TABLE_2
          WHERE     TABLE_2.OID= '12'
                AND TABLE_2.FID= '1'
                AND TABLE_2.STATUT = 'A')
  SELECT DISTINCT
         T.FSID activitySubTypeId, T.DESCRIPTION descr, VIEW_X.STATUT
    FROM TABLE_1.TYPE T, VIEW_X
   WHERE T.FID= '16' AND T.FSID= VIEW_X.FSID
ORDER BY activitySubTypeId ASC;
```

2. Error message : 

> ORA-00942: table or view does not exist

Thanks !

**Comment by elhigu** [comment] 2019-04-25 22:06
And what is expected query in that case? Please create minimal reproduction code. You just might have written any table name wrong and oracle would throw that error.

Closing as cannot reproduce, can be reopened if reproduction code or correct output sql is added.

**Closed by elhigu** 2019-04-25 22:06 UTC

**Comment by CamShft** [comment] 2019-04-26 14:01
> And what is expected query in that case? Please create minimal reproduction code. You just might have written any table name wrong and oracle would throw that error.
> 
> Closing as cannot reproduce, can be reopened if reproduction code or correct output sql is added.

if the name was incorrect, why i can execute the sql in TOAD and i get the result that i expected :o

**Comment by elhigu** [comment] 2019-04-26 22:11
> ( same as the sql genereated by knex | copy/paste)

That is not the same query, nor copy/paste from knex. One generated by knex would look completely different as you can see here https://runkit.com/embed/sc33wjmqgjen and in the error message returned by oracle. Maybe you have case sensitivity issue since I see you are not quoting your identifiers.

Please add reproduction case if you find out that there is actually bug in knex.
