### ISSUE TITLE
Knex >= 0.15.0 always require mssql npm package

### ISSUE THREAD

**Issue by noreplyme** [tgriesser/knex#3206] opened 2019-05-17 14:31 UTC
# Environment

Knex version: 0.15.0 and newer
Database + version: no db, only generating sql queries under sqlite2
OS: osx

# Bug
Seems Knex requires `mssql` npm package installed in project.
Error I got after adding Knex into project:
```
 ERROR  Failed to compile with 1 errors                                                                                                                5:16:46 PM

This dependency was not found:

* mssql/package.json in ./node_modules/knex/lib/dialects/mssql/index.js

To install it, you can run: npm install --save mssql/package.json
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
> see: knex/lib/dialects/mssql/index.js:117

After adding `"mssql": "^5.1.0"` build pass sucessfully. 
But in scope of my project I dont need mssql nor any other adapter except sqlite (if it required for generating sql queries as text strings?)

Also after downgrade to 0.14.6 everything works ok without any mssql package.

**Comment by kibertoad** [comment] 2019-05-17 15:23
Are you using webpack or something along these lines?

**Comment by elhigu** [comment] 2019-05-17 17:53
this should be fixed in the latest version I believe. Closing as cannot reproduce. Please add enough details for validate the issue.

**Closed by elhigu** 2019-05-17 17:53 UTC

**Comment by wimil** [comment] 2020-01-17 15:06
same problem, using version 0.20.8 of k'nex, any solution without having to download the version?

**Comment by kibertoad** [comment] 2020-01-17 15:18
@wimil What version of yarn or npm are you using?

**Comment by wimil** [comment] 2020-01-17 21:24
@kibertoad 
node: v12.12.0
npm: 6.13.4
yarn: 1.19.1

install the package with yarn

**Comment by kibertoad** [comment] 2020-01-17 21:35
@wimil These are up-to-date enough not to cause a problem. However, considering the error that you are getting, I suspect you are using some bundler, e. g. webpack, and that seems to be causing the problem.
If that is the case, can you please check if solution from https://github.com/knex/knex/issues/3130 would work for you?
