### ISSUE TITLE
Raw Bindings Broken for PostgreSQL 9.6.2

### ISSUE THREAD

**Issue by Aslan11** [tgriesser/knex#2053] opened 2017-05-09 23:03 UTC
Expected
```
knex.raw('select * from users where id in (?)', [[1, 2, 3]])
Outputs:
select * from users where id in (1,2,3)
```

Actual
```
knex.raw('select * from users where id in (?)', [[1, 2, 3]])
Outputs:
select * from users where id in ('{1,2,3}')
```

The actual where syntax does not work in PostgreSQL 9.6.2

**Comment by elhigu** [comment] 2017-05-10 05:46
Duplicate of https://github.com/tgriesser/knex/issues/1733

Postgres has multiple different array/list syntaxes, `knex.raw` doesn't know anything about the context where certain binding is used, so it cannot know which syntax you are trying to use. 

So arrays are always outputted like https://www.postgresql.org/docs/8.2/static/arrays.html

Code you are trying to add should be written like:

```js
let array = [1,2,3];
knex.raw(`select * from users where id in (${array.map('?').join(',')})`, array)
```

This comes up every now and then and should be documented better.

**Closed by elhigu** 2017-05-10 05:46 UTC

**Comment by rkaw92** [comment] 2017-05-10 15:42
Actually, the root cause here was that `IN` doesn't really work on arrays. With arrays, one should use `= ANY(?)` and pass the array there.

**Comment by elhigu** [comment] 2017-05-10 15:58
Yeah that works too as I explained in #1733. However I don't know if there is any difference in performance matter. 

Usually I prefer subqueries which returns the id list to prevent having to pass big id lists back and forth to db server, but sometimes these array tricks are just needed.
