### ISSUE TITLE
Knex + RDS + bindings = increasing ClientRead

### ISSUE THREAD

**Issue by mejt** [tgriesser/knex#3264] opened 2019-06-07 13:03 UTC
# Environment

Knex version: 0.17.3
Database + version: postgres 9.6.9
OS: AWS RDS

# Bug
Hi, it is probably that I detected issue in knex related with prepared statements. Unfortunately I am not sure that it is problem with implementation of knex but I want to describe my problem for potential detect issue.

I build queries using knex query builder and as I understand it use by default bindings. For example I have generated such query:
```
select "uuid", "country_code", ."updated", "default_title" from "schema"."table" where "uuid" in ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
```
it works rather fine, but when I have huge load on ma service my RDS stucked on `ClientRead` which in result I reach a lot of errors: `TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`.

I did simple solution in my code for comparison (which improved results). I just converted knex builder to string and next executed query.

```
knex.raw(knex.select('').from('table').whereIn([...]).toString()).then(...)
```

I don't feel comfortable with this solution and I am not sure that it is safe. Is it a issue on knex side or I did something wrong? 

Regards

**Comment by elhigu** [comment] 2019-06-07 13:13
It id not safe and may cause many kind of problems, creating prepared statements for queries is done by pg driver, so there is not much that knex can do about it. Sounds like you have some problems on application code, which causes too much pressure to database...

With current information and without any reproduction there is very little that we can do to help. You could try to setup connection limits to be bigger in DB side from RDS db properties and increase pool size. And watch how many connections are used in RDS when you run your application. Also you could try with local DB if you can reproduce your problems there. It would be really helpful.

**Comment by elhigu** [comment] 2019-06-07 13:15
closing for now, since there is nothing we can do for this right now. Can be reopened if it seems to be a bug in knex.

**Closed by elhigu** 2019-06-07 13:15 UTC
